### ISSUE TITLE
Check for "typed relation fields" fails incorrectly

### ISSUE THREAD

**Issue by harrikoo** [mjordan/islandora_workbench#107]
This may be already known, in which case feel free to close the issues.

The technique described entering data in "Typed Relation Fields" like `field_linked_agent` works as described in the documentation, but the `--check` marks them as invalid.

For example, in `field_linked_agent`,  `--check` accepts the field formatted like `person:New Person` which is not accepted by the actual `create` operation. The working format, also described in the documentation, `relators:pht:34` is accepted by the actual `create`, but not by `--check`

This is confusing.

**Comment by mjordan** [comment]
@harrikoo I'm very sorry to have missed this issue. I'll look into it.

**Comment by mjordan** [comment]
Turns out this is a known issue (validation code is not yet complete; see #41).

**Comment by mjordan** [comment]
@harrikoo Workbench now validates values in typed relation fields properly. If you have time, please test the master branch. I haven't added integration tests yet but will do so soon.

**Comment by mjordan** [comment]
OK to close?

**Comment by harrikoo** [comment]
I'm sorry, I'm currently unable to test this since I don't work with 
Islandora any more; I trust your judgment on this issue.

Best, Harri Kiiskinen

**Comment by mjordan** [comment]
OK, thank you for letting me know, and thank you for trying Islandora Workbench.
