### ISSUE TITLE
Default settings for Vocabulary terms view in Islandora lead to multiple term generation

### ISSUE THREAD

**Issue by harrikoo** [mjordan/islandora_workbench#108]
Noticed the following behaviour:

The default settings for the view "Terms in Vocabulary" that offers the `/vocabulary` REST endpoint has a default setting for PAGER to limit the display to 10 entries.

The workbench code, in [workbench_utils.py](https://github.com/mjordan/islandora_workbench/blob/ebc03385e27fbe8d78f1df949967322ff5d71390/workbench_utils.py#L889) therefore only returns the ten first terms in a vocabulary. At the point the 11th term has been created, there will no more be matches to this term, and subsequent appearances of this term lead to this term being created again.

In a large dataset with several terms, this results in huge numbers of duplicate terms.

As far I can see, this cannot be fixed here. The simplest solution is to change the default pager in the view "Terms in Vocabulary" to "Display All Items".

Once again, I'm not sure whether this is the best place to report this, but this was the place I searched for trying to figure out, what was wrong.

Harri

**Comment by mjordan** [comment]
Sorry again, I somehow missed this issue. I've opened it against the Drupal module, closing here. Thanks for finding this.
