### ISSUE TITLE
Add ability to create Typed Relation taxonomy terms

### ISSUE THREAD

**Issue by dannylamb** [mjordan/islandora_workbench#110]
Right now you can work with existing taxonomy terms using tids using this pattern: `namespace:rel:tid` (e.g. `relators:ctb:1` to make a 'Contributor from taxonomy term 1).  But if you're running a 'Create' operation, you cannot make typed relation values from scratch.  It would be nice to be able to use a pattern like `namespace:rel:vid:name` and have it make the term and give it a typed relation in one shot.

**Comment by mjordan** [comment]
I think this is a specific instance of the problem described in #111.

**Comment by mjordan** [comment]
This issue and #120 should be addressed together.

**Comment by mjordan** [comment]
Resolved with b5c4f778c2667f92bdd59771b5e4af66ef3a2192.
