### ISSUE TITLE
config --check is not connecting to the host

### ISSUE THREAD

**Issue by Parathantl** [mjordan/islandora_workbench#123]
I installed all the dependencies in my local. I have a Drupal installed system in server. Say for example nf.org/.
Enabled the Rest UI and installed Islandora default modules. Then I configured the create.yml and tried this code

`./workbench --config create.yml --check`

**Error: Workbench cannot connect to http://nf.org/. Please check the hostname or network.**

**Comment by mjordan** [comment]
http://nf.org is redircting to another hostname. I'll see if I can add a flag to allow redirects by default. If I do that, can you test my branch?

**Comment by mjordan** [comment]
@Parathantl replace line 214 of workbench_utils.py:

`host_response = requests.head(config['host'])`

with 

`host_response = requests.head(config['host'], allow_redirects=True)`

Let me know if this eliminates the "Error: Workbench cannot connect to http://nf.org/. Please check the hostname or network." error.

**Comment by mjordan** [comment]
@Parathantl if this change gets you paste the `--check` stage, I will add it to the codebase.

**Comment by Parathantl** [comment]
@mjordan Sorry for the inconvenient. The redirect suggestion is unfortunately not worked. I just pu the nf.org domain as an example just to hide my site. Do I need to share the actual domain name?

**Comment by mjordan** [comment]
I can't debug this problem without it. If you share it with me via email, I will keep it secret. mjordan at sfu.ca.

**Comment by Parathantl** [comment]
Shared the domain via mail

**Comment by mjordan** [comment]
Thank you, I will investigate.

**Comment by mjordan** [comment]
A `curl` request to your site works fine, but a request using the Python library "requests" (which is what Workbench uses) returns a `406 Client Error: Not Acceptable` response. I haven't seen this before. I will continue to look into this.

**Comment by mjordan** [comment]
Thanks to https://stackoverflow.com/questions/56101612/python-requests-http-response-406 I was able to identify the problem. I changed the User-Agent string and I was able to connect using Workbench. I will open a new issue to add a user agent to all requests, but in the meantime, change line 214 of workbench_utils from 

`host_response = requests.head(config['host'])`

to

`host_response = requests.head(config['host'], headers={"User-Agent": "Islanodora Workbench"})`

and try running workbench with `--check` again.

**Comment by mjordan** [comment]
@Parathantl I'm sorry, I just realized that this fix will allow Workbench to connect to your host, but it will eventually fail again because the fix I suggested is local to the `--check` code. In order for this to work i will need to add the User Agent option to all requests. I'll try to get to that by next weekend. Sorry for not thinking of this when I wrote my comment above.

**Comment by Parathantl** [comment]
No worries @mjordan . I will try fixing it in my local code as much as I can. Let me know when you are done. Thanks for this great tool. We are hoping to use this to save our time.

**Comment by mjordan** [comment]
It's not that many places, only within the `issue_request` function at https://github.com/mjordan/islandora_workbench/blob/master/workbench_utils.py#L130 and within the `ping_islandora` function at https://github.com/mjordan/islandora_workbench/blob/master/workbench_utils.py#L210. I am going to add this feature this weekend, so be aware that any changes you make locally will be temporary.

I'm happy to hear you will find Islandora Workbench useful!

**Comment by mjordan** [comment]
@Parathantl I've resolved the User-Agent issue. Can  you please revert your local changes and pull in the updates to the `master` branch and test?

**Comment by Parathantl** [comment]
Thanks for the quick update. It connects to my site. I am closing this ticket
