### ISSUE TITLE
Key error when ran ./workbench --config create.yml

### ISSUE THREAD

**Issue by Parathantl** [mjordan/islandora_workbench#124]
In the CSV file, I had a column called 'field_genre' the same machine name as in my islandora content-type. But it showed me the following error

`Traceback (most recent call last):
  File "./workbench", line 738, in <module>
    create()
  File "./workbench", line 97, in create
    if field_definitions[custom_field]['field_type'] == 'entity_reference':
KeyError: 'field_genre'
`

Filed another issue previously too. Would it be the issue with not connecting to the host?

**Comment by mjordan** [comment]
Yes, we need to resolve #123 first.

**Comment by mjordan** [comment]
If changes I made in #123 solve that issue for you, please close this issue.

**Comment by Parathantl** [comment]
Closing this one too. Thanks
