### ISSUE TITLE
SIte is not get created with nodes

### ISSUE THREAD

**Issue by Parathantl** [mjordan/islandora_workbench#134]
I am facing an issue

When run 

**./workbench --config create.yml --check**

OK, **My-DOMAIN** is accessible using the credentials provided.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file input_data/migration.csv found.
OK, all 10 rows in the CSV file have the same number of columns as there are headers (4).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
Warning: Issues detected with validating taxonomy terms used in the CSV column "field_model". See the Workbench log for important details.
OK, term IDs/names in CSV file exist in their respective taxonomies.
OK, files named in the CSV "file" column are all present; the "allow_missing_files" option is enabled and empty "file" values exist.
Configuration and input data appear to be valid.

Even when I run **./workbench --config create.yml**

It doesn't show any error. 

But the site is not get updated. Could you please help with what would be the issue?

**Comment by mjordan** [comment]
Look in workbench.log for more detail. In particular, "Warning: Issues detected with validating taxonomy terms used in the CSV column "field_model". See the Workbench log for important details." suggests that you are using invalid values in that column.

Also, can you confirm that you have installed the Islandora Workbench Integration module on your Drupal?

**Comment by Parathantl** [comment]
This is the Log I found in the log file

20-Oct-20 00:21:06 - ERROR - Node for CSV record 2465 not created, HTTP response code was 422.
20-Oct-20 00:21:07 - ERROR - Node for CSV record 9869 not created, HTTP response code was 422.
20-Oct-20 00:21:08 - ERROR - Node for CSV record 9833 not created, HTTP response code was 422.

I have installed the Workbench Integration and enabled it

**Comment by Parathantl** [comment]
This was the log ouput when I added a new column which is a taxonomy term

20-Oct-20 00:44:05 - ERROR - Node for CSV record 18510 not created, HTTP response code was 422.
20-Oct-20 00:44:06 - INFO - Term "நூல்" (term ID 6) already exists in vocabulary "genre".
20-Oct-20 00:44:08 - ERROR - Node for CSV record 4214 not created, HTTP response code was 422.
20-Oct-20 00:44:09 - INFO - Term "நூல்" (term ID 6) already exists in vocabulary "genre".
20-Oct-20 00:44:10 - ERROR - Node for CSV record 4215 not created, HTTP response code was 422.
20-Oct-20 00:44:12 - INFO - Term "நூல்" (term ID 6) already exists in vocabulary "genre".
20-Oct-20 00:44:13 - ERROR - Node for CSV record 6307 not created, HTTP response code was 422.

**Comment by Parathantl** [comment]
@mjordan That was a mistake from my side. I haven't given any values for "field_model" column.
I placed "islandora_models" for all data in the field_model.
And it worked for creating nodes.

Some other things I need to get clarified is
for update and delete it asks for node_id.

This means that I need to give the node id
That is for example

mydomain.com/node/86

86 needs to be in the column?

**Comment by mjordan** [comment]
Good to hear you found the source of the 422 responses. `--check` should also have left some entries in your log that the taxonomy term "islandora_models" didn't exist. Can you see those?

About the node_id, yes, it's 86 in the example you provide.

Also, thanks for testing input that is not in Latic characters. Good to see that non-Latin characters for taxonomy terms works.

**Comment by Parathantl** [comment]
Yes, I can see that one too.

20-Oct-20 14:02:32 - WARNING - CSV field "field_genre" in row 2 contains a term ("நூல்") that is not in the referenced vocabulary ("genre"). That tag will be added to that vocabulary.
20-Oct-20 14:02:34 - WARNING - CSV field "field_model" in row 3 contains a term ("islandora_models") that is not in the referenced vocabulary ("islandora_models"). That tag will be added to that vocabulary.

I am having other issue when handling Linked Agent.

I created a new column in the CSV as **field_linked_agent** and put the following in that column

- relators:aut:Pelikan, Jaroslav
- relators:aut:Iersel, B. Van

I am having this issue in the terminal console

Error: CSV column header "field_linked_agent" does not appear to match any Drupal field names.

**Comment by mjordan** [comment]
Currently you can't use string as the third part of the typed relation value and expect to create the new term. There is an open issue for this at https://github.com/mjordan/islandora_workbench/issues/110. Until that is resolved, the terms you reference in your typed relation CSV values need to look like `relators:aut:45` instead of `relators:aut:Iersel, B. Van`.

I'm not sure why it's not recognizing the `field_linked_agent` column but I am guessing it's related to this. Can you create a couple of "family" terms and use their term IDs instead of the term name? I've just done that and it works for me, although running `--check` fails (there is also an open issue for that, https://github.com/mjordan/islandora_workbench/issues/41).

**Comment by Parathantl** [comment]
@mjordan Thanks for your guidance. Yes even though it failed in the `--check` it has created the node when putting Taxonomy term ID. Looking forward to have a try with Workbench. Its really awesome. Since Drupal and Islandora are new to me. If possible I am too looking forward to contribute.

Shall I close this ticket?

**Comment by mjordan** [comment]
Sorry @Parathantl, yes close please. Don't hesitate to open new issues.

**Comment by Parathantl** [comment]
@mjordan Sure. Thanks
