### ISSUE TITLE
Multi-value Columns

### ISSUE THREAD

**Issue by seth-shaw-unlv** [mjordan/islandora_workbench#19]
Some fields allow multiple values (e.g. [field_subject](https://github.com/Islandora-CLAW/islandora_defaults/blob/8.x-1.x/config/install/field.field.node.islandora_object.field_subject.yml), [cardinality set on field storage config](https://github.com/Islandora-CLAW/islandora_defaults/blob/8.x-1.x/config/install/field.storage.node.field_subject.yml#L15)).

One way to allow multiple values is to configure the column with a sub-delimiter. For example, the file is delimited with commas, and then a particular field can be delimited with semicolons. The example CSV below has a field 'field_subject' that takes a semicolon delimited list of term ids.
```
field_identifier,title,field_subject,file
example001,My Image,5;7;33,example001.tif
```

This example extended to support field lookups (#18) could take a semicolon delimited list of subject URIs:
```
field_identifier,title,field_subject,file
example001,My Image,http://id.loc.gov/authorities/subjects/sh85049588;http://id.loc.gov/authorities/genreForms/gf2017027249;http://sws.geonames.org/4013157/,example001.tif
```

**Comment by mjordan** [comment]
Working on this now and over the weekend.

**Comment by mjordan** [comment]
Added for create and update tasks, and for string and entity-reference fields as of 6d050d675105f37576e03aa27a401f0ace78fe77. 

I will add the option to configure a subdelimiter character).

**Comment by mjordan** [comment]
As of e95de1da45b88a6ae4a22705d245047978e8be36 you can set the subdelimiter character like this (defaults to `|`):

`subdelimiter: ";"`
