### ISSUE TITLE
Support Linked Agents (TypedRelation Fields)

### ISSUE THREAD

**Issue by seth-shaw-unlv** [mjordan/islandora_workbench#20]
Islandora Defaults uses the [TypedRelations](https://github.com/Islandora-CLAW/controlled_access_terms/blob/8.x-1.x/src/Plugin/Field/FieldType/TypedRelation.php) FieldType for [field_linked_agent](https://github.com/Islandora-CLAW/islandora_defaults/blob/8.x-1.x/config/install/field.field.node.islandora_object.field_linked_agent.yml). This means that a valid value for a field_linked_agent field includes both the relator (e.g. 'relators:pht' for a Photographer) and the Photographer's term id. 

Also, assuming we implement multi-valued columns (#19), we could have a cell listing the relator code/term id pairs delimited by semi-colons.

**Comment by mjordan** [comment]
@seth-shaw-unlv It would be feasible enough to join the relator and the term ID with a character, but how would be handle multiple values for that field? Something like `pht:5|pht:34`? Would we need the `relators:` namespace?

**Comment by seth-shaw-unlv** [comment]
@mjordan we do need the relators namespace as that is part of the field value. Other namespaces, such as schema, can also be used. So, you could have `"relators:pht|5;schema:author|34"`.

**Comment by mjordan** [comment]
Sounds good. We allow users to define `subdelimiter` for multivalued fields, but I don't think we need to provide an option to define the namespace / value pair. Maybe we could reserve `:` and not allow it to be used as a subdelimiter (and check that it's not configured as the `subdelimter` value).

**Comment by mjordan** [comment]
Sorry, my last comment is incomplete. Since we allow users to define `subdelimiter`, maybe a syntax like `"relators:pht:5;schema:author:34"` (multivalue subdelimiter is `;`) would be OK, in other words, the namespace / relator / local value triple would need to use `:` to join all three parts. Then people could use whatever multivalue subdelimiter they want as long as it's not a `:`.

Would that kind of syntax apply to all TypedRelation fields?

**Comment by mjordan** [comment]
Since we can now get a field's type during `--check`, we can also validate this complex structure.

**Comment by seth-shaw-unlv** [comment]
@mjordan we can make that work. After we explode on the sub-delimiter we can split each field instance value on the last colon seen to get the field's predicate and tid.

**Comment by mjordan** [comment]
Cool, I'll work on implementing this over the next day or two.

**Comment by mjordan** [comment]
OK, got this working for the 'create' task, I'll move on to the 'update' task next. README has also been updated.

**Comment by mjordan** [comment]
Also, validation of these fields within --check is not yet done.

**Comment by mjordan** [comment]
@seth-shaw-unlv this is working but needs some testing for the various cardinalities. I'll do that over the weekend and then hand it over to you for some smoketesting.

**Comment by mjordan** [comment]
795da71b573d23ec70912ee7f30378ab32696afa adds create and update support for cardinalities of unlimited, 1, and between 1 and unlimited. Note: We do not yet validate the CSV values for fields of this type. I've opened a separate issue for this at #41.

**Comment by mjordan** [comment]
I've merged the issue-20 branch into master, but if you can do some smoke tests I'd appreciate it. No sweat if you don't have time, I've tested it fairly thoroughly and we can address any issues that come up later.
