### ISSUE TITLE
Reports of google_sheets_gid not working

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#206]
During yesterday's Hack/Doc, several people reported that the `google_sheets_gid` config option wasn't working. I'll investigate.

**Comment by mjordan** [comment]
Also reported in #202.

**Comment by mjordan** [comment]
@Digital-Grinnell @DonRichards changing the value of `google_sheets_gid` works for me without failure. After a bunch of attempts, I can't replicate the case where the data being fetched is not from the sheet identified by the gid. I've also added an integration test (https://github.com/mjordan/islandora_workbench/blob/main/tests/islandora_tests.py#L670) that runs `--check` on four different worksheets and counts the number of CSV rows in each. This test passes.

Given that the automated test passes, I am convinced that the strange behavior people are seeing is not caused by a bug in the `google_sheets_gid` functionality. My best hunch at this point is that changes are not showing up in the CSV extracted from the Google Sheet because of changed cells are not being "saved" due to the cursor focus issue described in #202. Does that sound reasonable?

**Comment by Digital-Grinnell** [comment]
Ok, I don't think the Google Sheets cursor is the issue here, I've made sure I changed mine a number of times, always looking at the "Last updated..." note that appears at the top of the sheet to indicate that my changes have been made.

However, I think I did find the cause of this, at least in my case.  Look closely at my `hackdoc_demo2.yml` file contents:

```
task: create
host: "http://97.107.189.30"
username: admin
password: islandora
Allow_adding_terms: true
Google_sheets_gid: 1094504353
# input_csv: google_sheet.csv
input_csv: 'https://docs.google.com/spreadsheets/d/12QezZCbW2ZIO8WJd8kpMgnt6OI-JVSXQ-rTs-0LA4mI/edit?usp=sharing'
```
Note the case of the `Google_sheets_gid` parameter above, and the output:

```
╭─mark@Marks-MacBook-Pro ~/GitHub/islandora_workbench ‹main*›
╰─$ ./workbench --config hackdoc_demo2.yml --check                   
OK, connection to Drupal at http://97.107.189.30 verified.
OK, configuration file has all required values (did not check for optional values).
Extracting CSV data from https://docs.google.com/spreadsheets/d/12QezZCbW2ZIO8WJd8kpMgnt6OI-JVSXQ-rTs-0LA4mI/edit?usp=sharing to input_data/google_sheet.csv.
OK, CSV file input_data/google_sheet.csv found.
OK, all 2 rows in the CSV file have the same number of columns as there are headers (8).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, ETDF field values in the CSV file validate.
Error: CSV field "field_subject" in row 1 contains a term ("Task3") that is not in the referenced vocabulary ("subject").
```

So, I changed the parameters to all lowercase like you see here:

```
task: create
host: "http://97.107.189.30"
username: admin
password: islandora
allow_adding_terms: true
google_sheets_gid: 1094504353
# input_csv: google_sheet.csv
input_csv: 'https://docs.google.com/spreadsheets/d/12QezZCbW2ZIO8WJd8kpMgnt6OI-JVSXQ-rTs-0LA4mI/edit?usp=sharing'
```

And the subsequent output looks good:

```
╭─mark@Marks-MacBook-Pro ~/GitHub/islandora_workbench ‹main*›
╰─$ ./workbench --config hackdoc_demo2.yml --check
OK, connection to Drupal at http://97.107.189.30 verified.
OK, configuration file has all required values (did not check for optional values).
Extracting CSV data from https://docs.google.com/spreadsheets/d/12QezZCbW2ZIO8WJd8kpMgnt6OI-JVSXQ-rTs-0LA4mI/edit?usp=sharing to input_data/google_sheet.csv.
OK, CSV file input_data/google_sheet.csv found.
OK, all 2 rows in the CSV file have the same number of columns as there are headers (8).
Error: CSV column header "field_Linked_agent" does not match any Drupal field names.
```

I'm also pleased to see that the application is checking the CSV headings to make sure there are indeed corresponding Drupal field names.

**So, the moral of the story here...  both Workbench config file parameters AND data column headings are CASE SENSITIVE.**  I'd like to reiterate my IMI-experience comment from another issue (https://github.com/mjordan/islandora_workbench/issues/199) and suggest that Workbench sanitize all such parameters AND column headings by converting them automatically to lowercase.

**Comment by Digital-Grinnell** [comment]
I'd also like to suggest that the `google_sheet_gid` value be echoed in the output, maybe something like this:

```
Extracting CSV data from https://docs.google.com/spreadsheets/d/12QezZCbW2ZIO8WJd8kpMgnt6OI-JVSXQ-rTs-0LA4mI/edit?usp=sharing to input_data/google_sheet.csv.  Optional google_sheet_gid is NOT present.
```
or,

```
Extracting CSV data from https://docs.google.com/spreadsheets/d/12QezZCbW2ZIO8WJd8kpMgnt6OI-JVSXQ-rTs-0LA4mI/edit?usp=sharing to input_data/google_sheet.csv with google_sheet_gid:1094504353.
```

Or better yet, use and echo the Google Sheet tab names instead of the less-friendly `gid`.   IMI does this and we leverage it to our advantage at GC.

**Comment by mjordan** [comment]
Tab names would be useful. Can you point me to the IMI code (Github, etc.) that gets the tab names?

**Comment by mjordan** [comment]
Re. converting to lower case is a good plan. Thanks for the suggestion.

**Comment by mjordan** [comment]
@Digital-Grinnell found the IMI code. Looks like IMI uses the Google Sheets API, which is way richer, and a lot more complex, than the method Workbench uses for fetching CSV from a Sheet. To be honest, I won't be working on incorporating that API that until I finish some other, longstanding clean up on core Workbench code.

**Comment by mjordan** [comment]
Echoing the gid to the user is also a good idea.

**Comment by mjordan** [comment]
@Digital-Grinnell as of 28c1f53ca9fa9f5f49018793134902328d5b6499 the Sheets gid is echoed to the user as you suggest above.

**Comment by mjordan** [comment]
As of https://github.com/mjordan/islandora_workbench/commit/28c1f53ca9fa9f5f49018793134902328d5b6499 config keys such as `google_sheets_gid` are normalized to lower case automatically, so `Google_sheets_gid` is allowed.Thanks for catching that.

However, I'm not sold on normalizing CSV column headers since `--check` flags any headers that that don't match Drupal field names (which, as you point out, are always lowercase). I'm happy to discuss that further but I don't think autoconverting the CSV column headers to lowercase is worth the added code complexity.

**Comment by mjordan** [comment]
Since this is related to #202 and we closed that one, same goes here - if you see any strange behavior on this feature please open a new issue.
