### ISSUE TITLE
Filenames and extensions

### ISSUE THREAD

**Issue by ajstanley** [mjordan/islandora_workbench#214]
If your file's URL points to an Islandora 7 instance, it will have no extension, and will fail when trying to add it to a media -
`example.com/islandora/object/islandora:1/datastream/OBJ/download` saves a file in the input_dir called `download`. The file has no extension and has a troublingly non-unique name.  I've added an option to use the node title for the media name.

I've added a default_file_extension to tack on to any file that has no extension, but this has some obvious limitations.  I tried installing the magic library so we could read the file's mime-type directly, but it doesn't seem to play very nicely with python3.

I can stick a pull request in once I have it generalized, but this could use some input.

**Comment by mjordan** [comment]
Great idea, thanks for opening this. Last weekend I added a helper script to get CSV data from Solr and also accompanying OBJs. The `requests` code you are describing could be based on https://github.com/mjordan/islandora_workbench/blob/main/scripts/get_islandora_7_content.py#L163 . I too noticed that the Python `mimetypes` library doesn't work the way I expected and included https://github.com/mjordan/islandora_workbench/blob/main/scripts/get_islandora_7_content.py#L53 in my script as a workaround.

Please feel free to open a PR if you have the time. It would be great to be able to reference datastreams in Islandora as remote files.

**Comment by mjordan** [comment]
Just occurred to me - we need to make sure that if we add code to download datastreams from and Islanodra repo, non-Islandora downloads continue to work. Not sure of best way to conditionally apply that logic. Maybe check download URL for pattern `/islandora/object/.*/datastream/.*/download` or some such?

**Comment by ajstanley** [comment]
The logic I have set up now checks for a file extension.  If its missing I fire it out to  the` magic.from_file` method, then I use `mimetypes.guess_extension` to return the desired extension and rename the file from `someFile` to s`someFile.abc`.  If the file has an extension already I leave it alone.

Whether we use the file name or the node title as the media name is toggled with `use_node_title_for_media: 1` in the config file.

I think this covers the weirdness that comes from Islandora not having the original file name contained in OBJ.

I'm cleaning up the code now and making sure it's ready for primetime.  I should have a pull request shortly.

**Comment by mjordan** [comment]
That's better than what I was describing since it's more generalized.

**Comment by mjordan** [comment]
PR #215 merged.
