### ISSUE TITLE
File bloat

### ISSUE THREAD

**Issue by ajstanley** [mjordan/islandora_workbench#218]
When ingesting files from URLs a copy of that file is imported to the workbench computer before being sent off the Islandora 8 instance for ingestion.  Even if we rollback at re-import that downloaded file is never used again.  On large spreadsheets this could result in many megabytes of duplicated storage

We should allow the option of having that file autodelete once it's been added to the Islandora instance.

**Comment by mjordan** [comment]
PR #219 merged.
