### ISSUE TITLE
TypeError after a clean check

### ISSUE THREAD

**Issue by zvowell** [mjordan/islandora_workbench#221]
After getting a "Configuration and input data appear to be valid" message from workbench --check, I'm getting a TypeError when running a real workbench operation (with no --check flag), pretty early on in the process it seems. Here's the output from ---check:

    OK, connection to Drupal at http://localhost:8000 verified.
    OK, configuration file has all required values (did not check for optional values).
    OK, CSV file testBatch_01/barneberg_forTesting_001_withMemberOf-minimal.csv found.
    OK, all 14 rows in the CSV file have the same number of columns as there are headers (13).
    OK, CSV column headers match Drupal field names.
    OK, required Drupal fields are present in the CSV file.
    OK, ETDF field values in the CSV file validate.
    OK, term IDs/names in CSV file exist in their respective taxonomies.
    OK, files named in the CSV "file" column are all present.
    Configuration and input data appear to be valid.

Then when I remove the --check flag, I see:

    OK, connection to Drupal at http://localhost:8000 verified.
    Traceback (most recent call last):
       File "./workbench", line 965, in <module>
         create()
       File "./workbench", line 270, in create
         node = simple_field.create(config, field_definitions, node, row, custom_field)
       File "/mnt/c/Users/zvowell/islandora8_vmTesting/islandora_workbench/workbench_fields.py", line 60, in create
        first_subvalue = truncate_csv_value(custom_field, id_field, field_definitions[custom_field], first_subvalue)
       File "/mnt/c/Users/zvowell/islandora8_vmTesting/islandora_workbench/workbench_utils.py", line 1130, in truncate_csv_value
         if max_length is not None and len(value) > max_length:
    TypeError: '>' not supported between instances of 'int' and 'str'

Here is the csv that I used: https://gist.github.com/zvowell/5cfd6e892375ba69c492f4b09f511bc9

And here is my config file:

    task: create
    host: "http://localhost:8000"
    username: admin
    password: islandora
    input_dir: testBatch_01
    input_csv: barneberg_forTesting_001_withMemberOf-minimal.csv
    allow_adding_terms: true

also fwiw I'm on a PC, and tried this with both a Windows for Linux Subsystem shell, and a Cygwin shell, and got the same error.

**Comment by mjordan** [comment]
Sorry about this - I'm sure we can fix this as we did in #217. I'll do a thorough audit of numeric comparisons and apply that same fix.

**Comment by mjordan** [comment]
@zvowell Can you pull in the latest changes to the main branch and see if they resolve this issue? Depending on how old your main branch is, you may need to rerun setuptools, e.g. `python setup.py install` (five days ago PR #215 added a new library).

I have no idea why I am not able to reproduce this bug on my (linux) system. I can't find any reference to differences between Windows and Linux around simple numeric comparison or typecasting. Thanks for testing on Windows - I have tested Workbench on Windows but I don't do it regularly.

**Comment by zvowell** [comment]
@mjordan thanks for the quick response, the changes fixed the issue. I was able to successfully import 15 records with their TIFFs.

that's really weird how these issues don't come up on linux. Glad it's useful to test it on Windows, I'll definitely keep at it. Thanks for all your work on workbench, it's a big help.

**Comment by mjordan** [comment]
Super, thanks for confirming it worked and for providing more robust Windows experience than I can provide.
