### ISSUE TITLE
Using the subdelimiter config parameter

### ISSUE THREAD

**Issue by Ansel-Hong** [mjordan/islandora_workbench#228]
When I use the config subdelimiter: "," and I try to ingest data into a single-valued field it gives the error "Warning: CSV field "field_description" in (!) record with ID TEST_001 contains more values than the number allowed for that field (1). Workbench will add only the first value." 

Is there another way to only apply the subdelimiter to multivalue fields.

**Comment by mjordan** [comment]
@Ansel-Hong that error message needs to be cleaned up, but if you can share your config file and CSV (or a sample from the CSV) with me I'd be happy to look into what't going on.

**Comment by Ansel-Hong** [comment]
For this csv file, the "field_description" is a single value text field and "field_type" is a multivalued field. When I set the subdelimiter as "," it treats "field_description" as a multivalued field that only accepts one value and only ingests up to "Twine is an open-source tool for telling interactive"

[example.pdf](https://github.com/mjordan/islandora_workbench/files/6024922/example.pdf)

**Comment by mjordan** [comment]
The default delimeter (between fields) is `,` - is there a reason you also want to use `,` as the subdelimiter? By default, the subdelimiter is a pipe (`|`).

**Comment by Ansel-Hong** [comment]
I think we were already using (`|`) for key-pair values so we just wanted to use `,` for convenience sake. Just for clarification, in the documentation (https://mjordan.github.io/islandora_workbench_docs/fields/#field-types) does "single valued field" mean drupal fields that only accept one value?

**Comment by mjordan** [comment]
Correct, single value fields only have one value; multivalued fields have a specific maximum number of values, or an unlmited number of values.

You can use any character as a subdelimiter, other than the same character that is being used as the CSV delimiter. I wouldn't use a comma as a subdelimiter unless you changed the delimiter character to a tab or something other than a comma.

**Comment by Ansel-Hong** [comment]
Ah okay, we'll probably have to change the subdelimiter into another character then. Thanks.

**Comment by mjordan** [comment]
`^` makes a good subdelimiter since it rarely occurs in likely Drupal field values.
