### ISSUE TITLE
Taxonomy terms with namespaces causing errors

### ISSUE THREAD

**Issue by zvowell** [mjordan/islandora_workbench#235]
I know I'm missing something here, but I think I'm following the documentation correctly, specifically the Taxonomy Reference Fields section of https://mjordan.github.io/islandora_workbench_docs/fields/#content-type-specific-fields. I'm happy to contribute to documentation if that turns out to be worthwhile.

When trying to ingest a record with a taxonomy term that uses a namespace (in my csv, it's "person:Chris Juperre"), I'm getting a couple of warning during ``--check``, and then an actual error when running Workbench. Here are the ``--check`` warnings:

    WARNING - CSV field "field_subjects_name" in row 3 contains a term ("Chris Juperre") that is not in the referenced vocabulary ("person"). That term will be created.
    WARNING - Vocabulary "family" referenced in CSV field "field_subjects_name" may not be enabled in the "Terms in vocabulary" View (please confirm it is) or may contains no terms.

Then the info and warning that come from a real job:

    INFO - {'vid': [{'target_id': 'person', 'target_type': 'taxonomy_vocabulary'}], 'status': [{'value': True}], 'name': [{'value': 'Chris Juperre'}], 'description': [{'value': '', 'format': None}], 'weight': [{'value': 0}], 'parent': [{'target_id': None}], 'default_langcode': [{'value': True}], 'path': [{'alias': None, 'pid': None, 'langcode': 'en'}]}
    WARNING - Term 'Chris Juperre' not created, HTTP response code was 422.

...and the error:

    Traceback (most recent call last):
      File "./workbench", line 963, in <module>
        create()
      File "./workbench", line 165, in create
        if config['subdelimiter'] in row[custom_field]:
    TypeError: argument of type 'bool' is not iterable

I'm not sure why Workbench ``--check`` comments on the "family" vocabulary, because the csv doesn't reference it. The only thing I can think of is that ``field_subjects_name`` is not the right field to be using, but it seems right according to the documentation.

Here's the csv (sorry, the relevant term is in the last field): https://gist.github.com/zvowell/ae8b52c02b2bfd3467e3c15df7087b19
And then the config is:

    task: create
    host: "http://localhost:8000"
    username: admin
    password: islandora
    input_dir: testBatch_02_clean
    input_csv: barneberg_forTesting_002_as-imageObjects.csv
    allow_adding_terms: true

**Comment by mjordan** [comment]
That misleading logging is a known issue (#194 to be specific). Drupal's Views REST response returns the same result for vocabularies that are empty as it does for ones that aren't enabled in the View, hence the vague wording of the warning. I need to filter out vocabularies that are referenced by the field being checked but are not namespaced for new terms. That would eliminate most occurances of that warning message while leaving it present when it's important that the user checks that vocabulary. (I think, I logged the issue but haven't gotten to resolving it yet.)

The 422 errors I can't explain. Another user has reported them when trying to create terms before, but I have not been able to replicate or track down what is going on. Which baffles me. Coincidentally (?) they saw them with the Person vocabulary as well. I have not seen that Python `bool` error before though. Can you share your config and CSV with me so I can try to replicate what you are seeing?

**Comment by zvowell** [comment]
thanks @mjordan, let me know if I can provide any more info.

**Comment by mjordan** [comment]
Will do. I'm going to dig into this over the weekend.

**Comment by mjordan** [comment]
@zvowell can you export the configuration of your Person vocabulary for me and paste it into a comment here? To to that, go to `/admin/config/development/configuration/single/export` and choose "Taxonomy vocabulary" in the "Configuration type" list, and then "Person (person)" in the "Configuration name" list.

**Comment by zvowell** [comment]
Here's the Person vocabulary configuration:

    uuid: 516861d0-dcbe-40ce-b1b3-cbca5b89695e
    langcode: en
    status: true
    dependencies: {  }
    _core:
      default_config_hash: GAHBiBARA1hdVQoJq1P1oyK47vGxwTr3vyiPsnwqD44
    name: Person
    vid: person
    description: 'An individual of the human species. '
    weight: 0

**Comment by mjordan** [comment]
@zvowell haven't forgotten about this, just swamped with day job and am brain dead in evenings. Will dig in over the weekend.

**Comment by mjordan** [comment]
To try to replicate this problem, I created 1000 nodes with new Person terms as subjects (933 new terms total) without a failure. My CSV file was pretty simple however, with only an id, title, and field_subject field. 

I then spun up a new Islandora 8 box and tried to ingest the same CSV and all of the new terms failed to be created.

Can you check `/admin/reports/status` to see what version of Drupal you're running? The version where the terms are failing for me is 8.8.5. The version where I can't get the terms to fail is 8.9.12.

**Comment by mjordan** [comment]
Following up on my comment ^ from last night, I just installed the current version of the Islandora Playbook, installed the Islandora Workbench Integration module, and used Workbench to ingest (without any HTTP 422 taxonomy terms) the same set of nodes with new `person:` values in `field_subject`. That Islandora is running Drupal 9.2.0-dev.

I'm really hoping the failures are specific to the earlier version of Drupal, since otherwise I can't seem to replicate the problem. The only time I have seen it was when I used Workbench against a Drupal 8.5.5.

Would you be interested in trying to ingest your example CSV (or a subset of it since the Playbook doesn't have all your fields) into my new instance to see what happens? It's on the public web; I could provide details to you in Slack.

**Comment by zvowell** [comment]
I'm running 8.8.5. I'm definitely open to ingesting a modified CSV into your new instance, and will keep an eye on slack for the details. Thanks!

**Comment by mjordan** [comment]
OK to close this?

**Comment by zvowell** [comment]
Yes! :)
