### ISSUE TITLE
No Person terms are created - Drupal 8.9.14-dev

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#244]
When I run --check, it doesn't flag any errors, and says the new Person terms in my CSV will be created. Then, when I do the import I get errors in the log like `09-Mar-21 09:44:16 - WARNING - Term 'Sorg, Marcella' not created, HTTP response code was 422.`, the term is not created, and any node that references it is also not created in Drupal. Previously this was occurring for some Person terms, but not all. 
I am able to create other terms, just not Person terms.
If I manually create the Person term and then reference it by name in the CSV, the associated node is created without any issue.
An excerpt of the WB log is attached.
I imported the same CSV at your demo VM and the Person terms were created just fine.
Looking in the Drupal watchdog log, it seems like it is expecting values in the "Person Preferred Name" field that used to be required when creating Person terms but is no longer part of the form (I think it had been in the Names module?).
Error in Drupal log:
`Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException: Unprocessable Entity: validation failed. field_person_preferred_name: This value should not be null. in Drupal\rest\Plugin\rest\resource\EntityResource->validate() (line 55 of /var/www/drupal/web/core/modules/rest/src/Plugin/rest/resource/EntityResourceValidationTrait.php).`

Our developer, Hertzel, suggested opening a ticket with you. I know you'd said you were looking into terms not being created so perhaps there is a related ticket that I didn't see - but I wanted to call out what I was seeing in the Drupal log, in case that helps.

[PersonTermIssue.log](https://github.com/mjordan/islandora_workbench/files/6130360/PersonTermIssue.log)

**Comment by mjordan** [comment]
Thanks, this is very helpful. `field_person_preferred_name` is the problem. I think shipped with that field up until https://github.com/Islandora/documentation/issues/1561, when we removed it (and the Name module, which may have required that field). Can you confirm that your Islandora has the Name module installed and enabled? If it doesn't, then it looks like the the Person vocabulary on your Drupal has a required `field_person_preferred_name` that is not part of Name.

In either case, currently Workbench can't create terms that have required fields other than the core term name field. Issue #111 will address that, but it's a major chunk of work and will require that we figure out how to express the additional fields in CSV.

If you can look into the questions about `field_person_preferred_name` above, at least we'll be closer to identifying what's going on.

**Comment by dara2** [comment]
Hi Mark--
I don't see the Name module when I look at the list of modules in the Drupal UI, but when I look in Git, it seems like maybe it is still there. 
When I look in the Person form, there is no visible "Person Preferred Name" field like there used to be. But, I see that Person Preferred Name is still available as a field, just disabled (at /admin/structure/taxonomy/manage/person/overview/form-display).
I'm circling back with our developer to confirm that the Name module is no longer there.

**Comment by mjordan** [comment]
Sounds like the module was disabled but not uninstalled. That might be (not sure) required to remove the field.

**Comment by dara2** [comment]
Hi @mjordan - I think this is all set now (this specific error I was running into).
