### ISSUE TITLE
Update task to replace multivalued fields

### ISSUE THREAD

**Issue by Ansel-Hong** [mjordan/islandora_workbench#247]
Is there a way for the "update" task to update and replace a multivalued field with the new specified content rather than adding more values into the field.

What I mean is given a taxonomy field called fruits with "Apples, Bananas" can I run an update task to change it to "Apples, Oranges" because right now the update task adds the new taxonomy terms on top of it, ending up with "Apples, Bananas, Apples, Oranges" in the field

**Comment by mjordan** [comment]
Not at the moment. What you are asking for is related to #47, which has a depends on #72. I have been working on #72 for the last while, but it's a huge task, so I can't give you an estimated time of completion.

**Comment by Ansel-Hong** [comment]
Ok, thank you good to know there are plans to implement that feature.

**Comment by mjordan** [comment]
Fix included in work on #47.
