### ISSUE TITLE
Media referenced by URL with `?raw=true` suffix not loading.

### ISSUE THREAD

**Issue by Digital-Grinnell** [mjordan/islandora_workbench#260]
Working on ICG's test of I8 and we have a Google Sheet with media/file references like this:  
```
https://github.com/Islandora-Collaboration-Group/islandora-sample-objects/blob/master/VIDEO/Video_03/Video_03.mp4?raw=true
```

This was for an object to which I assigned a unique ID of 1100118.  The “intermediate” file left behind in my input_data folder was correspondingly named `1100118/Video_03.mp4?raw=true`.  That intermediate file was a viable .mp4 video because I was able to play it locally once I removed the `?raw=true` suffix from the filename.  Unfortunately, Workbench was subsequently unable to upload the viable "intermediate" file, presumably because the filename still had the `?raw=true` suffix.

So, I changed the entry in the Google Sheet to read `https://github.com/Islandora-Collaboration-Group/islandora-sample-objects/blob/master/VIDEO/Video_03/Video_03.mp4` thinking that would solve the problem.  It did not.  That URL returned an HTML response and I subsequently got the following in my log file:
```
28-Apr-21 15:15:19 - INFO - Node for Olivia's Arrival (record 1100118) created at https://icg-islandora.williams.edu/node/63.
28-Apr-21 15:15:21 - ERROR - Media not created, PUT request to "https://icg-islandora.williams.edu/node/63/media/video/16" returned an HTTP status code of "403".
```

**Comment by mjordan** [comment]
@Digital-Grinnell  As a generic (non-Github specific) solution, I wonder if just having Workbench strip everything including and after a `?` in the filenames of downloaded files would be sufficient? Using your example, if the remote filename is `Video_03.mp4?raw=true`, the version that Workbench saves would be `Video_03.mp4`.

**Comment by Digital-Grinnell** [comment]
Yes, that was what I was thinking too.   Asked on my experience I think it would work.

Sent from my iPad

On May 3, 2021, at 8:43 PM, Mark Jordan ***@***.***> wrote:

﻿

@Digital-Grinnell<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Digital-2DGrinnell&d=DwMCaQ&c=HUrdOLg_tCr0UMeDjWLBOM9lLDRpsndbROGxEKQRFzk&r=D8E-oGNaPT9srWV6jE8UP5unsmKEmmHEH-tzgmjBvLk&m=QWgax0m8rYS-6htgq3zGc_hpwcGu_phq1MA2SWPQb2Q&s=bCjfl8CO0Tr_9qnh9kQ6EIGt8O6YjF2W9LvRmUvmJzE&e=> As a generic (non-Github specific) solution, I wonder if just having Workbench strip everything including and after a ? in the filenames of downloaded files would be sufficient? Using your example, if the remote filename is Video_03.mp4?raw=true, the version that Workbench saves would be Video_03.mp4.

**Comment by mjordan** [comment]
@Digital-Grinnell can you test the issue-260 branch to see if it resolves the problem?

**Comment by mjordan** [comment]
@Digital-Grinnell OK, the issue-260 branch is ready to test, if you can.

**Comment by McFateM** [comment]
I pulled the `issue-260` branch and subsequently ran a brief test last evening, an ingest of video content that featured three different `file` references in the following forms:

  - https://github.com/Islandora-Collaboration-Group/islandora-sample-objects/raw/master/VIDEO/Video_01/Video_01.mp4
  - https://github.com/Islandora-Collaboration-Group/islandora-sample-objects/blob/master/VIDEO/Video_02/Video_02.mp4?raw=true
  - Video_03.mp4

All three ingested successfully this time!   The output from my test run follows.  

```
╭─markmcfate@MAC02NX13MG5RP ~/GitHub/islandora_workbench ‹ruby-2.3.0› ‹issue-260*›
╰─$ ./workbench --config icg_testing-video.yml
OK, connection to Drupal at https://icg-islandora.williams.edu verified.
Warning: Media creation in your version of Drupal (8.9.14) is less reliable than in Drupal 9.2 or higher.
Node for "A Brief History of Acceleration" (record 20116) created at https://icg-islandora.williams.edu/node/69.
+ Media for https://github.com/Islandora-Collaboration-Group/islandora-sample-objects/raw/master/VIDEO/Video_01/Video_01.mp4 created.
Node for "Blues for C.M." (record 20117) created at https://icg-islandora.williams.edu/node/70.
+ Media for https://github.com/Islandora-Collaboration-Group/islandora-sample-objects/blob/master/VIDEO/Video_02/Video_02.mp4?raw=true created.
Node for "Olivia's Arrival" (record 20118) created at https://icg-islandora.williams.edu/node/71.
+ Media for Video_03.mp4 created.
```

If I have time this afternoon I'll run a similar test using PDFs.  Looking good.

**Comment by mjordan** [comment]
Can you run `curl -v -uadmin:islandora "https://icg-islandora.williams.edu/islandora_workbench_integration/core_version"` replacing the credentials with the same ones used in your config file and let me know what comes back? Should be something like `{"core_version":"9.3.0-dev"}`.

The 404 is being generated by the Islandora media REST endpoint, but that endpoint has to exist, otherwise you'd see media not being created in general. Not sure what's going on yet.

**Comment by Digital-Grinnell** [comment]
Here are the results...

╭─markmcfate@MAC02NX13MG5RP ~/GitHub/islandora_workbench ‹ruby-2.3.0› ‹issue-260*›
╰─$ curl -v -uadmin:xxxxxxxxxxxxx "https://icg-islandora.williams.edu/islandora_workbench_integration/core_version"
*   Trying 104.236.219.173...
* TCP_NODELAY set
* Connected to icg-islandora.williams.edu (104.236.219.173) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=Massachusetts; L=Williamstown; O=Williams College; CN=icg-islandora.williams.edu
*  start date: Apr 26 00:00:00 2021 GMT
*  expire date: Apr 26 23:59:59 2022 GMT
*  subjectAltName: host "icg-islandora.williams.edu" matched cert's "icg-islandora.williams.edu"
*  issuer: C=US; ST=MI; L=Ann Arbor; O=Internet2; OU=InCommon; CN=InCommon RSA Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Server auth using Basic with user 'admin'
* Using Stream ID: 1 (easy handle 0x7fbe4b008800)
> GET /islandora_workbench_integration/core_version HTTP/2
> Host: icg-islandora.williams.edu
> Authorization: Basic YWRtaW46QnV0dGVyU2FnZUdub2NjaGk=
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200
< cache-control: must-revalidate, no-cache, private
< content-language: en
< content-type: application/json
< date: Tue, 11 May 2021 15:11:26 GMT
< expires: Sun, 19 Nov 1978 05:00:00 GMT
< server: nginx
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-generator: Drupal 8 (https://www.drupal.org)
< x-powered-by: PHP/7.4.15
< x-ua-compatible: IE=edge
< content-length: 25
<
* Connection #0 to host icg-islandora.williams.edu left intact
{"core_version":"8.9.14"}* Closing connection 0
________________________________

**Comment by mjordan** [comment]
OK, thanks. Can you pull in the latest updates to Islandora Workbench from the main branch and try to ingest those PDFs again?

**Comment by seth-shaw-unlv** [comment]
@McFateM , can you confirm that you have a "Document" media type configured (`/admin/structure/media/manage/document`)?

**Comment by mjordan** [comment]
If that's the issue here, we can make Workbench confirm that the media type exists during its `--check` phase.

**Comment by mjordan** [comment]
@Digital-Grinnell OK to close this issue, since you've been able to ingest files whose URLs have a `?` query string? I've opened #269 to address verifying media types exist.

**Comment by McFateM** [comment]
Yes, by all means.  Thanks!

Mark A. McFate
Digital Library Applications Developer
Burling Library, Grinnell College
1111 6th Ave., Grinnell, IA  50112-1690
(641) 269-3674    ***@***.***

________________________________
