### ISSUE TITLE
Can't create media during import with latest version of Workbench - Drupal 8.9.14-dev

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#262]
I am unable to create media at all anymore when importing content with the most recent version of Workbench. I get the error: `04-May-21 15:08:59 - ERROR - File not created, POST request to "/file/upload/media/image/field_media_image" returned an HTTP status code of "404".`

I am using Drupal 8.9.14-dev. Workbench does identify this during its --check. When I run the --check, it says: `Warning: Media creation in your version of Drupal (8.9.14-dev) is less reliable than in Drupal 9.2 or higher.`

The error I see in the Drupal database log is:
```
Type	php
Date(s)	Tuesday, May 4, 2021 - 19:08
User	admin
Location	https://staging.francoamericandigitalarchives.org/entity/media
Referrer	
Message	Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException: Unprocessable Entity: validation failed. field_media_image.0.target_id: This value should be of the correct primitive type. in Drupal\rest\Plugin\rest\resource\EntityResource->validate() (line 55 of /var/www/drupal/web/core/modules/rest/src/Plugin/rest/resource/EntityResourceValidationTrait.php).
Severity	Error
Hostname	47.51.79.50
Operations
```	
In #https://github.com/mjordan/islandora_workbench/issues/171#issuecomment-818922480, I see:

> Workbench now polls Workbench Integration for Drupal's version number.
> If Drupal's version is less than 9.2, Workbench uses Islandora's MediaSourceController to create media (i.e., what it's been doing up until now).

But from the Drupal database error I'm seeing, it seems like it's still trying to use Drupal's core REST endpoints, even though I'm in Drupal 8.

**Comment by mjordan** [comment]
I'll try to replicate what you're seeing by hard-coding the Drupal version in my setup to to "8.9.14-dev".

**Comment by ajstanley** [comment]
I'm seeing the exact same thing using Drupal 8.  The error is coming from here
https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L1580
When we get to issue_request, the URL is 'https://islandora.traefik.me/file/upload/media/file/field_media_file' and we get a 404

**Comment by mjordan** [comment]
OK, thanks both, there's obviously something awry here that I thought my `drupal_8` flag covered.

**Comment by ajstanley** [comment]
It might not be a Drupal 8 thing - we're not even getting to the create_media part yet.
On a hunch a checked my REST settings, and that endoint wasn't activated by default.  I turned it on and I'm now getting a 406 error (which is 2 better than a 404). My headers include accept: */*, so beats me.  I'll much around some more.

**Comment by ajstanley** [comment]
I've got it.  The file upload rest endpoint needs to have a format specified.
PR coming.

**Comment by ajstanley** [comment]
We should add a note to the documentation that the` /file/upload/{entity_type_id}/{bundle}/{field_name}: POST` endpoint must be activated on the I8/9 instance

**Comment by mjordan** [comment]
That endpoint is enabled automatically by https://github.com/mjordan/islandora_workbench_integration/blob/main/config/optional/rest.resource.file.upload.yml on new installs, but if for existing installs, you need to import the configs for that module using `drush cim -y --partial --source=modules/contrib/islandora_workbench_integration/config/optional`. But given the (probably flawed) logic in determining whether the target Drupal is 8 or 9, if you're running 8 your Workbench should not be using that endpoint, it should be using Islandora's MediaSourceController endpoint to create media.

I'll reply on your PR with more detail but I'm still trying to figure out why your suggested fix resolves the problem you and @dara2  are seeing.

**Comment by ajstanley** [comment]
` set_drupal_8() `was missing a return statement

**Comment by mjordan** [comment]
That's probably the real bug we're trying to fix. Thanks for finding that @ajstanley.

That said, I want to look into lowerering the threashold to Drupal 8.5 to qualify as "drupal_8" since it appears `/fine/upload` is available in 8.6.

**Comment by ajstanley** [comment]
I can confirm that it works for me with 8.9

**Comment by mjordan** [comment]
Sweet. I'll give it a test in 9.2 as well, although these fixes should have no side effects there.
