### ISSUE TITLE
Add option to ignore invalid HTTP certificates

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#272]
@ajstanley brought this up in a slack convo... I'll implement this as a config option similar to the way `allow_redirects` is currently implemented. For reference, requests' docs on this option are at https://docs.python-requests.org/en/master/user/advanced/?highlight=verify#ssl-cert-verification.

**Comment by mjordan** [comment]
@ajstanley can you test the issue-272 branch? You will need to use `secure_ssl_only: false` in your config file.

**Comment by mjordan** [comment]
If this option is in effect, "Ignoring SSL certificates." is added to the "OK, connection to Drupal at xxxx verified." message.

**Comment by ajstanley** [comment]
Hah!  Exactly what I had in my branch already (even the variable name).
Works perfectly in my test environments.

**Comment by mjordan** [comment]
Thanks! Merged into main with e886edae7aec4c3f948de0890721d83a5e80587f.
