### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by edlington** [mjordan/islandora_workbench#275]
I ran `./workbench --config config.yml --check`

The resulting error was:

"Error: Row 1 in your CSV file has more columns (13) than there are headers (14)"

Is this supposed to read "Row 1 in your CSV file has fewer columns (13) than there are headers (14)" ?

**Comment by mjordan** [comment]
Yes, it is. I'll fix, thanks!

**Comment by mjordan** [comment]
@edlington `--check` already accounts for when there are fewer columns than headers. Was this CSV data the same as that in #278?

**Comment by mjordan** [comment]
But it's broken! So as I said ^, I'll fix!

**Comment by mjordan** [comment]
@edlington I'm making progress on this, but it turned out to be way more complicated than it at first appeared.

**Comment by edlington** [comment]
@mjordan If there's anything I can do to help lemme know.

**Comment by mjordan** [comment]
Thanks - will get you to test at a certain point.

**Comment by mjordan** [comment]
@edlington can you pull in the latest updates to the `main` branch and test?

**Comment by edlington** [comment]
@mjordan, Yes I will do that this afternoon and let you know how it goes.

**Comment by edlington** [comment]
@mjordan First test. Here's the data:

id,title,file,field_model,field_geographic_subject,field_alternative_title,field_physical_form,field_edtf_date_created,field_resource_type,field_edtf_date_issued,field_description,field_note, field_edtf_date_issued

0,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2",Hiller-08-19.tif.tiff,11,China,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2", 22,1949,21,1949,"A photograph of a man with gray hair\, lying on the ground on his side with hand outstretched to the woman standing in front of him. He has a small\, white bag. Wall in background. A woman in a fur coat is handing an item to the man lying on the ground.","Digitized from glass slide. Digitization specification: Creo iQsmart3. Image is 2000 dpi\, color\, TIFF. Scanned Spring 2019. Original in University of Missouri Library Special Collections.",1945

Here's the result:

OK, connection to Drupal at http://islandora.traefik.me verified.
Warning: Media creation in your version of Drupal (9.1.8) is less reliable than in Drupal 9.2 or higher.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /home/borwickja/PhpstormProjects/islandoraworkbenchmigration/importdata/metadata.csv found.
OK, all 20 rows in the CSV file have the same number of columns as there are headers (14).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, ETDF field values in the CSV file validate.
OK, term IDs/names in CSV file exist in their respective taxonomies.
Warning: Issues detected with validating taxonomy field values in the CSV file. See the log for more detail.
Warning: Issues detected with validating typed relation field values in the CSV file. See the log for more detail.
OK, files named in the CSV "file" column are all present.
Configuration and input data appear to be valid.

**Comment by edlington** [comment]
@mjordan I ran three tests with a single record, one test with the same number of colums and rows (12), another with one fewer column, and a third with one with one fewer row. Below is the data for each test and the test result:

Test 1: Equal number of rows (12) and column headers (12) - works

id,title,file,field_model,field_geographic_subject,field_alternative_title,field_physical_form,field_edtf_date_created,field_resource_type,field_edtf_date_issued,field_description,field_note
0,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2",Hiller-08-19.tif.tiff,11,China,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2", 22,1949,21,1949,"A photograph of a man with gray hair\, lying on the ground on his side with hand outstretched to the woman standing in front of him. He has a small\, white bag. Wall in background. A woman in a fur coat is handing an item to the man lying on the ground.","Digitized from glass slide. Digitization specification: Creo iQsmart3. Image is 2000 dpi\, color\, TIFF. Scanned Spring 2019. Original in University of Missouri Library Special Collections."


OK, connection to Drupal at http://islandora.traefik.me verified.
Warning: Media creation in your version of Drupal (9.1.8) is less reliable than in Drupal 9.2 or higher.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /home/borwickja/PhpstormProjects/islandoraworkbenchmigration/importdata/metadata.csv found.
OK, all 1 rows in the CSV file have the same number of columns as there are headers (12).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, ETDF field values in the CSV file validate.
OK, term IDs/names in CSV file exist in their respective taxonomies.
Error: File /home/borwickja/PhpstormProjects/islandoraworkbenchmigration/importdata/Hiller-08-19.tif.tiff identified in CSV "file" column for record with ID field value 0 not found.


Test 2: One fewer column header (11) than rows (12) - works

id,title,file,field_model,field_geographic_subject,field_alternative_title,field_physical_form,field_edtf_date_created,field_resource_type,field_edtf_date_issued,field_description
0,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2",Hiller-08-19.tif.tiff,11,China,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2", 22,1949,21,1949,"A photograph of a man with gray hair\, lying on the ground on his side with hand outstretched to the woman standing in front of him. He has a small\, white bag. Wall in background. A woman in a fur coat is handing an item to the man lying on the ground.","Digitized from glass slide. Digitization specification: Creo iQsmart3. Image is 2000 dpi\, color\, TIFF. Scanned Spring 2019. Original in University of Missouri Library Special Collections."


OK, connection to Drupal at http://islandora.traefik.me verified.
Warning: Media creation in your version of Drupal (9.1.8) is less reliable than in Drupal 9.2 or higher.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /home/borwickja/PhpstormProjects/islandoraworkbenchmigration/importdata/metadata.csv found.
Error: Row 1 in your CSV file has more columns (12) than there are headers (11).



Test 3: One fewer row (11) than column headers (12) - doesn't work(?) See error message, seems like the count on the rows is off

id,title,file,field_model,field_geographic_subject,field_alternative_title,field_physical_form,field_edtf_date_created,field_resource_type,field_edtf_date_issued,field_description,field_note
0,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2",Hiller-08-19.tif.tiff,11,China,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2", 22,1949,21,1949,"A photograph of a man with gray hair\, lying on the ground on his side with hand outstretched to the woman standing in front of him. He has a small\, white bag. Wall in background. A woman in a fur coat is handing an item to the man lying on the ground."

OK, connection to Drupal at http://islandora.traefik.me verified.
Warning: Media creation in your version of Drupal (9.1.8) is less reliable than in Drupal 9.2 or higher.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /home/borwickja/PhpstormProjects/islandoraworkbenchmigration/importdata/metadata.csv found.
OK, all 1 rows in the CSV file have the same number of columns as there are headers (12).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, ETDF field values in the CSV file validate.
OK, term IDs/names in CSV file exist in their respective taxonomies.
OK, files named in the CSV "file" column are all present.
Configuration and input data appear to be valid.

**Comment by edlington** [comment]
@mjordan One gotcha for me was duplicate column headers. When I had duplicate headers it showed up in the error output as a miscount between rows and headers, since the data was still counted but the duplicate header was not. If the error message noted the presence of a duplicate header that might have been helpful. Thing is, I have no idea how difficult it would be to add a feature like that to Islandora Workbench. It looks like the pandas library for python supports removal of duplicate headers and associated data, but that could be confusing as well. https://stackoverflow.com/questions/14984119/python-pandas-remove-duplicate-columns. And then here's some pandas library code related to detecting duplicate headers: https://www.geeksforgeeks.org/how-to-find-drop-duplicate-columns-in-a-pandas-dataframe/

**Comment by edlington** [comment]
@mjordan Sorry I ran a few tests and sent messages and realized I hadn't pulled in the update before testing. Now I will do that. Apologies.

**Comment by edlington** [comment]
@mjordan. Apologies for those false starts on testing. I pulled in the updates and then tested against a single record. Here's the tests with the data. **They all worked!**

**Test 1: Equal number of rows (12) and column headers (12) - works**

id,title,file,field_model,field_geographic_subject,field_alternative_title,field_physical_form,field_edtf_date_created,field_resource_type,field_edtf_date_issued,field_description,field_note
0,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2",Hiller-08-19.tif.tiff,11,China,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2", 22,1949,21,1949,"A photograph of a man with gray hair\, lying on the ground on his side with hand outstretched to the woman standing in front of him. He has a small\, white bag. Wall in background. A woman in a fur coat is handing an item to the man lying on the ground.","Digitized from glass slide. Digitization specification: Creo iQsmart3. Image is 2000 dpi\, color\, TIFF. Scanned Spring 2019. Original in University of Missouri Library Special Collections."


OK, connection to Drupal at https://islandora.traefik.me verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file input_data/metadata.csv found.
OK, all 1 rows in the CSV file have the same number of columns as there are headers (12).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, ETDF field values in the CSV file validate.
OK, term IDs/names in CSV file exist in their respective taxonomies.
OK, files named in the CSV "file" column are all present.


**Test 2: One fewer column header (11) than rows (12) - works**

id,title,file,field_model,field_geographic_subject,field_alternative_title,field_physical_form,field_edtf_date_created,field_resource_type,field_edtf_date_issued,field_description
0,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2",Hiller-08-19.tif.tiff,11,China,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2", 22,1949,21,1949,"A photograph of a man with gray hair\, lying on the ground on his side with hand outstretched to the woman standing in front of him. He has a small\, white bag. Wall in background. A woman in a fur coat is handing an item to the man lying on the ground.","Digitized from glass slide. Digitization specification: Creo iQsmart3. Image is 2000 dpi\, color\, TIFF. Scanned Spring 2019. Original in University of Missouri Library Special Collections."


OK, connection to Drupal at https://islandora.traefik.me verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file input_data/metadata.csv found.
Error: Row 1 (ID 0) of the CSV file has more columns (12) than there are headers (11).



**Test 3: One fewer row (11) than column headers (12) - works**

id,title,file,field_model,field_geographic_subject,field_alternative_title,field_physical_form,field_edtf_date_created,field_resource_type,field_edtf_date_issued,field_description,field_note
0,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2",Hiller-08-19.tif.tiff,11,China,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2", 22,1949,21,1949,"A photograph of a man with gray hair\, lying on the ground on his side with hand outstretched to the woman standing in front of him. He has a small\, white bag. Wall in background. A woman in a fur coat is handing an item to the man lying on the ground."

OK, connection to Drupal at https://islandora.traefik.me verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file input_data/metadata.csv found.
Error: Row 1 (ID 0) of the CSV file has fewer columns than there are headers (12).

**Comment by edlington** [comment]
@mjordan Are there additional tests that you feel like might be worthwhile?

**Comment by mjordan** [comment]
Super, no, I think that's it. Thanks for finding this and reporting it!
