### ISSUE TITLE
Counting of headers and rows appears to be wonky

### ISSUE THREAD

**Issue by edlington** [mjordan/islandora_workbench#278]
If I run `./workbench --config config.yml --check`

with the csv below (note an extra white space before field_edtf_date_issued field name):

`id,title,file,field_model,field_geographic_subject,field_alternative_title,field_physical_form,field_edtf_date_created,field_resource_type,field_edtf_date_issued,field_description,field_note, field_edtf_date_issued
0,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2",Hiller-04-04.tif.tiff,11,China,"Hiller 04-003 e: A man\, lying on the ground\, begging\, number 2", 22,1949,21,1949,"A photograph of a man with gray hair\, lying on the ground on his side with hand outstretched to the woman standing in front of him. He has a small\, white bag. Wall in background. A woman in a fur coat is handing an item to the man lying on the ground.","Digitized from glass slide. Digitization specification: Creo iQsmart3. Image is 2000 dpi\, color\, TIFF. Scanned Spring 2019. Original in University of Missouri Library Special Collections.",1945`

Workbench tells me:

"OK, all 1 rows in the CSV file have the same number of columns as there are headers (13).
Error: CSV column header " field_edtf_date_issued" does not match any Drupal or reserved field names.

If I run the same command with the same csv but remove the extra white space between the comma and field_edtf_date_issued 

Workbench tells me:

"Error: Row 1 of your CSV file does not have same number of columns (12) as there are headers (13)."

**Comment by edlington** [comment]
Along the same lines, as I was trying to figure out what was going on I built up the csv - headers and data - row by row. When I did that I was getting helpful error messages about field problems, that were not output when I ran the workbench command against the whole csv. So it seemed as if there's an error message hierarchy? The program will tell you there's a field mismatch and if there is it won't output messages about other problems... Is that correct? I thought it might be helpful to include messages about other field problems - if I'm understanding the program flow. But maybe it never gets to evaluating other issues if the count doesn't first match.

**Comment by ajstanley** [comment]
@edlington  - I can see in your sample above you have field_edtf_date_issued and field_edtf_date_issued 0.  The second isn't going to be a valid drupal field name.  Maybe that's an issue?  
I have a pull request in now to check for duplicates - I'm creating some new content types with dozen of new fields that are hard to keep rack of and I find it pretty handy.

**Comment by edlington** [comment]
Thanks @ajstanley! Good eye. I'll edit the csv then it will probably work, and I can close this. I appreciate your comment!

**Comment by edlington** [comment]
The problem was with my data, as @ajstanley noted. Closing the issue.
