### ISSUE TITLE
Validation fails with parent_id unless both field_weight and field_member_of present

### ISSUE THREAD

**Issue by ajstanley** [mjordan/islandora_workbench#279]
We don't necessarily need field weight if we are using parent_id. 
We do need field_member_of, even if every row is blank.  We can ingest without it, but objects are orphaned.

I can put in a pull request later today to handle this.  Maybe put a warning in that if parent_id is present field_weight is required when ordered children are expected?

**Comment by mjordan** [comment]
Thanks. Can you outline steps to reproduce the problem?

**Comment by ajstanley** [comment]
If we have a spreadsheet with parent_id, but no field_weight everything ingests as it is meant to, but it still fails --check.
