### ISSUE TITLE
 does not use the pattern required for typed relation fields.

### ISSUE THREAD

**Issue by Natkeeran** [mjordan/islandora_workbench#282]
For the field_linked_agent, I am using the following as the value "relators:art:person:Jordan, Mark"; however, I am getting the following error message:
```
21-May-21 02:23:03 - ERROR - Value in field "field_linked_agent" in row 1 ("relators:art:person:Jordan, Mark") does not use the pattern required for typed relation fields.
```
What is the expected pattern?

Thank you.

**Comment by mjordan** [comment]
@Natkeeran I can't replicate this. When I use the same value for `field_linked_agent`, I get the warning:

`24-May-21 11:45:09 - WARNING - CSV field "field_linked_agent" in row 1 contains a term ("Jordan, Mark") that is not in the referenced vocabulary ("person"). That term will be created.`

Can you pull in the latest updates to the `main` branch to be sure we're running the same code?

**Comment by Natkeeran** [comment]
Got the latest and works as expected.

Thanks Mark.
