### ISSUE TITLE
Unabel to ingest content_types other than islandora_object

### ISSUE THREAD

**Issue by yamensaleh** [mjordan/islandora_workbench#284]
Good Day

first of all, thank you for this great tool.
I am facing an issue when ingesting records with content type other than islandora_object, the error is:
27-May-21 19:24:51 - ERROR - Node for CSV record 103 not created, HTTP response code was 403.
if I use the content_type islandora_object it is working fine.
![config yml](https://user-images.githubusercontent.com/16070733/119863427-368dfb80-bf22-11eb-8add-7b5c78bdbe8e.png)
![Content_type_machine_name](https://user-images.githubusercontent.com/16070733/119863583-62a97c80-bf22-11eb-8950-adec1cd87b59.png)
![Log](https://user-images.githubusercontent.com/16070733/119863675-7c4ac400-bf22-11eb-83b8-cc54476fd89f.png)

yml config file is attached along with the log and the content_type machine name

Thank you and best regards

**Comment by mjordan** [comment]
Thanks for reporting this. Can you add `log_json: true` to your config file and rerun your job, and provide  your log file so I can inspect the raw JSON that is being pushed up to Drupal?

**Comment by yamensaleh** [comment]
Log attached
Thanks
[workbench.log](https://github.com/mjordan/islandora_workbench/files/6556009/workbench.log)

**Comment by mjordan** [comment]
@yamensaleh The version difference shouldn't matter. Nothing in the node JSON in your log indicates why the failures are happening. The next best place to look for clues in in the error.log of your 8.9.13 server (should be in `/var/log/apache2/error.log`). Can you take a look there to see if there are any `403` entries?

Also, are you sure the content type configuration is the same on both the successful and unsuccessful Drupals (e.g. same fields, same vocabularies, etc.)? 

Finally, did you run `--check` before ingesting the content? The check log entries are not in your log file.

**Comment by yamensaleh** [comment]
Hi, yes I checked before running, and below is the log:
28-May-21 21:38:08 - INFO - OK, connection to Drupal at http://192.168.25.29 verified.
28-May-21 21:38:11 - INFO - Starting configuration check for "create" task using config file create.yml.
28-May-21 21:38:12 - INFO - OK, configuration file has all required values (did not check for optional values).
28-May-21 21:38:12 - INFO - OK, CSV file input_files/Sample_Data.csv found.
28-May-21 21:38:12 - INFO - OK, all 21 rows in the CSV file have the same number of columns as there are headers (9).
28-May-21 21:39:35 - INFO - OK, CSV column headers match Drupal field names.
28-May-21 21:39:35 - INFO - OK, required Drupal fields are present in the CSV file.
28-May-21 21:39:43 - WARNING - Vocabulary "family" referenced in CSV field "field_subject" may not be enabled in the "Terms in vocabulary" View (please confirm it is) or may contains no terms.
28-May-21 21:50:36 - INFO - OK, term IDs/names in CSV file exist in their respective taxonomies.
28-May-21 21:50:41 - WARNING - Vocabulary "family" referenced in CSV field "field_subject" may not be enabled in the "Terms in vocabulary" View (please confirm it is) or may contains no terms.
28-May-21 21:50:45 - INFO - OK, files named in the CSV "file" column are all present.
28-May-21 21:51:07 - INFO - Configuration checked for "create" task using config file "create.yml", no problems found.

I will check the apache error log and let you know.
thanks

**Comment by yamensaleh** [comment]
I can find in find this error in drupal  and nothing in apache log
![Access log](https://user-images.githubusercontent.com/16070733/120031556-a0c99d80-c001-11eb-850e-f7d83b4b7de6.png)

Path: /node?_format=json. Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: Access denied on creating field 'status'. in Drupal\rest\Plugin\rest\resource\EntityResource->checkEditFieldAccess() (line 30 of /var/www/html/drupal/web/core/modules/rest/src/Plugin/rest/resource/EntityResourceAccessTrait.php).

**Comment by yamensaleh** [comment]
@mjordan  I've found the issue, there is a workflow configured on Islandora, where the default status is draft, now when i remove the content_type from the workflow it works fine with no issues.
Thank you for your support and for this great tool

**Comment by mjordan** [comment]
Thanks for letting me know. How did you create your workflow? Was it simply a content-type specific default or did you use a contrib module?

**Comment by yamensaleh** [comment]
I am not sure which one my colleague is using, i will check with him

Now i have an issue where  I am trying to create some paged content, the CSV along with the configuration is attached, the error I am getting is (01-Jun-21 21:58:59 - ERROR - Node for CSV record 7 not created, HTTP response code was 422.)
what I am doing wrong?
![config yml](https://user-images.githubusercontent.com/16070733/120379544-94f31980-c328-11eb-8937-fa77044b27f3.png)
![CSV](https://user-images.githubusercontent.com/16070733/120379678-c8ce3f00-c328-11eb-816f-7b969e5b8659.png)
the member of Value 7 is a Collection node exists in the system.
please advise 
regards

**Comment by mjordan** [comment]
@yamensaleh I got an email reminder of a new comment here, but don't see it. Did you delete it or did something else happen to it?

**Comment by yamensaleh** [comment]
Hello mjordan
Yes actually, i added and deleted a comment.
In regards to the workflow I am nit sure which one because it was installed configured by my colleague.
Now I am trying to import some paged contents but I have some issues.
I will double check my configurations and let u know, if didnt work i will share the files with you along with the log.
Thanks

**Comment by mjordan** [comment]
OK, thank you. Since we seemed to have resolved the workflow question, I would like to close this issue and address the paged content question in a new issue. Is that OK?
