### ISSUE TITLE
Is it possible to run add_media.yml with declared media_use_tid values in the CSV?

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#290]
Hi Mark - I'm trying to add thumbnails to some objects that don't have images as original media files (e.g., binaries, audio files, compound objects where children are not images). I tried this using the add_media task and add_media.yml file. My CSV is attached. These are existing objects on my site, and I would like to add thumbnails for list views. The term ID for Thumbnail Image on my site is `8`.
When I run --check on add_media.yml I get this error:
```
(awesome) Born-Digitals-MacBook-Air:islandora_workbench Dara$ ./workbench --config add_media.yml --check
OK, connection to Drupal at https://bd-i8-prod.born-digital.com verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file i8demo_BD/i8_sample_objects_workbench_SMALLBATCH_060921-2.csv found.
OK, all 4 rows in the CSV file have the same number of columns as there are headers (3).
Traceback (most recent call last):
  File "./workbench", line 953, in <module>
    check_input(config, args)
  File "/Users/Dara 1/islandora_workbench/workbench_utils.py", line 999, in check_input
    validate_media_use_tids_in_csv(config, validate_media_use_tid_values_csv_data)
  File "/Users/Dara 1/islandora_workbench/workbench_utils.py", line 1552, in validate_media_use_tids_in_csv
    validate_media_use_tid(config, field_value, row[csv_id_field])
KeyError: 'id'
```
Is this functionality currently available in Workbench, or would it be an enhancement?

[i8_sample_objects_workbench_SMALLBATCH_060921-2.csv](https://github.com/mjordan/islandora_workbench/files/6626142/i8_sample_objects_workbench_SMALLBATCH_060921-2.csv)

**Comment by mjordan** [comment]
Not currently. I will address this as soon as I complete #287.

**Comment by mjordan** [comment]
@dara2 I'm still working on #287 but I think it makes sense to include this feature at the same time. Can you confirm that you will want to be able to specify multiple media use tids in the CSV?

**Comment by dara2** [comment]
Hi @mjordan - That would be fabulous (but maybe less critical once we can run ingests with multiple media per object). I'm thinking in cases where we've ingested a lot of objects but might want to go back and add thumbnails to the existing nodes, we would use this. Some of our object types don't automatically generate derivatives (e.g., Audio, Video, Book Parent).

**Comment by mjordan** [comment]
@dara2 I've merged a fix for this into the main branch. Can you pull in the updates to that branch and test please?

**Comment by dara2** [comment]
Sure, will do!

**Comment by dara2** [comment]
Worked perfectly - thanks, Mark!

**Comment by mjordan** [comment]
Super, thanks for testing.
