### ISSUE TITLE
Issues with using semicolon as delimiter

### ISSUE THREAD

**Issue by fgeisser21** [mjordan/islandora_workbench#293]
Hi Mark,
I would like to use semicolon instead of comma as delimiter in my csv files. I did the following:
- Added this option in the config file: delimiter: ";" (I also tried without the double quotes, but it didn't make a difference)
- Created csv file with ; as delimiter for the headers and data (I tried with and without wrapping string values containing a comma in double quotes, but it didn't make a difference)
The check gave me the following feedback:
- OK, all 3 rows in the CSV file have the same number of columns as there are headers (1)
But there are 6 rows in the csv file and 7 more are created by the csv_field_templates.
- and consequently this Error:  For "create" tasks, your CSV file must have a column containing a unique identifier.
Using the same data with the default comma delimiter passes the check and reports the correct number of columns (13).
What could be the source of the error?
The preprocessed files generated from the different input csv files look both good, they match exactly.

**Comment by mjordan** [comment]
Haven't seen this, but I will try to replicate it here and get back to you.

**Comment by fgeisser21** [comment]
Thanks for looking into this. 
In the meantime I managed to run Workbench with the comma-separated configuration and created 3 nodes with media and files. However, I ran into a couple of strange errors - dummy thumbnails displayed at first instead of the ones created from the files, php errors in the Islandora UI log messages, relators:pht:person not created despite using the syntax described in the documentation... I wonder whether some of these problems might be due to the fact that my Islandora Playbook installation uses Drupal 8.8.5. In your (otherwise excellent) documentation, it says that Drupal 9.2 or higher should be used, and there is a section on what happens if you use Drupal 8.5 or earlier, but nothing about the versions in between.
I know that I probably should open a separate issue for these questions, but I'd rather refrain from flooding your repository with a number of marginal issues.

**Comment by mjordan** [comment]
@fgeisser21 Sorry about that, I'll clarify the (completely misleading) point about Drupal version 9.2 at the top of https://mjordan.github.io/islandora_workbench_docs/installation/. You can use Workbench with any version of Islandora. The important version milestone is 8.6: if you're running that version or higher, Workbench uses a more reliable way of creating media that in lower versions. That's the only distinction.

On your thumbnail question, Workbench doesn't create thumbnails on its own, Islandora does that. Can you try creating the same type of media using Drupal's web-based tools (i.e. by creating a media manually) to see if the thumbnails are created properly?

On the `relators:pht:person` question, are you referring to the example `"relators:art:person:Jordan, Mark"`? If you use `relators:pht:person` you need to specify a new name after `person`.

**Comment by fgeisser21** [comment]
Great, thanks! Good to know that I don't have to try to upgrade Drupal - which in the past always wrecked my installation.

I know that Islandora does the thumbnail creation. It probably just took a long time and in the meantime filled the view with some thumbnails from the cache, who knows. In the end the proper thumbnails were there. I never had observed that behaviour in a manual upload before. I wonder how the Workbench ingest will behave with larger numbers of images.

As to the relators: I tried all kinds of variations, such as
"relators:pht:person:Nefflen, Werner|relators:own:corporate_body:Stadtarchiv Baden"
"relators:pht:person:Werner Nefflen|relators:own:corporate_body:Stadtarchiv Baden"
and I also tried without the double quotes.
The owner was created in the first attempt. But the photographer always gave a warning in the workbench.log, and the node could not be created: 
WARNING - Term 'Werner Nefflen' not created, HTTP response code was 422.
ERROR - Node for CSV record 03 not created, HTTP response code was 422.
Strangely enough, all the other terms were put in double quotes in the log file, but the person name only in single quotes.
In the end I tried without person - "relators:pht:Werner Nefflen|...". This time there were no warnings, the nodes and media were created, but still no linked agent.
I have to mention that I added these terms in the csv_field_templates config, I didn't yet try to add them through the metadata.csv.

**Comment by mjordan** [comment]
> I know that Islandora does the thumbnail creation. It probably just took a long time and in the meantime filled the view with some thumbnails from the cache, who knows. In the end the proper thumbnails were there. I never had observed that behaviour in a manual upload before. I wonder how the Workbench ingest will behave with larger numbers of images.

I'm guessing that the thumbnails took a while to show up because the microservice that generates that took a while to work its way through the queue. Scalability of microservices, especially if you're using Workbench or Drupal Migrate to ingest hundreds or thousands of objects, is something we'll need to keep an eye on. I think @ajstanley has had some experience with this sort of behavior.

> I have to mention that I added these terms in the csv_field_templates config, I didn't yet try to add them through the metadata.csv.

OK, that's very useful to know. I have to admit that I don't recall testing the field templates with linked agents, I will do so.

**Comment by mjordan** [comment]
@fgeisser21 I fixed the delimiter issue. Please test, if you have time.

**Comment by fgeisser21** [comment]
I did some testing: csv with ";" as a delimiter now works as expected. Thanks for fixing the issue!

**Comment by mjordan** [comment]
Very good, thank you for confirming.
