### ISSUE TITLE
Cannot create taxonomy terms for typed relations

### ISSUE THREAD

**Issue by fgeisser21** [mjordan/islandora_workbench#296]
I am trying to create new taxonomy terms and typed relations using create and update tasks.
As mentioned in https://github.com/mjordan/islandora_workbench/issues/293, creating a linked agent with a corporate body taxonomy term works fine. It also works with a new term in the csv file using a create task. However, it doesn't work with an update task - although the documentation says it should (https://mjordan.github.io/islandora_workbench_docs/fields/#adding-new-typed-relation-targets). There is no error in the log, it says "Node ... updated", but the new taxonomy term is not created. Updating a node with an already existing linked agent doesn't work either, the linked agent field is not added. Did I miss something?

Creating a new person term doesn't work at all due to the issue described here: https://github.com/mjordan/islandora_workbench/issues/244. Is there a way to get rid of the required "Person Preferred Name" field?

**Comment by seth-shaw-unlv** [comment]
Go to /admin/structure/taxonomy/manage/person/overview/fields/taxonomy_term.person.field_person_preferred_name on your site and deselect the required field check box,  then save.

**Comment by seth-shaw-unlv** [comment]
Or, to simply delete the field, go to  /admin/structure/taxonomy/manage/person/overview/fields and select delete on the button drop down for that field.

**Comment by fgeisser21** [comment]
Unchecking the "required" checkbox didn't work - it gave me an error "Title field type field required". So I deleted the field, as well as the "Alternate Names" field. Then I tried to uninstall the elusive Drupal Name module, but without success - see attached screenshot. There seem to be dependencies with other fields, and it is probably hopeless to remove them manually.
![grafik](https://user-images.githubusercontent.com/58389767/124560364-03059180-de3d-11eb-9eb0-a0ef8cf43168.png)

It would be interesting to know how the issue https://github.com/mjordan/islandora_workbench/issues/244 was solved, but it has already been closed.

**Comment by fgeisser21** [comment]
I now created a person taxonomy term manually and tried to connect it with some repository items in an update task, like this:
field_linked_agent
relators:pht:person:40
Strangely enough, the workbench log says: CSV field "field_linked_agent" in row 1 contains a term ("40") that is not in the referenced vocabulary ("person").
When I edit the metadata through the UI and add the person manually, the name is displayed in double quotes:
![grafik](https://user-images.githubusercontent.com/58389767/124563867-bd4ac800-de40-11eb-8668-dedf7c0eaa78.png)

This is probably rather an Islandora/Drupal than a Workbench issue. But I have no idea how to solve the problem. Any help is appreciated!

**Comment by fgeisser21** [comment]
Here are the results of my latest tests:
- After the required "Preferred Name" was deleted, creating a new person taxonomy term using a create task works fine (woohoo!)
- Creating new nodes with an already existing person taxonomy term in the linked agent field works fine. It works with the term id, too, as long as I use the correct syntax (relators:pht:40 instead of relators:pht:person:40 - sorry for the confusion). 
- When updating a node, I can connect it with an existing term, but only through the person name. Term ID doesn't work, even if I use the correct syntax. The configuration passes the check ("term IDs/names used in typed relation fields in the CSV file exist in their respective taxonomies"), but the linked agent is not added.
- It looks like I cannot create a new taxonomy term as a linked agent with an update task. Configuration passes the check, log says that the new term will be created, node is updated but the new term is not created.
- Creating new subject terms with an update task works fine. So it seems that the problem is limited to typed relations.
Altogether the situation is not as bad as I first thought.

**Comment by mjordan** [comment]
@fgeisser21, I'm glad to hear you made some progress. I'll look into the following: 

> - When updating a node, I can connect it with an existing term, but only through the person name. Term ID doesn't work, even if I use the correct syntax. The configuration passes the check ("term IDs/names used in typed relation fields in the CSV file exist in their respective taxonomies"), but the linked agent is not added.
> - It looks like I cannot create a new taxonomy term as a linked agent with an update task. Configuration passes the check, log says that the new term will be created, node is updated but the new term is not created.

**Comment by mjordan** [comment]
@fgeisser21 sorry this has taken so long. I can replicate both of the above bugs and will address them this weekend.

**Comment by mjordan** [comment]
@fgeisser21 can you try again? I have fixed the two issues you describe ^.

**Comment by fgeisser21** [comment]
I made the following tests:
- Update a node with existing taxonomy term in linked_agent field: relators:art:41 - works fine.
- Update a node with a new person taxonomy term in linked_agent field: "relators:pht:person:Nefflen, Werner" - works fine, new person term is created and linked agent added to the node.
Thanks for fixing this - Islandora Workbench is a great tool!

**Comment by fgeisser21** [comment]
(I didn't get rid of the stupid emoji in above comment. Should be relators : art : 41)

**Comment by mjordan** [comment]
Thank you for finding these bugs and for testing!
