### ISSUE TITLE
Update task failed with no messages or errors

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#303]
I'm not sure if this relates to any already known limitations in #47 but when I tried to use the "update" task to update an object title, my files passed the `--check` validation but when I ran the script, nothing happened. (Running the "create" task works fine.)
My CSV is attached. The only thing I was trying to update was the Title (so I didn't include the `validate_title_length: false`).
The .log file included no messaging whatsoever.
The site is running 8.9.17-dev.
My .yml file looked like this:
```
task: update
host: "https://isu-i8-demo.born-digital.com/"
username: [myusername]
password: [mypassword]
input_dir: i8demo_BD
input_csv: i8_sample_objects_workbench_update.csv
```
Output in the terminal, including the `--check`, was:
```
(awesome) Born-Digitals-MacBook-Air:islandora_workbench Dara$ ./workbench --config update.yml --check
OK, connection to Drupal at https://isu-i8-demo.born-digital.com verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file i8demo_BD/i8_sample_objects_workbench_update.csv found.
OK, all 1 rows in the CSV file have the same number of columns as there are headers (17).
OK, CSV column headers match Drupal field names.
OK, ETDF field values in the CSV file validate.
OK, term IDs/names in CSV file exist in their respective taxonomies.
Warning: Issues detected with validating taxonomy field values in the CSV file. See the log for more detail.
OK, term IDs/names used in typed relation fields in the CSV file exist in their respective taxonomies.
Warning: Issues detected with validating typed relation field values in the CSV file. See the log for more detail.
Configuration and input data appear to be valid.
(awesome) Born-Digitals-MacBook-Air:islandora_workbench Dara$ ./workbench --config update.yml
OK, connection to Drupal at https://isu-i8-demo.born-digital.com verified.
(awesome) Born-Digitals-MacBook-Air:islandora_workbench Dara$
```

[i8_sample_objects_workbench_update.csv](https://github.com/mjordan/islandora_workbench/files/6850065/i8_sample_objects_workbench_update.csv)

**Comment by mjordan** [comment]
@dara2 running an update task using the following CSV works as expected for me:

```
node_id,title
1559,New title FTW
```
The only thing I can think of is that Workbench is attempting to update every field that is included in your CSV. However, if it failed at updating any of the non-title fields, I would expect it to leave some messages in your log. I never finished resolving #47 (even though what is finished has been in `main` for some time) so the lack of messages could very well be because of that.

Can you try with just title and let me know how it goes?

**Comment by dara2** [comment]
Yes, that worked - thank you!

**Comment by mjordan** [comment]
Great, thanks. I've updated https://mjordan.github.io/islandora_workbench_docs/updating_nodes/ to be clearer.
