### ISSUE TITLE
does id field header need to be prepended to list of fields in get_islandora_7_content.py?

### ISSUE THREAD

**Issue by edlington** [mjordan/islandora_workbench#320]
My understanding is that an id field with a unique id is required in the csv that is fed to Islandora Workbench for migration.

Current in get_islandora_7_content.py I see this:

`rows[0] = 'file,' + rows[0] + ',sequence'`

Wondering if it should be changed to:

`rows[0] = 'id,' + 'file,' + rows[0] + ',sequence'`

**Comment by mjordan** [comment]
@edlington I'm on vacation now and can't easily test this, but will next week. Looks good though.

**Comment by ajstanley** [comment]
Normally we'd use the PID as the unique identifier, but the identifier isn't added to the record.  I can add an optional ID column for those cases when we want to add the PID to the Islandora 2 node.

**Comment by mjordan** [comment]
@ajstanley thanks so much for improving this part of Workbench!

**Comment by mjordan** [comment]
@edlington if you have time to pull in the most recent changes and test Alan's work, that would be great. You will need to run setup.py.
