### ISSUE TITLE
Provide a config options to ignore columns

### ISSUE THREAD

**Issue by Natkeeran** [mjordan/islandora_workbench#324]
Often times one wants to just keep one metadata file for a collection.  Currently, workbench requires all column headers with the exception of some system columns to be available in drupal as fields.  It would be useful to provide option to list columns headings the workbench should ignore.  Perhaps, might be useful to provide option to ignore rows as well (in case one has human friendly metadata heading names in a separate row).  

Usability/Lower priority issue.

**Comment by mjordan** [comment]
`ignore_csv_columns` does this. Let me know if it doesn't do what you expect.

**Comment by Natkeeran** [comment]
Thanks, should have checked the doc :)

**Comment by mjordan** [comment]
@Natkeeran OK to close?

**Comment by Natkeeran** [comment]
@mjordan 
When I add this config 
```
ignore_csv_columns: "Target Collection"
```
or as
```
ignore_csv_columns: Target_Collection
```

it throws the following error:
Error: Row 1 (ID 1) of the CSV file has more columns (18) than there are headers (18).

**Comment by mjordan** [comment]
Sorry, it's not documented clearly, try `ignore_csv_columns: ["Target Collection"]`

**Comment by mjordan** [comment]
I've updated to the docs: 

> For example, `ignore_csv_columns: [Target Collection, Ready to publish]`

Wrapping the column names in quotes is not required.

**Comment by Natkeeran** [comment]
Works as expected, thank you.
