### ISSUE TITLE
Allow disabling of checking for existence of terms in Drupal in --check to speed up checking

### ISSUE THREAD

**Issue by dmer** [mjordan/islandora_workbench#331]
--check doesn't always need to be checking if terms exist (esp. if all the terms are new ones begin added) but it is still nice to get the syntax/formatting checking on the structure of the terms in the CSV.

Make is an option to tell --check that you don't want to check for terms' existence in Drupal

relates to [Improve scalability of finding terms in a vocabulary #312](https://github.com/mjordan/islandora_workbench/issues/312)
and
[--check should not log warnings about vocabularies if they are not referenced in the CSV #194](https://github.com/mjordan/islandora_workbench/issues/194)

**Comment by mjordan** [comment]
Merged into main with e1dd874. See the `validate_term_existence` option in https://mjordan.github.io/islandora_workbench_docs/configuration/ (basically, include `validate_term_existence: false` in your config file to tell Workbench to not query Drupal for the existence of terms during `--check`).
