### ISSUE TITLE
If a vocabulary term is an integer, Workbench treats it as a Term ID and then returns http 422 if that ID doesn't exist

### ISSUE THREAD

**Issue by dmer** [mjordan/islandora_workbench#337]
Working with a taxonomy for temporal subjects, when the CSV field contains strings like "19th Century" it gets added to the vocab list on ingest - same for integers that contain at least one non-numeric like "1920-1930". However when the term is simply an integer "1893" Workbench tries to treat it like a Term ID and fails because there is not a Term ID of that value.
 
See CSV below the last line has a 4-digit value in the field_temporal_subject "1893". As an experiment I added a hyphen to it "1893-" and re-ran check and it all passed.

**CSV snippet:**
`id,field_resource_type,field_model,parent_id,field_weight,field_member_of,file,media_use_tid,field_display_hints,field_identifier,title,field_alternative_title,field_place_published,field_date_text,field_edtf_date_issued,field_extent,field_height,field_width,field_depth,field_description_long,field_language,field_collection_note,field_genre,field_subjects_name,field_subject,field_subject_pictured,field_temporal_subject,field_geographic_subject,field_linked_agent
1,Collection,Compound Object,,,3141,,,,XB2000.45.178,"California Building : Panama-California Exposition, San Diego, Cal. 1915.",,San Diego,c1914.,1914~,9 x 14 cm. 1 postcard : |color illustrations ,9,14,,,English,,Postcards,,"subject:Exhibitions|subject:Exhibition buildings|subject:Architecture, Baroque|subject:Pavilions|subject:Spectators",,20th century|1910-1920,United States|California|San Diego|UnitedStates,
2,Collection,Compound Object,,,3141,,,,XB1990.1973,Les trente-six vues de la Tour Eiffel,,Paris,1888-1902.,1888/1902,"24 x 30 cm. [12] pages, [36] leaves of plates, [3] pages : |chiefly color illustrations ",24,30,,,French,,Books,,"subject:Tour Eiffel (Paris, France) in art|subject:Eiffel Tower (Paris, France) in art|subject:Artists' books|subject:Printing",subject:Specimens,,France,"relators:pbl:corporate_body:Eugène Verneau|relators:cre:person:|relators:oth:person:Alexandre, Arsène|relators:tyg:person:Auriol, George|relators:oth:person:Baron, Charles"
3,Collection,Compound Object,,,3141,,,,XB1990.1060,History of the World's Fair : being a complete and authentic description of the Columbian Exposition from its inception,,"Philadelphia, Pa.",c1893.,1893~,"27 x 21 cm. 610 pages : |illustrations, portraits ",27,21,,,English,,Books,,subject:Exhibitions|subject:Exhibition buildings|subject:Exhibition grounds|subject:Demographic surveys,,19th century|1893,United States|Illinois|Chicago,"relators:pbl:corporate_body:Syndicate Publishing Co.|relators:cre:person:|relators:oth:person:Davis, Geo. R."`

**result of running --check**

OK, configuration file has all required values (did not check for optional values).
OK, CSV file input_data/Lib-test-IssueBranch336.csv found.
OK, all 2 rows in the CSV file have the same number of columns as there are headers (29).
Output CSV already exists at Lib-test-IssueBranch336_output.csv, records will be appended to it.
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, EDTF field values in the CSV file validate.
Error: CSV field “field_temporal_subject” in row 2 contains a term ID (1893) that is not in the referenced vocabulary (“temporal”).

**Comment by mjordan** [comment]
Another option we might want to introduce would tell Workbench to treat *all* CSV term values as term names. In other words, not to check if they are term IDs (i.e. integers). This might suit users who never use term IDs and always want to use term names.

**Comment by dmer** [comment]
That makes a lot of sense to me @mjordan - in a migration situation, I'm usually going to expect to have all term values. I guess I would want to also have the "n" prefix option for situations where I have mixed term ID's and names (though that seems like a less likely scenario tbh)

**Comment by jlong2git** [comment]
I think this will work we have several items that use just the a single year  (exp:1911) for field_temporal_subject
`Error: CSV field "field_temporal_subject" in row 18 contains a term ID (1911) that is not in the referenced vocabulary ("temporal").`
I was adding quotes to them,  then removing the quotes in /admin/structure/taxonomy/manage/temporal/overview as a workaround

**Comment by mjordan** [comment]
@jlong2git thanks, I know you've been hitting this so I'm glad you think the `n` solution will work for you.

@dmer excellent point about migrations.

Let me investigate what's involved in implementing both of these changes.

**Comment by rosiel** [comment]
I ran into this just now in `field_temporal_subject`. 

The 'n' solution seems prone to fail in weird ways. Like it seems very possible to want to create a term with name 'n2' and that would get the 'n' chopped off which would be quite bizarre and unexpected.

I like the idea of an option, maybe (i know this is lots more work) something like
```
columns_with_term_names:
  - field_temporal_subject
  - field_subject
```
in the config.yml, so that it _doesn't_ assume integers are term names on those columns?

**Comment by dmer** [comment]
Returning to this - I'm in agreement w/ @rosiel the "n" solution feels a bit hacky and prone to outlier errors. I would be very happy if there was simply a config as suggested that allows one to tell WB that a column has term names (not term IDs)

**Comment by mjordan** [comment]
Thanks @dmer. I like this approach. @jefferya provides an alternative approach (basically, only use term IDs) over at https://github.com/cwrc/islandora-etl/issues/2#issuecomment-1290900860 as well. @jefferya would the approach @rosiel proposes work for your team?

**Comment by jefferya** [comment]
> Thanks @dmer. I like this approach. @jefferya provides an alternative approach (basically, only use term IDs) over at [cwrc/islandora-etl#2 (comment)](https://github.com/cwrc/islandora-etl/issues/2#issuecomment-1290900860) as well. @jefferya would the approach @rosiel proposes work for your team?

Yes, the proposal works on this end.
Our workflow for migrating content is evolving toward first ingesting all taxonomy terms first (after a cleanup and reconciliation step) and then add the node (with taxonomy ids). We're not planning on mixing IDs and names in the same Workbench ingest CSV.

**Comment by mjordan** [comment]
@rosiel sorry I want to clarify, if a user defines a column in your proposed config setting, it is telling Workbench to treat integers as term names, correct?

**Comment by mjordan** [comment]
Thanks. I think it would be useful to have `--check` log any instances of integers in those columns with the warning that they will be treated as term names. Never know when someone will mix and match.

**Comment by mjordan** [comment]
Hi everyone, I'd like to come to a resolution on this issue. Does anyone have any objections to moving ahead with having to register columns that may contain term names that are integers, using @rosiel 's method of registering those columns? If I don't hear any vociferous objection by end of the day June 26 I'll go ahead and implement it.

**Comment by dara2** [comment]
I'm fine with Rosie's proposed solution.

**Comment by dmer** [comment]
Yes, this solution sounds good. Thanks!

**Comment by rosiel** [comment]
Error for me. 

with config.yml: 
```yaml
task: create
host: http://islandora.dev
username: admin
password: password
input_csv: test337.csv
secure_ssl_only: false
allow_missing_files: true
columns_with_term_names:
  - field_temporal_subject
  - field_subject
```

and test337.csv: 
```csv
id,title,field_subject,field_temporal_subject,field_model,file
2,test 2,1010101,1790,903,
```

and those values (1010101, 1790) in their respective vocabularies, I get 
`Error: CSV field "field_subject" in row 1 contains a term ("1010101") that is not in the referenced vocabulary ("subject").`

I believe there's something fishy in this line: https://github.com/mjordan/islandora_workbench/blob/issue_337/workbench_utils.py#L8137-L8138 but I don't know where to put the fix. 

My debugger says that at that line, i had successfully found the tid (914) of the term "1010101" but then it continued with the "didn't find term, and error" logic.

**Comment by mjordan** [comment]
Thanks for catching that, I'll fix.

**Comment by mjordan** [comment]
Weird, I can't replicate this. Here's my CSV (101010 exists in the Issuance Mode vocab):

```
file,field_model,id,title,field_mode_of_issuance,field_subject_general,field_language
,902,issue_337_01,Issue 337 node 1,101010,subject:Subject 1,7827
```
Node was created, here's the entries from the log:

```
03-Jul-24 06:58:09 - INFO - workbench_utils.py - 6282 - Term 921 ("7827") added to vocabulary "language".
03-Jul-24 06:58:09 - INFO - workbench_utils.py - 6222 - Term "101010" (term ID 920) already exists in vocabulary "issuance_modes".
03-Jul-24 06:58:10 - INFO - workbench - 416 - Node for "Issue 337 node 1 (record issue_337_01)" created at https://islandora.traefik.me/node/281.
```
and a shot of the resulting node:

![image](https://github.com/mjordan/islandora_workbench/assets/403918/67a45a96-2afa-4ac4-94b1-34db15549644)

**Comment by mjordan** [comment]
Can someone else (maybe @dmer ?) test to see what happens?

**Comment by rosiel** [comment]
@mjordan do you have `allow_adding_terms: true`? I have it false. I see that in that conditional, you only test if the tid is false in the former case before erroring.

**Comment by mjordan** [comment]
Ah, sorry, I didn't notice that. Will test again and if that's it, will fix.

**Comment by mjordan** [comment]
Ok, this should be ready for retesting.

**Comment by mjordan** [comment]
OK, sorry about that, issue_337 branch is ready for testing.

**Comment by rosiel** [comment]
Tested and verified with a combination of term IDs/names that do/don't exist. It works!

**Comment by mjordan** [comment]
Excellent, thanks for testing @rosiel . I'll merge this branch now and update the docs this evening.

**Comment by mjordan** [comment]
Docs are at https://mjordan.github.io/islandora_workbench_docs/fields/#using-numbers-as-term-names.

Thanks everyone!
