### ISSUE TITLE
Node title overrides media titles

### ISSUE THREAD

**Issue by rosiel** [mjordan/islandora_workbench#343]
I am making nodes with multiple media attached.

## Method 1: Nodes first, then media

I created the nodes using `nodes_only` then made an `update` config. My data spreadsheet was very simple and had headers `['node_id', 'file']`. Multiple rows had the same node_id. When I did it like this, my media were added and the media names were the filenames.

## Method 2: Nodes and media in one

I altered my spreadsheet to have a flexible number of "additional" columns, and put my file information in a single row along with the info for the node. I was kind of proud of this python wizardry. 

I will mention that i _had to_ put the first ~node~ filename [oops - RL] in the `file` column in the csv, as if that was empty, then any values in the additional file columns were ignored. I configured it to `create`.

When I did it this way, the media names were overwritten with the node title! 

I need a way to manage and keep track of what files I have ingested. This means either keeping the filename as the media title, or providing another way to put that information into a field in the media. 

Here's the bit that overwrites the media name.
https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L2031-L2032

**Comment by rosiel** [comment]
Thanks Mark!

> I think that the "Original Name" field, whose storage is provided in the Islandora module, would be great

I was actually thinking this makes more sense to do in Drupal code! Islandora would be a more useful module if it provided "write the original file to a field" functionality the way that drupal images write the height and width automatically. so no worries about doing it in wb.

**Comment by mjordan** [comment]
That makes sense. Islandora Workbench Integration module doesn't currently provide any hook/context/action functionality but it could. I want to be careful to not let that module grow too large/complex, but the idea of having it include optional submodules that do the sort of thing you are describing has come up before. Alternatively, the module that implements this code could be entirely separate from the Integration module if that functionality could be used in other situations.

**Comment by rosiel** [comment]
Yes - I meant that we should put the code for original filename into the Islandora module! :)

**Comment by rosiel** [comment]
You already have an option, `'use_node_title_for_media'` from 9 months ago. however, it's only called in the case where the file is a remote file(?).
https://github.com/mjordan/islandora_workbench/blob/1b39f45e2307f5cb69a873393769cccbc0182c81/workbench_utils.py#L4181-L4189

So I have a PR up now where I just use this existing variable. However, doing this changes the default behaviour for the primary use case of Workbench.

I assumed that 'use node title for media' is an accurate expression of what I was talking about, but looking closer, I see that the variable had only been used to determine the remote file's filename when downloaded into Drupal.

Is this the same? Should there be another config variable?

**Comment by mjordan** [comment]
That config option was the result of https://github.com/mjordan/islandora_workbench/issues/214, so tagging @ajstanley in case he's interested. 

I think changing the default value from false to true won't be a big deal. We could ask on the slack channel if anyone has a problem with doing that.

**Comment by ajstanley** [comment]
I use this flag 100% of the time when grabbing I7's downloads (all of which have the same name)  Having it set as default works for me.
In my use cases, it's useful to have several media have the same name. The connection to the original is more obvious than using the node ID as part of the owned Media's name and I can disambiguate with Media Use.

**Comment by mjordan** [comment]
@ajstanley thanks, I think that changing the default to true, and just telling everyone on the slack channel is probably OK in this case. For other, more commonly used defaults, we might want a bit more process, but the change @rosiel is proposing will likely be seen by everyone as an improvement.

**Comment by mjordan** [comment]
@rosiel I changed the GH assignment from me to you, to give you credit for doing all the work on this. Is that OK?

**Comment by mjordan** [comment]
PR merged, and docs at https://mjordan.github.io/islandora_workbench_docs/configuration/#media-settings updated to include this new option.
