### ISSUE TITLE
Nodes are not created but no error message except in .log file

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#355]
Would it be possible for Workbench to report errors where no node is created (like it does when no media is created)? I did a large ingest and several nodes were not created due to an issue with a custom field. But when I was monitoring Workbench in my terminal, I saw no error messages so I assumed everything was fine. Only when I looked at the site did I notice half the objects didn't get created. I see the errors in the .log file, but it would be helpful to see them during the ingest in terminal.
Example error from .log file that is not reported:

`19-Nov-21 13:20:42 - ERROR - Node for CSV record islandora:trc_2753 not created, HTTP response code was 422.`

(The --check was fine as well. And for background info, the issue with the custom field was that it was set to be limited to one value, but the data I was ingesting included multiple values. Although Workbench said it would ingest the first value, the error in fact caused the entire node to not be created. I can create a separate ticket for that if you think it's valuable.)

**Comment by mjordan** [comment]
Yes, it is possible to add more control over what is printed to the terminal and what is written to the log.

On the single vs. multiple valued field, the intent is in the case you describe (field configuration is for single value, but CSV data has multiple values) to just use the first value and log the event. I'll test that to confirm it's working as intended and if not, fix it. I assumed that this would be desired behavior; if it's not, let me know.

**Comment by dara2** [comment]
> On the single vs. multiple valued field, the intent is in the case you describe (field configuration is for single value, but CSV data has multiple values) to just use the first value and log the event. 

Yes, that is the desired behavior. Even more strange: I looked back at the metadata CSV and there aren't actually any multivalued cells for the field that Workbench was reporting the error for. So this is even weirder - I'm going to look into this a bit more. If I find any more info, I'll make a ticket for this.

**Comment by mjordan** [comment]
@dara2 Workbench now indicates in the console output if node was not created.
