### ISSUE TITLE
Could you add the option to use the "id" field for media filename?

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#374]
I’m running into an interesting issue with an i7 -> i2 migration. We’re pulling the files directly from i7 from filepaths (e.g., https://mysite.edu/islandora/object/islandora:103267/datastream/JP2/view). There are many objects that have the same title. At first, I had `use_node_title_for_media: true` in the YML file, but it seems Fedora doesn’t like this because you start to get multiple media files with the same filename. I got error messages in the Drupal log. So I removed that line from the YML file. Now the media are still getting a Name that matches the object title, but the media files are all being called "jp2". So I have the same problem: multiple files with the same name (though in this case "0", "1", etc. is being appended to the filename).
I wondered...how difficult would it be to add logic to the YML file telling it to use the "id" value for the filename? That would resolve my issues.

**Comment by dara2** [comment]
Hi @ajstanley - here's the ticket. I'm unable to assign it to you.

**Comment by dara2** [comment]
@ajstanley - thanks for making the update in your repo. I pulled from https://github.com/ajstanley/islandora_workbench, `issue_374` branch and did an ingest as-is, and it worked perfectly (media files got the title plus node ID as their filename). Then, as you suggested, I updated at line 2233 in workbench_utils.py to be this: 
``` 
media_name = node_csv_row['id'].replace(':', '_')
```
And now media are getting the value in my CSV's "id" column (which for this client is the PID).

**Comment by ajstanley** [comment]
I still like the idea of naming the Original File with the NID (makes it consistent with NID-Service file etc, but I'll put in a PR later today for this issue that will allow the user to specify whatever column they like in their input sheet to make the name for the Media.  This could be the id, a catalog number, or any other uniqueish value.

**Comment by dara2** [comment]
So unfortunately it seems like the media "Name" is using the PID now, but the actual _filename_ is not. So I'm running into the same duplicate filename error in Fedora. Example from the Drupal log:
```
Type	php
Date	Thursday, January 27, 2022 - 19:37
User	admin
Location	https://digitalcollections-prod.saic.edu/file/upload/media/file/field_media_file?_format=json
Referrer	
Message	Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException: Unprocessable Entity: validation failed. uri: The file fedora://2022-01/Lace_Collar.jp2 already exists. Enter a unique file URI. in Drupal\file\Plugin\rest\resource\FileUploadResource->resourceValidate() (line 55 of /var/www/drupal/web/core/modules/rest/src/Plugin/rest/resource/EntityResourceValidationTrait.php).
Severity	Error
Hostname	47.51.79.50
Operations	
```

**Comment by ajstanley** [comment]
The latest on my test branch allows four different behaviours.

1. Use filename for media (Workbench Classic ™ )
2. Use TItle from Node as media
3. Use any field from the spreadsheet as media name
4. Use the Nid of the parent node to make 23-Original File

Each of these has a file name the same as the media name
I'll get a PR ready over the next day or two - I want to write some validation code so we don't have conflicting entries in the config file

**Comment by dara2** [comment]
Thank you so much, @ajstanley - this is great. I tested option #3 and it was working as expected.

**Comment by dara2** [comment]
Yep, I tested the issue branch on Alan's repo (and am running it on a production site successfully right now), if that helps!

**Comment by dara2** [comment]
Oh, no problem! Thank you!

**Comment by mjordan** [comment]
Thanks @dara2 for opening this and thanks @ajstanley for fixing.
