### ISSUE TITLE
Datastreams are unpredictable

### ISSUE THREAD

**Issue by ajstanley** [mjordan/islandora_workbench#389]
The Original File is usually OBJ, unless its from the PDF solution pack, then it's PDF.
I had been checking for both and stopping with the first hit, but this can cause some unexpected problems.  Some Image based content models store PDFs and (even worse) some PDFs have OBJs that appear to be mostly gibberish.

We should default to OBJ on everything except islandora:sp_pdf, but allow overrides.

**Comment by mjordan** [comment]
Resolved with https://github.com/mjordan/islandora_workbench/pull/390.
