### ISSUE TITLE
Adding ability to specify node_id in create task

### ISSUE THREAD

**Issue by dnwk** [mjordan/islandora_workbench#397]
Is it possible to specify node_id during create task?

**Comment by mjordan** [comment]
Node IDs are generated by Drupal (basically auto-increment database IDs). Can you describe what you are tying to achieve? I've seen you question about adding URL aliases over at #69.

**Comment by dnwk** [comment]
We have a prod and staging site. We want to try to sync node_id between these 2 sites. Trying to explore if it's possible.

**Comment by mjordan** [comment]
Sorry, I don't know how you'd do that. You may want to ask in the #islandora slack channel what people's staging->production workflows are, and ask if there's a way to sync up node IDs.
