### ISSUE TITLE
Add ability to create redirects

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#398]
The [Redirect](https://www.drupal.org/project/redirect) contrib module provides a REST interface for creating and updating redirects. Could be useful during migrations, for example, to provide a redirect from the old node URL to the new one.

**Comment by dnwk** [comment]
one more note, the url_alias currently created, even though it is overwritten by pathauto pattern, the URL does work as a redirect. When you visit the url_alias it will be redirected to the url created by pathauto.

**Comment by mjordan** [comment]
After enabling the redirect REST resources:

`curl -v -uadmin:password "https://islandora.traefik.me/admin/config/search/redirect/edit/1?_format=json"` yields:

```
{
  "rid": [
    {
      "value": 1
    }
  ],
  "uuid": [
    {
      "value": "44fc9811-a063-4960-a2da-068c48802d70"
    }
  ],
  "hash": [
    {
      "value": "NKHV-iroG_AcWGqgRa0pNg1GhXIK-vNj5RPuf-B2dWM"
    }
  ],
  "type": [
    {
      "value": "redirect"
    }
  ],
  "uid": [
    {
      "target_id": 1,
      "target_type": "user",
      "target_uuid": "0b250d99-e207-4866-9830-780a045552a1",
      "url": "/user/1"
    }
  ],
  "redirect_source": [
    {
      "path": "node/6",
      "query": []
    }
  ],
  "redirect_redirect": [
    {
      "uri": "internal:/node/7",
      "title": "",
      "options": []
    }
  ],
  "language": [
    {
      "value": "und"
    }
  ],
  "status_code": [
    {
      "value": 301
    }
  ],
  "created": [
    {
      "value": "2024-06-19T14:10:52+00:00",
      "format": "Y-m-d\\TH:i:sP"
    }
  ]
}
```

`curl -vX POST -uadmin:password -H "Content-Type: application/json" -d @/tmp/redirect1.json "https://islandora.traefik.me/entity/redirect"` with data being:

```
{
    "type": [
      {
        "value": "redirect"
      }
    ],
    "redirect_source": [
      {
        "path": "node/8"
      }
    ],
    "redirect_redirect": [
      {
        "uri": "internal:/node/9"
      }
    ],
    "status_code": [
      {
        "value": 301
      }
    ]
  }
  ```

  creates an internal redirect. To create an external redirect, use an external URL instead of an `internal` URI:

  ```
  {
    "type": [
      {
        "value": "redirect"
      }
    ],
    "redirect_source": [
      {
        "path": "node/8"
      }
    ],
    "redirect_redirect": [
      {
        "uri": "https://www.lib.sfu.ca"
      }
    ],
    "status_code": [
      {
        "value": 301
      }
    ]
  }
  ```

**Comment by mjordan** [comment]
Docs pending.

**Comment by mjordan** [comment]
https://mjordan.github.io/islandora_workbench_docs/redirects/
