### ISSUE TITLE
A few misspelled words in README and docs

### ISSUE THREAD

**Issue by ysuarez** [mjordan/islandora_workbench#399]
I noticed a misspelled word in the readme, so I proceeded to run the open source CLI aspell spell checker. 

I followed this workflow that I documented for the ISLE7 project here:
 https://islandora-collaboration-group.github.io/ISLE/contributor-docs/spell-checker/

I tried to be conscious of British/Canadian versus American spelling of words. When I do spell checks I strive to stick to whatever the authors preference is for these types of spelling variations, though I may still make mistakes.

I will soon submit 2 PRs for the code repo README and for the official docs repo.

NOTE: I am unable to add the documentation tag/label at this time.

**Comment by mjordan** [comment]
Sorry @ysuarez I merged your PR and didn't close this issue. Thanks again!
