### ISSUE TITLE
Update tasks show KeyError

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#401]
When updating text fields in `update` tasks, this happens:

```
OK, connection to Drupal at http://localhost:8000 verified.
Traceback (most recent call last):
  File "./workbench", line 1132, in <module>
    update()
  File "./workbench", line 704, in update
    if int(entry['target_id']) not in added:
KeyError: 'target_id'
```

**Comment by mjordan** [comment]
Resolved with 77202be3fda7eab2fef7231a87b504dba1b9a76a.

**Comment by mjordan** [comment]
Not resolved.

**Comment by dara2** [comment]
Hi @mjordan - We were wondering if there is anything we could do to help move this along, or if there is any temporary workaround we could use? We're stalled on a migration (unless we start making updates manually, but there are a lot of nodes). Thank you!

**Comment by mjordan** [comment]
@dara2 I will try my hardest to get this working by Monday morning. Can you confirm that the only field type you need to update is typed relation? I am asking so I can focus efforts on that one field type. With Drupal's REST interface, each field type (with some exceptions) has its own JSON structure that Workbench will need to work with.

**Comment by dangercat** [comment]
Hi @mjordan @dara2 is out today but I'm her colleague (the one with the stalled migration)! The only fields I'm trying to update at this time are typed relations, yes. Thanks so much!

**Comment by mjordan** [comment]
Commit fc6134134637435d822b8c8b2ba1883eb7eba7a0 resolves this so you will be able to update your typed relation fields. 

However, it's a quick fix that *appends* taxonomy and typed relation values in "update" tasks the existing values. This is inconsistent with Workbench's current behaviour for other fields, which is to replace existing values with values in the CSV. As long as the target fields you are updating are empty, or have values that are not also in your update CSV, you'll be fine.

**Comment by dangercat** [comment]
Okay, thanks @mjordan. So, if I'm understanding correctly, if I'm trying to replace incorrect/bad typed relation values (which I am) I'm going to need to empty the taxonomies first so that the fields are empty? Otherwise I'll just end up with both the bad and the good values?

**Comment by mjordan** [comment]
That's correct, but I thought (not sure why) that the fields were empty because there was a problem with the original ingest. Sorry I misunderstood that. I think I can change my quick fix so that it deletes all content from the target field before adding the CSV values. If I do that, this will work the same as other update tasks. I can't do it this evening I will take a look tomorrow morning.

**Comment by mjordan** [comment]
@dangercat please pull in the latest changes to the main branch and test. Updates to taxonomy and typed relation fields will now replace all existing values with values in your input CSV.

This is a quick fix to get you going. I am expediting #417 so all field types will use the same logic. When this work is done, you will be able to configure whether `update` tasks replace or append to existing values.

**Comment by dangercat** [comment]
Great, thank you @mjordan! I will update and test this afternoon!

**Comment by mjordan** [comment]
@dangercat how did it go?

**Comment by dangercat** [comment]
Hey @mjordan - it works! I've tested two collections and I'm going to clean out the necessary taxonomies before proceeding with more, but workbench is updating/replacing values in typed relation fields correctly! Thanks again!

**Comment by mjordan** [comment]
@dangercat OK to close this?
