### ISSUE TITLE
suppress warnning on " Unverified HTTPS request is being made to host "

### ISSUE THREAD

**Issue by dnwk** [mjordan/islandora_workbench#402]
This message is repeating on the screen when secure_ssl_only is set to false. Is there a way to suppress it? 
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host ' '. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(

**Comment by mjordan** [comment]
The solution posted at https://stackoverflow.com/questions/68445066/how-to-fix-insecurerequestwarning-unverified-https-request-is-being-made-to-hos is to not set that option to false. Does that work in your case?

**Comment by mjordan** [comment]
https://iqcode.com/code/python/python-request-remove-warning also suggests the following. Add these two lines to workbench_utils.py right below the block of `import` statements at the top:

```
from requests.packages.urllib3.exceptions import InsecureRequestWarning # Add this to the line 
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
```

Let me know if that has any effect.

**Comment by mjordan** [comment]
Commit d580feab6263cebe2ec2f0fbe97f04fb5d458c49 should take care of this.
