### ISSUE TITLE
Check didn't flag extra pipe characters in custom typed relation field

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#405]
I am in Drupal 9.3.3, running the latest Workbench from my local.
I have a site with a custom typed relation field. The CSV passed the --check process, but when I started to ingest, it failed with this error:
```
Traceback (most recent call last):
  File "./workbench", line 1130, in <module>
    create()
  File "./workbench", line 257, in create
    subvalues = split_typed_relation_string(config, row[custom_field], target_type)
  File "/home/islandora/islandora_workbench/workbench_utils.py", line 1601, in split_typed_relation_string
    if value_is_numeric(item_list[2]):
IndexError: list index out of range
```
When I looked at my CSV I saw the node that it was trying to ingest had data in the custom typed relation field like this, with an extra leading pipe character:
```
|local:dgc:person:Paschen, Elise|local:dgc:person:McManus, James
```
The --check had caught a similar issue in the Linked Agent typed relation field, but for some reason didn't catch this. When I looked in the rest of the CSV, there are several other places where this happens in this same custom field, none of which --check apparently caught. It would be helpful if --check caught this.

**Comment by mjordan** [comment]
All CSV field types should be checked for superfluous subdelimiter characters, not just typed relation fields.

**Comment by mjordan** [comment]
This could be added to `clean_csv_values()`.

**Comment by mjordan** [comment]
@dara2 sorry this took so long! Anyway, now all trailing and leading subdelimiter characters should be stripped from CSV values.
