### ISSUE TITLE
Add_media check fails due to missing file but doesn't say which file

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#406]
I am running Drupal 9.3.3 and the latest version of Workbench.
When running a --check on the add_media task, it fails with an unhelpful error message. I can tell there is a missing file, but I'm not sure which one. So all I can do (since in some cases there are hundreds of files in the CSV) is run the task itself until it hits the bad one. It would be helpful if the failure identified which file was missing.
Here is the output from --check:
```
islandora@islandora01:~/islandora_workbench$ ./workbench --config add_flax.yml --check
OK, connection to Drupal at https://digitalcollections-prod.saic.edu verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /mnt/legacy-data/flax/flax-update.csv found.
OK, all 26 rows in the CSV file have the same number of columns as there are headers (2).
Traceback (most recent call last):
  File "./workbench", line 1113, in <module>
    check_input(config, args)
  File "/home/islandora/islandora_workbench/workbench_utils.py", line 1154, in check_input
    + file_check_row[config['id_field']] + ' not found.'
KeyError: 'id'
islandora@islandora01:~/islandora_workbench$
```

**Comment by mjordan** [comment]
Can you share your config (removing credentials of course) and a couple rows from your CSV?

**Comment by dara2** [comment]
Sure - config:
```
task: add_media
host: "[mydomain]"
username: [myusername]
password: [mypassword]
input_dir: /mnt/legacy-data/flax
input_csv: flax-update.csv
```
Some rows from my CSV:
```
node_id	file
13488	20090615-FLAXSCEX-001.jp2
13962	20160621-FLAXSCEX-005.jp2
14011	20170109-FLAXMNEV-005.jp2
14065	20170316-FLAXMNEV-010.jp2
14073	20170321-FLAXSCEX-004.jp2
```

**Comment by mjordan** [comment]
OK, thanks. `if_field` applies to `create` tasks only, so I'll need to investigate as to why that error is happening. Will try to do so this evening.

**Comment by mjordan** [comment]
@dara2 can you add `delimiter: "\t"` to your config file and try again?

**Comment by dara2** [comment]
Thanks, Mark! Unfortunately, it just gives this error when I run the check:
```
islandora@islandora01:~/islandora_workbench$ ./workbench --config add_rbsketch.yml --check
OK, connection to Drupal at https://digitalcollections-prod.saic.edu verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /mnt/legacy-data/rbsketch/rbsketch-update.csv found.
OK, all 3565 rows in the CSV file have the same number of columns as there are headers (1).
Error: For "add_media" tasks, your CSV file must contain a "node_id" column.
```
My file does contain a node_id column, and when I remove the delimiter line of code and rerun the check, Workbench finds the node_id column but then of course comes back with the error about a missing file (but I still don't know which one, sadly):
```
islandora@islandora01:~/islandora_workbench$ ./workbench --config add_rbsketch.yml --check
OK, connection to Drupal at https://digitalcollections-prod.saic.edu verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /mnt/legacy-data/rbsketch/rbsketch-update.csv found.
OK, all 3565 rows in the CSV file have the same number of columns as there are headers (2).
Traceback (most recent call last):
  File "./workbench", line 1113, in <module>
    check_input(config, args)
  File "/home/islandora/islandora_workbench/workbench_utils.py", line 1154, in check_input
    + file_check_row[config['id_field']] + ' not found.'
KeyError: 'id'
```
Here is my config with the added delimiter line:
```
task: add_media
host: "[mydomain]"
username: [myusername]
password: [mypassword]
input_dir: /mnt/legacy-data/rbsketch
input_csv: rbsketch-update.csv
delimiter: "\t"
```
And here are the first few lines of my CSV (which has 3,000+ rows):
```
node_id	file
28696	RBSK001-001.jp2
28697	RBSK001-002.jp2
28698	RBSK001-003.jp2
28699	RBSK001-004.jp2
28700	RBSK001-005.jp2
```

**Comment by mjordan** [comment]
I am pretty sure that at least one of your CSV/TSV rows uses space(s) instead of tabs. I was able to replicate the error above by creating a TSV file with one row that used spaces instead. The best way to figure out which row is the culprit is to open your TSV file in an editor that allows you to show invisible characters or show whitespace. Can you try that and let me know what you find?

**Comment by dara2** [comment]
Hmm, I'm not seeing any whitespaces when I open the file in Visual Studio but perhaps I'm doing it wrong. :)
I've attached the file here in case you can see what the problem is.
When I run the add_media task it works just fine, and will just stop when it hits the bad file.
[rbsketch-update.csv](https://github.com/mjordan/islandora_workbench/files/8427955/rbsketch-update.csv)

**Comment by dara2** [comment]
It gives me the same error I reported originally :(
```
islandora@islandora01:~/islandora_workbench$ ./workbench --config add_rbsketch.yml --check
OK, connection to Drupal at https://digitalcollections-prod.saic.edu verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /mnt/legacy-data/rbsketch/rbsketch-update.csv found.
OK, all 3565 rows in the CSV file have the same number of columns as there are headers (2).
Traceback (most recent call last):
  File "./workbench", line 1113, in <module>
    check_input(config, args)
  File "/home/islandora/islandora_workbench/workbench_utils.py", line 1154, in check_input
    + file_check_row[config['id_field']] + ' not found.'
KeyError: 'id'
```

**Comment by mjordan** [comment]
Since I can replicate the error when I use a delimiter (spaces) that are not the default (`,`) or defined in config (e.g. `delimiter: "\t"`), that's probably what's going on. But, I can't see any errant characters in your file. When you run your task, what is the last successful line in your CSV? Look at the end of your log to see what the last successful row is; it's likely the one that is next in your CSV is the one we should be focusing on.

**Comment by mjordan** [comment]
I think I've found a bug that is causing Workbench to display that error. For `add_media` tasks, the internal config value "id" needs to be `node_id`. I won't be able to fix/test until this evening, but I'll do that. You could test this theory by adding `id_field: node_id` to your config. I think that should work.

**Comment by mjordan** [comment]
There is an issue for not exiting on the first missing file (or other fatal error): https://github.com/mjordan/islandora_workbench/issues/268. When I put together the "fall 2021" roadmap for Workbench this feature came in 6th. It's a very large amount of work to change it from who it works now, but I know people want it. 

But that feature request is general, it applies to all error `--chec` finds. Doing this for just the file-existence-check might be fairly localized. I'll take a look.

**Comment by mjordan** [comment]
@dara2 I've added an option to check for the existence of all files before exiting. To use it, include `exit_on_first_missing_file_during_check: false` in your configuration.

**Comment by dara2** [comment]
Hi @mjordan - As noted in Slack, I'm still hitting this error when I run the latest Workbench (both with and without the new line, `exit_on_first_missing_file_during_check: false`, in the config).

**Comment by dara2** [comment]
I just added both `id_field: node_id` AND `exit_on_first_missing_file_during_check: false` and now I get this message, is that what is expected?
```
islandora@islandora01:~/islandora_workbench$ ./workbench --config add_saicnews.yml --check
OK, connection to Drupal at https://digitalcollections-prod.saic.edu verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /mnt/legacy-data/saicnews/saicnews-update.csv found.
OK, all 1099 rows in the CSV file have the same number of columns as there are headers (2).
Error: Missing or empty CSV "file" column values detected. See the log for more information.
```

**Comment by mjordan** [comment]
Yes. Your log will contain an entry for each missing file. Can you confirm that?

**Comment by dara2** [comment]
Yep! Just updated my comment above. Thanks, Mark!

**Comment by mjordan** [comment]
If you're doing an update you don't need to define id_field.
