### ISSUE TITLE
Error during --check when YML file has additional_files configuration

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#442]
I was able to ingest objects onto a client's server just fine, until I had a YML file that included the "additional_files" configuration, and a CSV with a "thumbnail" column. At first I thought it was because Workbench and the Python libraries were out of date, so I updated those. But I'm still getting the same error:

```
islandora@archive-prod:/opt/islandora_workbench$ ./workbench --config create_brochures6.yml --check
OK, connection to Drupal at https://archive-prod.legion.org verified.
OK, configuration file has all required values (did not check for optional values).
OK, CSV file /mnt/legacy-data/Brochures/Marketing-MC Files/20220609-marketingm-cbrochures.csv found.
OK, all 271 rows in the CSV file have the same number of columns as there are headers (22).
Traceback (most recent call last):
  File "./workbench", line 1257, in <module>
    check_input(config, args)
  File "/opt/islandora_workbench/workbench_utils.py", line 1067, in check_input
    if len(get_additional_files_config(config)) > 0:
  File "/opt/islandora_workbench/workbench_utils.py", line 1782, in get_additional_files_config
    for additional_file_field, additional_file_media_use_tid in additional_files_entry.items():
AttributeError: 'str' object has no attribute 'items'
```
Is something misconfigured in my YML file? Here is what it looks like:
```
task: create
host: "https://archive-prod.legion.org/"
username: XXX
password: XXX
input_dir: /mnt/legacy-data/Brochures/Marketing-MC Files
input_csv: 20220609-marketingm-cbrochures.csv
output_csv: 20220609-marketingm-cbrochures-output.csv
output_csv_include_input_csv: true
allow_missing_files: true
allow_adding_terms: true
use_nid_in_media_title: 1
validate_title_length: false
exit_on_first_missing_file_during_check: false
additional_files:
 -thumbnail: 39
```
CSV is attached.
My site is on Drupal 9.3.12.
[20220609-marketingm-cbrochures.csv](https://github.com/mjordan/islandora_workbench/files/9059558/20220609-marketingm-cbrochures.csv)

**Comment by mjordan** [comment]
It's the lack of a space between the `-` and `thumbnail`. I can replicate this error if I don't include the space. Which is strange, since your YAML is perfectly valid YAML. Might be a peculiarity of the Python YAML parser. I'll look into it, but if you use `- thumbnail: 39` instead of `-thumbnail:39`, it should work.

**Comment by mjordan** [comment]
I've added a note to https://mjordan.github.io/islandora_workbench_docs/adding_multiple_media/ about the need for a space.
