### ISSUE TITLE
TypeError: argument of type 'bool' is not iterable during 'create' task with Drupal 9.4.5

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#462]
We are hitting an error on the "create" task with the latest version of Workbench (updated today) and a site that is using Drupal 9.4.5. We are not getting this error with the latest Workbench on Drupal sites that are lower than 9.4.5, using the same CSV (attached).
The error is this:
```
OK, connection to Drupal at https://islandora-staging.lib.iastate.edu verified.
"Create" task started using config file create_isu_staging.yml.
Node for "AUGUST 12 TEST COLLECTION" (record 1) created at https://islandora-staging.lib.iastate.edu/node/358.
+ No files specified in CSV for row 1.
Node for "Easthampton Town Hall (Large Image)" (record 2) created at https://islandora-staging.lib.iastate.edu/node/359.
+ Media for EasthamptonTownHall.tif created.
Traceback (most recent call last):
 File "./workbench", line 1281, in <module>
 create()
 File "./workbench", line 193, in create
 node = entity_reference_field.create(config, field_definitions, node, row, custom_field)
 File "/Users/margaret/islandora_workbench/workbench_fields.py", line 774, in create
 if config['subdelimiter'] in row[field_name]:
TypeError: argument of type 'bool' is not iterable
```
Here is the config we're using:
```
task: create
host: "https://islandora-staging.lib.iastate.edu"
username: [username]
password: [password]
input_dir: mnt/ingest/Archive
input_csv: i8_sample_objects_workbench_SMALLBATCH2.csv
allow_missing_files: true
allow_adding_terms: true
exit_on_first_missing_file_during_check: false
standalone_media_url: true
```
The standalone media URL box is checked on our site.

[i8_sample_objects_workbench_SMALLBATCH2.csv](https://github.com/mjordan/islandora_workbench/files/9404046/i8_sample_objects_workbench_SMALLBATCH2.csv)

**Comment by dara2** [comment]
If you're asking if the field name on both sites (the one that works, v9.4.3 and the one that doesn't work, v9.4.5) is field_linked_agent, and that Corporate Body vocab is associated with the field, and cre and ctb are listed as allowable relators for the field, then yes. Does that help?

**Comment by mjordan** [comment]
I suspect there might be a difference in configuration in how many values "Linked Agent" are allowed - e.g. unlimited, one, or a specific number. I suspect that because the error reported is happening on line 774 in workbench_fields.py, which only applies for unlimited values in the linked agent field. I can't see why the error would fail on one Drupal and not another, using the same input CSV.

**Comment by dara2** [comment]
On both sites, the field is set to "Unlimited." It is very strange! I will keep poking at it. The prod instance of this ISU site is still on 9.3.14, and I don't believe we had the issue there (only when it went to 9.4.5) but I'm going to verify that now.

**Comment by dara2** [comment]
Hi Mark - I tested the prod instance of this ISU site and we are getting the same error there (with a lower Drupal version) so I'm going to close out this issue!
