### ISSUE TITLE
Error when running rollback "Local variable referenced before assignment"

### ISSUE THREAD

**Issue by alxp** [mjordan/islandora_workbench#484]
Text of the error:

```python
$ ./workbench --config rollback.yml 
OK, connection to Drupal at http://islandora.traefik.me verified.
"Delete" task started using config file rollback.yml.
Node http://islandora.traefik.me/node/1 deleted.
Traceback (most recent call last):
  File "/Users/aoneill/dev/islandora_workbench/./workbench", line 1309, in <module>
    delete()
  File "/Users/aoneill/dev/islandora_workbench/./workbench", line 517, in delete
    media_delete_status_code = remove_media_and_file(config, media_id)
  File "/Users/aoneill/dev/islandora_workbench/workbench_utils.py", line 2767, in remove_media_and_file
    if file_id is not None:
UnboundLocalError: local variable 'file_id' referenced before assignment
cmtctest:islandora_workbench aoneill$ 

```

Running Python version 3.10.8

**Comment by mjordan** [comment]
Thanks @alxp I noticed that while running integration tests too. I'll spend some time on the weekend resolving this.

**Comment by mjordan** [comment]
From my testing, it appears to be an authentication problem, without doubt related to #466:

```
OK, connection to Drupal at http://localhost:8000 verified.
"Delete" task started using config file rollback.yml.
DEBUG: http://localhost:8000/media/560/edit?_format=json
DEBUG: {'message': 'The used authentication method is not allowed on this route.'}
Traceback (most recent call last):
  File "./workbench", line 1309, in <module>
    delete()
  File "./workbench", line 517, in delete
    media_delete_status_code = remove_media_and_file(config, media_id)
  File "/home/mark/hacking/islandora_workbench/workbench_utils.py", line 2770, in remove_media_and_file
    if file_id is not None:
UnboundLocalError: local variable 'file_id' referenced before assignment
```
Adding `standalone_media_url: true` to my config circumvented the error and deleted the media successfully, but the strange thing is that I do not have the "Standalone Media URL" option checked at admin/config/media/media-settings and my REST config for Media looks like this (as I would expect when i don't have "Standalone Media URL" option checked):

![image](https://user-images.githubusercontent.com/403918/202221525-a710ccd8-b0d0-45f7-ad5a-51a292d159f6.png)

So until I can understand what's going on here, add `standalone_media_url: true` to your config to see if that bypasses the error.

**Comment by mjordan** [comment]
Welp, now that I've cleared my cache, my REST configuration for Media looks like I expect it to:

![image](https://user-images.githubusercontent.com/403918/202223063-a195ebc5-81cd-4e3b-a895-1da0d1b57da1.png)

And now running workbench without the  `standalone_media_url: true` setting in my config works as expected. So it was a cache problem. But it appears that with the "Standalone Media URL" setting unchecked, Drupal uses the correct Media URL (that is, with the 'edit' in the URL), but without a rebuilt cache after changing that Media config setting, responds at the correct URL but doesn't register the authentication methods indicated in the REST configuration.

I think I've documented this enough that I can replicate it and understand it better when I have more time, but in the meantime, clear you cache and try again.

**Comment by mjordan** [comment]
@alxp Workbench now errors out if it gets a 403 response from Drupal in the situation I think you are reporting. We needed that check anyway, but in the meantime I'll see if I can get a better handle on, and document, the subtle variations of the "Standalone Media URL" Drupal config setting.

**Comment by mjordan** [comment]
@alxp OK to close this issue, given that Workbench with `--check` will now warn you if it can't access the media endpoint?

**Comment by alxp** [comment]
Thanks @mjordan  I'll close this.
