### ISSUE TITLE
Documentation - I can't find Workbench in isle-dc make local

### ISSUE THREAD

**Issue by DanRoller** [mjordan/islandora_workbench#493]
I'm new to Islandora and trying to use workbench using docker from Windows WSL.

make local
Islandora starts under browser.  So looked into workbench.

https://mjordan.github.io/islandora_workbench_docs/
says do ./workbench or python[3] workbench
within the islandora_workbench .  

I have found under isle-dc a
codebase/web/modules/contrib/islandora_workbench_integration folder
which has no file called workbench.  The complimentary folder in the running
system looks similar.
Was python and not python3 a requirement for make local?

List of that docker folder has

LICENSE    composer.json  islandora_workbench_integration.info.yml     src
README.md  config         islandora_workbench_integration.routing.yml

I'm at a loss to know what to do.
What have I missed? Thanks

This may be worthless because all of the action happens on the running system 
but somewhere I saw installation instructions that included:
docker-compose exec -T drupal with-contenv bash -lc "composer require mjordan/islandora_workbench_integration"

That timed out, but bashing into running system and doing composer require mjordan/islandora_workbench_integration

says
bash-5.1# composer require mjordan/islandora_workbench_integration
Using version ^1.0 for mjordan/islandora_workbench_integration
./composer.json has been updated
Running composer update mjordan/islandora_workbench_integration
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - islandora/islandora_install_profile_demo is locked to version dev-main and an update of this package was not requested.
    - islandora/islandora_install_profile_demo dev-main requires mjordan/islandora_workbench_integration dev-main -> found mjordan/islandora_workbench_integration[dev-main] but it conflicts with your root composer.json require (^1.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by mjordan** [comment]
Hi @DanRoller at the moment I recommend [installing](https://mjordan.github.io/islandora_workbench_docs/installation/) Islandora Workbench as a standalone application on your Windows OS and not using its docker. I say this only because I don't have any experience using the docker image. That image exists (at least primarily) to auto-populate ISLE Islandora with some sample content. Workbench is designed to be completely independent of the Islandora installation, and to be run from anywhere that has HTTP access to Islandora.

I think the Drupal module is a red herring - it should install automatically without drama (or manually using composer). I've seen it be installed successfully many times. including on ISLE. I'll rebuild my ISLE later today to confirm that hasn't broken in the last few weeks.

**Comment by DanRoller** [comment]
installed, pip'ed, 

However, today docker-compose up -d, starts normally it seems but 
https://islandora.traefik.me does not so no UI.

I can bash in but workbench gets a connection error.  This is probably outside your territory.  

connection error
dan@HPLaptop2018:~/Isle-dc/islandora_workbench$ ./workbench --config create.yml --checkTraceback (most recent call last):
  File "/home/dan/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/dan/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/dan/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by DanRoller** [comment]
Duh, After site started working again, I changed the host url and all is
fine now.  Thanks
host: "https://islandora.traefik.me"

**Comment by mjordan** [comment]
Good to hear. Let me know if you have any questions (Slack is a good place to start).

Closing this ticket if that's OK.
