### ISSUE TITLE
field_resource_type required in —config create.yml example BUG

### ISSUE THREAD

**Issue by DanRoller** [mjordan/islandora_workbench#495]

**Comment by DanRoller** [comment]
In a docker, make local environment, my test of
python3 workbench —config create.yml —check

20-Dec-22 21:56:46 - INFO - OK, connection to Drupal at https://islandora.traefik.me verified.
20-Dec-22 21:56:46 - INFO - OK, Islandora Workbench Integration module installed on https://islandora.traefik.me is at version 1.0.0.
20-Dec-22 21:56:46 - INFO - Client-side request caching is enabled.
20-Dec-22 21:56:46 - INFO - Starting configuration check for "create" task using config file create.yml.
20-Dec-22 21:56:46 - INFO - OK, Islandora Workbench Integration module installed on https://islandora.traefik.me is at version 1.0.0.
20-Dec-22 21:56:47 - INFO - OK, configuration file has all required values (did not check for optional values).
20-Dec-22 21:56:47 - INFO - OK, CSV file input_data\metadata.csv found.
20-Dec-22 21:56:47 - INFO - OK, all 5 rows in the CSV file have the same number of columns as there are headers (5).
20-Dec-22 21:56:58 - INFO - OK, CSV column headers match Drupal field names.
20-Dec-22 21:56:58 - ERROR - Required Drupal field field_resource_type is not present in the CSV file.

It didn’t complain if I added the column with “image” .

**Comment by DanRoller** [comment]
Maybe not a bug but is inconsistent.

**Comment by mjordan** [comment]
Hi @DanRoller Islandora Workbench inspects the field configuration of the target content type in Drupal and will issue the error you saw if a field configured as required in Drupal is absent from your CSV. If you check the field_resource_type configuration, it should be required. If not, let me know.

I have noticed that in the Islandora Playbook, that field is not configured as required in the Islandora Object content type, but ISLE, it is.

**Comment by mjordan** [comment]
I'll add that if you don't want to add a required column to our CSV, and every record in the CSV would have the same value if you did, you can use a "[field template](https://mjordan.github.io/islandora_workbench_docs/field_templates/)" to populate that field.

**Comment by DanRoller** [comment]
I have successfully added to the config
csv_field_templates:
 - field_resource_type: 'image'
 
As for checking the field_resource_type configuration, I wandered the ui and don't know how to do that.

**Comment by DanRoller** [comment]
Required!
found on 
https://islandora.traefik.me/admin/structure/types/manage/islandora_object/fields/node.islandora_object.field_resource_type

My internet connection here is very spotty today and I'm ... learning.
