### ISSUE TITLE
UnboundLocalError in the latest version of workbench

### ISSUE THREAD

**Issue by dangercat** [mjordan/islandora_workbench#522]
Hi Mark,

I updated to the latest version of workbench and now I'm getting an error during --check: 

Traceback (most recent call last):
  File "/opt/islandora_workbench/./workbench", line 1342, in <module>
   check_input(config, args)
  File "/opt/islandora_workbench/workbench_utils.py", line 1752, in check_input
   media_type_file_field = config['media_type_file_fields'][media_type]
UnboundLocalError: local variable 'media_type' referenced before assignment

My .yml file does have stand_alone_media_url: true set and running the same CSV in a check didn't result in the same error last week/before I updated.

I searched the islandora_workbench slack and browsed the recent issues and I didn't see anything related to this type of error. I've since rolled back/reset to the last working commit on my local machine and my client's prod server and it's once again passing check.

Let me know if you need more info? 

Thanks,

Liza (Born-Digital)

P.S. 
I reset to this commit, there's one or two after this that works but there's a bunch of debugging stuff that gets spit out in the console when I run a check so I went back further: 

commit 760948265c84c819f56e13f0fb3437d672973bf4 (HEAD -> main)
Author: Mark Jordan <mjordan@sfu.ca>
Date:   Tue Jan 10 07:43:32 2023 -0800

    WIP on #126.

**Comment by mjordan** [comment]
@dangercat I apologize for the debugging output, that is very sloppy of me. Of course, it didn't show up when I tested but that's often the case.

I'll look into your first issue this evening. If you can't wait until tomorrow, check out 760948265c84c819f56e13f0fb3437d672973bf4 (from Jan. 10) and try again.
