### ISSUE TITLE
Workbench warns on check about missing values for Drupal list fields

### ISSUE THREAD

**Issue by dangercat** [mjordan/islandora_workbench#523]
Hi Mark,

After updating to the latest commit for Workbench, I started getting warnings about Drupal list fields where my CSV doesn't have a value. In this case, the rows with missing values for these list fields are parents of compounds, the children do have values. The lists don't have a blank as a possible value and in one case there's a default value set. 

Here are the warnings:

Warning: CSV field "field_digital_origin" in record with ID wessca:559 contains a value ("") that is not in the fields's allowed values.
Warning: CSV field "field_media_type" in record with ID wessca:559 contains a value ("") that is not in the fields's allowed values.
Warning: CSV field "field_digital_origin" in record with ID wessca:609 contains a value ("") that is not in the fields's allowed values.
Warning: CSV field "field_media_type" in record with ID wessca:609 contains a value ("") that is not in the fields's allowed values.
Warning: CSV field "field_digital_origin" in record with ID wessca:568 contains a value ("") that is not in the fields's allowed values.
Warning: CSV field "field_media_type" in record with ID wessca:568 contains a value ("") that is not in the fields's allowed values.

The check did continue to run, before ending in an error (see: https://github.com/mjordan/islandora_workbench/issues/522) so I'm not sure how big a deal these warnings are and if the ingest would proceed correctly in spite of them because of the error...

Attaching a snippet of the CSV (dangercat.csv).

Thanks,

Liza (Born-Digital)

[dangercat.csv](https://github.com/mjordan/islandora_workbench/files/10458709/dangercat.csv)

**Comment by mjordan** [comment]
Excellent, that was #509, which I've now resolved. OK to close this one?
