### ISSUE TITLE
Errors in workbench due to whitespace?

### ISSUE THREAD

**Issue by rosiel** [mjordan/islandora_workbench#530]
I'm not sure if this is something Workbench could/should handle gracefully, rather than requiring precision in the CSV file (also good).

I ran across "does not have an extension allowed" error that looked like this:

```
23-Jan-23 15:29:25 - ERROR - File "Documents/Sample_Excel_file.xlsx
" in CSV row 10 does not have an extension allowed in the "field_media_file" field of the (file) media type.
```

The `xlsx` extension was fine (after much gnashing of teeth), it was the newline/enter key/whitespace that snuck into the spreadsheet.

**Comment by mjordan** [comment]
Workbench does in many cases (apparently not all) clean values using [this function](https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L2149). I'll check into why this one didn't get that treatment. Thanks for reporting it.

**Comment by mjordan** [comment]
This should be applied within [get_csv_data()](https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L3181) instead of where it is now applied (varies). I'll address. Thanks again.

**Comment by mjordan** [comment]
Note to @mjordan also add tests for newlines in https://github.com/mjordan/islandora_workbench/blob/main/tests/unit_tests.py#L534.

**Comment by mjordan** [comment]
@rosiel can you pull in updates to main and try again? I've tested on my end but would appreciate a sanity check.

**Comment by mjordan** [comment]
Closing, if this is still an issue we can reopen.
