### ISSUE TITLE
--check file extension validation for "additional_files" files incorrectly checks extension in the "file" column

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#540]
Using this CSV:

```
node_id,file,transcript
840,AtoMHome2.jpg,addmedia_1.txt
841,metropolis_maria_robot.png,addmedia_2.txt
```
 `--check` is failing because it it checking to see if "txt" is a registered extension for the file in the `file` column.

**Comment by mjordan** [comment]
Related issue - #126.

**Comment by mjordan** [comment]
Resolved with e6a2b2241efe41c0236e14a7eb004df5dbbdcc6e.

**Comment by dmer** [comment]
@mjordan we added a custom media type for extracted hocr  - that media type has a file field field_media_file that was set to allow html

when running that, the hocr media was not created and this error was in the log:

`File not created for "/tmp/smith_85807/view.html", POST request to "/file/upload/media/file/field_media_file?_format=json" returned an HTTP status code of "422" and a response body of b'{"message":"Unprocessable Entity: file validation failed.\\nOnly files with the following extensions are allowed: txt rtf doc docx ppt pptx xls xlsx pdf odf odg odp ods odt fodt fods fodp fodg key numbers pages tiff tif jp2 csv xml r tab."}'.`

I recognized those were the allowed types on the file media type's instance of field_media_file so I added html to that field and now WB will create the media in the proper media type. I'm not sure if maybe I can get past this w/ the media_types_override - i did try that earlier in my testing but was not successful. So things are working fine - just thought you'd appreciate the info.

**Comment by mjordan** [comment]
Did `--check` not detect that .html wasn't registered in the file field's Drupal configuration?

**Comment by dmer** [comment]
--check did have an error - it didn't make a lot of sense to me at the time:
`Error: File "https://compass.fivecolleges.edu/islandora/object/smith:85804/datastream/HOCR/view" in the "extracted_hocr" field of row "smith:85804" has an extension (html) that is allowed in the "field_media_file" field of the "file" media type.`
