### ISSUE TITLE
Checking existence of files in "additional_files" and validating their file extensions assumes allow_missing_files is false

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#541]
Need to allow for `allow_missing_files: true` as well.

**Comment by mjordan** [comment]
@dara2 can you pull in updates from the main branch and try `--check` with your additional files?

**Comment by dara2** [comment]
This worked perfectly - thanks, Mark!

**Comment by mjordan** [comment]
Thanks for testing!
