### ISSUE TITLE
Entity reference fields that have a cardinality other than 1 or unlimited result in invalid JSON

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#553]
Thanks to @simonhm for finding this bug.

**Comment by mjordan** [comment]
Strange, the structure that is being pushed up to Drupal does in fact valid JSON:

`[{'target_id': '33', 'target_type': 'taxonomy_term'}, {'target_id': '34', 'target_type': 'taxonomy_term'}]`

Will investigate further.

**Comment by mjordan** [comment]
Branch for testing is issue-553.

**Comment by simonhm** [comment]
@mjordan 
Sorry for the late response, Mark. We've just finished an upgraded hardware for our system.
Anyway, we tried the branch and confirm it's working like a charm!
Thank you for this fix, Mark. It helps a lot. I was planning to change all the fields's limitation to "unlimited" to pass the error ^_^
Simon.

**Comment by mjordan** [comment]
Super, thanks, I'll merge that branch into main now.

**Comment by mjordan** [comment]
Resolved with d200db67ba2f9744f5791292c4b49b996c2f2488.
