### ISSUE TITLE
--check complains about invalid extensions on remote files

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#580]
@rosiel reports, and others have confirmed, that during `--check`, Workbench is producing errors like:

`Error: File "http://islandlives.ca/islandora/object/ilives:112483-f_000/datastream/OBJ/download" in CSV row ilives:112483-f_000 does not have an extension allowed in the "field_media_file" field of the (file) media type.`

for remote files. Code near https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L1877 needs to be adjusted to fetch the remote file's MIME type and check the corresponding extension against the target Drupal file field's configuration.

**Comment by mjordan** [comment]
Preliminary plan derived over lunch: make code at ://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L5580-L5592 into its own function (returning the extension), then also call it in the vicinity of https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L1870 for `file` values that start with "http".

**Comment by mjordan** [comment]
Work in the issue_580 branch also applies this fix to files named in `additional_files` columns. I'll test that separately.

**Comment by mjordan** [comment]
Closing since a fix for this has been merged into main. We can reopen if necessary.

**Comment by rosiel** [comment]
Works! thank you.

**Comment by dara2** [comment]
Hi @mjordan - as reported in Slack, I am still seeing this issue when running --check on an ingest.  
```
Error: File "https://diglib.amphilsoc.org/islandora/object/text:347832/datastream/OBJ/view" in CSV row text:347832 does not have an extension allowed in the "field_media_file" field of the (file) media type. 
```
The file is a TIFF, which is in the list of allowed extensions. These are the allowed extensions for the field_media_file field: `txt, rtf, doc, docx, ppt, pptx, xls, xlsx, pdf, odf, odg, odp, ods, odt, fodt, fods, fodp, fodg, key, numbers, pages, tiff, tif, jp2, csv, xml, r, tab`

**Comment by dara2** [comment]
Updating to note that I didn't actually have the most up-to-date Workbench (despite thinking I did!). Please disregard my previous comment.
