### ISSUE TITLE
Switch to using the ruff linter

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#585]
Seems like [ruff](https://github.com/charliermarsh/ruff) is Python devs' linter of choice these days. It is extremely fast (not that important to the Workbench project) but is very configurable via a .ruff.toml file.

Also, add ruff as a GIt pre-commit hook.

**Comment by joecorall** [comment]
How about [black](https://github.com/psf/black) for linting? I can add it as a GitHub action to force PRs to to be linted with black, and apply the linter to all existing python code.

**Comment by mjordan** [comment]
black is now the official linter. Thanks @joecorall!

Resolved with 6c50ccf6afde35b1843ea034f8dce62761b2af31.

**Comment by mjordan** [comment]
Docs will be updated this evening.
