### ISSUE TITLE
update media task that allows existing fields associated with media to be updated, specifically publish field

### ISSUE THREAD

**Issue by edlington** [mjordan/islandora_workbench#591]
Hey @mjordan wondering if at very least an update task could be included in Islandora Workbench to target the published status of media. Our use case is this: post migration there are collections that our partners determined to be not ready for prime time. I don't think they want them deleted, just hidden from public view. The collections are mostly photographs and metadata, and so there are a lot of images to unpublish. We're trying to use Views Bulk Operations to unpublish media and finding that it's non performant, to say the least, on our system (isle-dc running on a CentOs host). We haven't yet been able to track down potential causes of limitations on unpublishing. Suffice it to say a VBO unpublishing more than six or seven media items will inevitably result in a Gateway Timeout error.  Thanks for considering this!!

**Comment by mjordan** [comment]
Sorry to have missed this issue.... but good news is that @hassanelsheikha is currently working on #461.

**Comment by mjordan** [comment]
@edlington I could have suggested this a while ago, I'm sorry I let this issue drop off my radar.

If all you want to do is update the "published" field for the media, the REST request is quite simple. The harder part is getting the media ID that you will need. Do you have this list of media IDs? If so, I can provide you with a simple script for you that will let you use it as input and would unpublish those media. If you don't have those IDs, we'd need to get them, which is a bit more complicated, but do-able.

**Comment by hassanelsheikha** [comment]
Just wanted to confirm that this use case has been considered for my work on #461 (not yet merged).

**Comment by mjordan** [comment]
@edlington you can now use Workbench to change media's published status: https://mjordan.github.io/islandora_workbench_docs/updating_media/#updating-the-published-status-of-media

**Comment by mjordan** [comment]
@edlington OK to close this issue?

**Comment by edlington** [comment]
@mjordan yes thank you so much!!!
