### ISSUE TITLE
Allow for multiple parent_id's for an object

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#595]
I have several objects that belong to multiple parents. I tried ingesting them with both parent ids separated with a pipe character in the parent_id column of my sheet. The parents were both created before the children. However, the children ended up with no parent (nothing in the “Member of” Drupal field). It would be awesome if I could ingest objects with two values in the parent_id column, and both of those parent nodes would be put in the "Member of" field in Drupal. This assumes the parents will be created before the children (in the same ingest sheet).

**Comment by dara2** [comment]
I'm going to do what you've suggested in option 1. I agree that the new CSV ID to node ID feature would be useful for this. I'd be fine with just handling it that way.

**Comment by mjordan** [comment]
@dara2 I've updated the docs on using `parent_id` (https://mjordan.github.io/islandora_workbench_docs/paged_and_compound/#with-pagechild-level-metadata), mainly by adding a new bullet to the top of the list of "Some important things to note:". Can you take a look to see if it needs any changes?

**Comment by dara2** [comment]
Hi Mark! Sorry it took so long to review this. It looks great. I created a PR with some very minor typo fixes (https://github.com/mjordan/islandora_workbench_docs/pull/8).

**Comment by mjordan** [comment]
Closing, since this is now documented.
