### ISSUE TITLE
Errors when updating Workbench - "local changes to the following files would be overwritten by merge" (I didn't make any changes)

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#596]
I am trying to update Workbench (installed recently on a client's staging server and I haven't used it since it was installed). I did `git pull origin main` on the server and I get this:
```
From https://github.com/mjordan/islandora_workbench
 * branch            main       -> FETCH_HEAD
   15e6c16..eeade7f  main       -> origin/main
Updating 15e6c16..eeade7f
error: Your local changes to the following files would be overwritten by merge:
	.github/PULL_REQUEST_TEMPLATE.md
	Dockerfile
	WorkbenchConfig.py
	add_media.yml
	assets/contact_sheet/contact-sheet.css
	create.yml
	create_from_files.yml
	delete.yml
	delete_media.yml
	google_spreadsheet.yml
	i7Import/i7ImportUtilities.py
	input_data/metadata.csv
	setup.py
	tests/assets/create_paged_content_from_directories_test/books_drupal_8.yml
	tests/islandora_tests.py
	tests/islandora_tests_check.py
	tests/islandora_tests_paged_content.py
	tests/unit_tests.py
	update.yml
	workbench_fields.py
	workbench_utils.py
Please commit your changes or stash them before you merge.
Aborting
```

This isn't the first time I've run into this - I didn't make any local edits to these files. I'm not sure why it keeps wanting me to stash them. I will, so I can keep going. But I thought I'd report this to see if a) I'm doing something incorrectly or b) there is a way to prevent this.
Thanks!

**Comment by mjordan** [comment]
Strange. I suspect there was a change to the files like the wrong line endings were introduced somehow (there's a .gitattributes file to avoid this, that's just a guesss). If you know know of the files ehrer changed intentionally, try running `git reset --hard`, which should put everything back into its original state. Then you should be able to `git pull` into the main branch.

**Comment by mjordan** [comment]
@dara2 did this work?

**Comment by dara2** [comment]
I had already stashed the changes. I could try that next time before I pull updates? I am just curious because this has happened on a couple different sites lately (where no edits had been made to the files). I used to be able to just do `git pull origin main` with no issue. Should I just plan to always do `git reset --hard` before updating from now on?

**Comment by mjordan** [comment]
`git reset --hard` will remove all changes you have made, intentional or not, so I wouldn't recommend running that as a matter of course. However if all the files in the repo show changes, and you haven't modified the workbench code, it should be OK to run reset. Stashing, as you have done, is also a very good way around the problem.

OK to close this issue then?

**Comment by dara2** [comment]
Sure, but I guess my question remains, why does it suddenly keep telling me I've edited all these files? Workbench gets installed on client servers and we don't edit any of its files. Could it be the way it is getting installed?  I don't install it there myself, so I could check with the person who does, if that might be causing the issue...

**Comment by mjordan** [comment]
I don't know why. The .gitattributes file in the repo should pre-empt OS-specific line ending changes, and I know it works as intended since I routinely pull/modify/push code between Linux and Windows. Maybe if you see it happen again, do a `git diff` on one file (e.g. `git diff workbench`) to see if the changes are. Otherwise I don't know without being able to see the changes.

**Comment by dara2** [comment]
I'm wondering if instead of pulling from main, this is just getting copied from another server (where perhaps there were changes a long time ago). That would be weird...but is possible! I'll check with the person setting this up. Thanks!

**Comment by mjordan** [comment]
Yes, please check to see if that person knows anything that is relevant.
