### ISSUE TITLE
403 Errors

### ISSUE THREAD

**Issue by banetbi** [mjordan/islandora_workbench#601]
I'm seeing a lot of these in my Apache log. Looks like it gets called after all the media for an item are created. Not sure if there is something setup wrong for my API?

GET /entity/entity_form_display/node/.islandora_object.default?_format=json HTTP/1.1" 403 199 "-" "Islandora Workbench"

**Comment by banetbi** [comment]
Yes, full admin permissions.

Thanks
Justin Dalton
Ad maiorem Dei gloriam

**Comment by mjordan** [comment]
If you run  `curl -v -uyouruser:yourpassword https://yourhostnameorIP/entity/entity_form_display/node.islandora_object.default?_format=json'

What do you get?

**Comment by banetbi** [comment]
I get a full JSON response from CURL.

Thanks
Justin Dalton
Ad maiorem Dei gloriam

**Comment by mjordan** [comment]
One last thing - are you using up to date Workbench code? 

I'm going to try to figure out why your, and Will Conlin's, URLs look like `/node/.islandora_object` and not `/node.islandora_object`.

**Comment by flummingbird** [comment]
I took a look at WorkbenchConfig.py and I think that's where "/node/.islandora_object" is getting formatted on line 242.

But correcting it to /node.islandora_object by removing the '/' didn't change anything behavior wise. I got a json response back:
 "The used authentication method is not allowed on this route."
 
 Hope this helps.

**Comment by mjordan** [comment]
@flummingbird good eye - but what is strange is that you and @banetbi are the only ones reporting the problem. I'll investigate further.

**Comment by mjordan** [comment]
It's also defined, correctly here:

- https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L530
- https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L943

**Comment by mjordan** [comment]
@banetbi @flummingbird can you pull in updates to `main` and try again?

**Comment by flummingbird** [comment]
@mjordan I can confirm it works fine with the isle-dc starter site. I'm having trouble with a site on my vmware but I think that's my issue and not workbench's

**Comment by mjordan** [comment]
@flummingbird thanks for confirming (and for pointing out that inconsistency). I'm going to close this but feel free to open a new issue about your other problem or ping me on slack.
