### ISSUE TITLE
Blank geocoordinate fields in CSV result in errors

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#610]
Some users are reporting that empty geocordinate-type fields when creating taxonomies have resulted in errors. I can't produce any errors when using empty gecordinate fields in creating nodes, which use the same field-management functions as taxonomy creation does, but will turn my investigation to taxonomy terms next.

**Comment by rosiel** [comment]
That commit solved my issue. Thanks @mjordan!

**Comment by mjordan** [comment]
OK, thanks, closing.
