### ISSUE TITLE
Remote files are being assigned extensions when they already have extensions

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#615]
As reported by @rosiel in slack, remote files that have extensions like are generating errors like this one:

`Error: File "https://islandora-community-storage.s3.ca-central-1.amazonaws.com/Collection Service Files/Book_Collection.png" in CSV row "2" has an extension (png.png) that is not allowed in the "field_media_image" field of the "image" media type.`

`.png` is in fact registered with the "field_media_image" field.

**Comment by mjordan** [comment]
@rosiel can you test the issue_615 branch to see if it addresses this problem. Looks good when I test it.

**Comment by dangercat** [comment]
Hi Mark,

I ran into this with tif files today. I checked the branch out and while I don't get the error message on the --check anymore, I still run into the same problem when I actually run the create task.

Media aren't created and I get the following errors in the log: 

09-Jun-23 11:07:49 - ERROR - File not created for "/var/folders/1k/dxqzz7z54c715b3r7ktbb3jw0000gn/T/3/78019", POST request to "/file/upload/media/file/field_media_file?_format=json" returned an HTTP status code of "422" and a response body of b'{"message":"Unprocessable Entity: file validation failed.\\nOnly files with the following extensions are allowed: txt rtf doc docx ppt pptx xls xlsx pdf odf odg odp ods odt fodt fods fodp fodg key numbers pages tiff tif jp2 csv xml r tab."}'.
09-Jun-23 11:07:49 - ERROR - Media for https://folger-cdi-images.s3.amazonaws.com/000001-001000/000002.tif not created (HTTP respone code False).

Thanks,

Liza

**Comment by mjordan** [comment]
@dangercat can you share the URLs of the remote files that are not working so I can troubleshoot?

**Comment by dangercat** [comment]
Hi Mark,

After some help troubleshooting from colleagues I tested this again, and actually your fix does work, UNLESS you're trying to use the field_for_media_title setting in your create.yml. Once I removed that setting from my .yml the files were pulled down to the server with their original and correct extension (.tif) and they validated and were ingested. No problem. But if you're using that setting you get a file with no extension and then you get file validation errors... Does that make sense?

Best,

Liza

**Comment by mjordan** [comment]
OK, thanks for adding that, I'll investigate.

**Comment by dangercat** [comment]
Yes, sorry, I literally just discovered this in the last hour...

**Comment by mjordan** [comment]
No problem, I'll fix that over in #613.

Closing this issue, resolved with a6404eabb32fe4b54374e40b5149cfcd847ec5e3.
