### ISSUE TITLE
Incompatible with core Workflows module

### ISSUE THREAD

**Issue by seth-shaw-asu** [mjordan/islandora_workbench#616]
We have the Drupal Core [Workflows module](https://www.drupal.org/docs/8/core/modules/workflows/overview) enabled which allows us to add moderation states to our objects (e.g. Draft, Reviewed, Published). This, unfortunately, appears to locks the `status` property from being set during REST operations, as noted in [the linked Drupal issue comment](https://www.drupal.org/project/drupal/issues/3077044#comment-13237570).

Workbench [automatically adds `status` to node](https://github.com/mjordan/islandora_workbench/blob/main/workbench#L81-L83) which causes the create task to fail. For example:
```
05-Jun-23 23:48:43 - ERROR - Node for CSV record az716.pdf not created, HTTP response code was 403, response body was b'{"message":"Access denied on creating field \\u0027status\\u0027."}'
05-Jun-23 23:48:43 - ERROR - JSON request body used in previous POST to "/node?_format=json" was {'type': [{'target_id': 'asu_repository_item', 'target_type': 'node_type'}], 'title': [{'value': 'Evaluation of the ADOT Small Area Transportation Studies and Planning Assistance for Rural Areas Programs'}], 'status': [{'value': 1}]}.
```

Removing those three lines allows the create task to complete successfully.

As noted by @rosiel on Slack,
> I’m making use of the ability to create unpublished nodes, and in general I think that’s a really useful ability. Ideally we’d have a Workflow set up between workbench ingest and publish. But I think this is a good feature workbench has (though it stinks if the API isn’t supposed to let us do it)

That said, the content type configuration _already_ allows you to set a new item as published or not by default, and there is nothing preventing a user from setting the status property value either in a column or using [field templates](https://mjordan.github.io/islandora_workbench_docs/field_templates/). So, I suggest we simply remove the default status property.

**Comment by mjordan** [comment]
This error is for media ("Media not created...") not nodes. I don't know how/whether Workflows applies to media creation (if it does, this PR probably didn't account for that). Can you try adding `nodes_only: true` and trying again with that same CSV row to see if that narrows down the problem.

**Comment by dmer** [comment]
oh right - good catch thanks. When I run it with nodes_only:true I am getting nodes created. I'll go poke at the media permissions to see if I can figure anything else out there, but I do need to create media with these nodes.

**Comment by mjordan** [comment]
Do you have any media-specific Workflow configurations (if such a think exists)?

**Comment by dmer** [comment]
No the only workflow is a simple content moderation on nodes - they come in as default "draft" and can be changed to "approved" which makes them visible.
I notice when I run this set without nodes_only:true, it refuses to create the node after getting the 403 back from Drupal about the media. I guess that is normal behavior.

**Comment by mjordan** [comment]
Nodes are created [first](https://github.com/mjordan/islandora_workbench/blob/main/workbench#L267), [then](https://github.com/mjordan/islandora_workbench/blob/main/workbench#L328) their media. I'll need to investigate further to explain why that's happening. I'll try to set up the same workflow you have.

**Comment by dmer** [comment]
Thanks Mark! I'm happy to test more configurations or whatever - just let me know.

**Comment by dmer** [comment]
@mjordan a theory that we've been discussing is that the media objects are also subject to the content moderation and are set to a draft state as default state for media creation. Wondering if it's a similar situation to the nodes where somewhere a contradictory state is being set by default? I did look through the defaults in WorkbenchConfig.py and nothing obvious jumped out.
We can see that state in the db in a table: content_moderation_state_field_data_table but no obvious way to set that for media (maybe via API?). We'll keep digging, but I thought I'd share what we'd come up w/ so far.

**Comment by mjordan** [comment]
Yup, media are always published: https://github.com/mjordan/islandora_workbench/blob/main/workbench_utils.py#L3205

We should be able to apply @seth-shaw-asu's approach to media as well.

**Comment by mjordan** [comment]
@dmer as you can see I've opened https://github.com/mjordan/islandora_workbench/issues/664 for this. Re-closing this issue.
