### ISSUE TITLE
ERROR: 'node_nid' is not defined

### ISSUE THREAD

**Issue by noahwsmith** [mjordan/islandora_workbench#640]
See error:
<img width="891" alt="main_error" src="https://github.com/mjordan/islandora_workbench/assets/39922/790710ef-b8cd-4d2d-afc8-21a29e796e4d">

I'm really not sure how this hasn't been hit before, because `blame` seems to indicate that this code has been here a while, but my VSCode linter verifies that these two variable usages are not previously defined:

https://github.com/mjordan/islandora_workbench/blob/411cd2d6398ce081683f47805fac0a8d6fc56748/workbench#L353

https://github.com/mjordan/islandora_workbench/blob/411cd2d6398ce081683f47805fac0a8d6fc56748/workbench#L370

The rest of that function seems to be using `node_id` instead of `node_nid`

I'll issue a PR with updated variable usage momentarily...

**Comment by mjordan** [comment]
Closed with e00088420e19bd84c201ebf2c3149fa42c418f09.
