### ISSUE TITLE
update tasks no longer update entity reference field types (referencing nodes and taxonomy terms)

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#648]
In `update` tasks, updates to fields that are configured as "entity reference" have stopped working. This applies to `update` tasks only; *use of entity reference fields in `create` tasks continue to work as intended*. Strangely, Drupal returns a successful response (HTTP code 200) and doesn't otherwise indicate that the update didn't work. Therefore Workbench erroneously reports that the updates were successful, when they were not.

Updates to other field types, such as plain text, continue to work as expected. I will note more updates here as I continue to narrow down the problem.

I'm making fixing this a top priority since entity reference fields in the standard Islandora Object content type include Member Of and other commonly updated fields.

**Comment by mjordan** [comment]
An `update` task performed on July 10 appears to have worked as intended, but another update job on July 18 appears to not have worked as intended, both running the most current code in `main` at that time. Blame for workbench_fields.py, where any changes that caused this change in behavior, is [here](https://github.com/mjordan/islandora_workbench/blame/main/workbench_fields.py).

**Comment by dara2** [comment]
(Reposting from Slack):
Hi Mark - I’m testing issue_613 (updated with your latest updates from Friday) and nothing is being put into the “Member of” field for my nodes. So I worry that `create` tasks may also be affected by this bug.
I confirmed the parent was created, but just nothing is put into the child’s Member of field, despite the correct PID being in the "parent_id" column.
NOTE: I do have `query_csv_id_to_node_id_map_for_parents: false` in my config, per your instructions. Could that be causing an issue?

**Comment by mjordan** [comment]
At commit 2373149 (July 10), updates to reference fields work. Here's the JSON pushed up to Drupal:

`{'type': [{'target_id': 'islandora_object'}], 'field_member_of': [{'target_id': '792', 'target_type': 'node_type'}]}
`

Updates stopped working with commit (411cd2d, July 11). Here's the corresponding JSON:

`{'type': [{'target_id': 'islandora_object'}], 'field_member_of': [{'value': '792'}]}`

**Comment by mjordan** [comment]
Resolved with 18ea969e48923e7f4ba8f15350fe6be602e986bb.
