### ISSUE TITLE
Useless output when running with secure_ssl_only:false

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_workbench#649]
If you are having SSL problems, and you choose to use the option `secure_ssl_only: false`, when you then run Workbench you get line after line after line of this:

```
/Users/brandonw/Library/Python/3.11/lib/python/site-packages/urllib3-2.0.4-py3.11.egg/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'islandora.dev'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
```

In a four-line CSV I get over 100 of these warnings. `--check` still evaluates the CSV, and a live run of Workbench does produce nodes, but the repeated SSL warnings make the output impossible to read.

**Comment by mjordan** [comment]
@bondjimbond can you record your OS and its version here so we can narrow down what platforms this error is most common on?

**Comment by bondjimbond** [comment]
Mac M1, Ventura 13.4.1

**Comment by mjordan** [comment]
[Quick web search](https://duckduckgo.com/?q=%22InsecureRequestWarning%3A+Unverified+HTTPS+request+is+being+made+to+host%22+python+requests&t=ffab&ia=web) suggests that the proper way to avoid these errors is to do exactly what `secure_ssl_only: false` does. Which obviously is not working in your case.

Can you paste the following into your termial before you run Workbench to see if is prevents the warnings:

`export PYTHONWARNINGS="ignore:Unverified HTTPS request"`

**Comment by mjordan** [comment]
These warnings just started showing up for me. As [discussed in Slack](https://islandora.slack.com/archives/CM6F4C4VA/p1690911254084609), the HTTPS certificate of traefik.me domain has expired. 

Running `export PYTHONWARNINGS="ignore:Unverified HTTPS request"` prior to accessing https://islandora.traefik.me prevents them from being triggered. I'll add an entry to https://mjordan.github.io/islandora_workbench_docs/troubleshooting/.

**Comment by mjordan** [comment]
OK, troubleshooting entry added.

**Comment by mjordan** [comment]
Woops, looks like you need to use `secure_ssl_only:false` in your Workbench config *and* set that environment variable.

**Comment by mjordan** [comment]
Aaaannnnd also redownloading the certificates in ISLE: https://islandora.github.io/documentation/installation/docker-custom/#traefikme-ssl-certificate-expired-or-revoked
