### ISSUE TITLE
Support absolute paths for metadata.csv and files listed therein

### ISSUE THREAD

**Issue by seth-shaw-unlv** [mjordan/islandora_workbench#65]
The metadata editor I'm working on for Desktop supports describing files with any absolute path defined. This means we may not be able to determine [a single root `input_dir` to place our `input_csv` inside of](https://github.com/mjordan/islandora_workbench/blob/master/workbench#L20).

Two options:
1. Restrict the desktop client to only accept a single directory argument (rather than files with absolute paths) writable by the current user (so we can populate the metadata.csv).
2. Modify workbench so that `input_csv` can be absolute OR relative to `input_dir` [as well as the file paths](https://github.com/mjordan/islandora_workbench/blob/master/workbench#L210).

**Comment by mjordan** [comment]
I like option 2 since it seems the most flexible.

**Comment by seth-shaw-unlv** [comment]
In the meantime I've opted for number 1 with the editor. We can go back to [an earlier commit](https://github.com/seth-shaw-unlv/islandora_workbench_desktop/tree/25e2a92d1efaab21d7f96454a0fb612bb609cd1e) to restore the file drop-area should we implement number 2.

**Comment by mjordan** [comment]
#136 has resolved this for the input CSV file. I'll tackle absolute paths for files over the holidays.

**Comment by mjordan** [comment]
As of d01498ccdef07ebbb438d2b2fb5006c7aee836f7 `file` values can be relative to `input_dir`, absolute, or URLs. #135 resolved path to the metadata CSV.

**Comment by mjordan** [comment]
Will open another issue for integration tests.
