### ISSUE TITLE
Found 2 unresolved variable references in workbench_utils.py 

### ISSUE THREAD

**Issue by ysuarez** [mjordan/islandora_workbench#659]
I opened the islandora_workbench codebase in the Python focused Pycharm IDE, and it detected a few generic warnings. Though it detected these two variables that would trigger runtime errors if the code section is run. 

In line 5617 I think `args.config` can be just changed to `config`: 

https://github.com/mjordan/islandora_workbench/blob/fce9db7e0de9047e93cd69c4644a4eca5e12e34c/workbench_utils.py#L5615-L5618

This is where `config` is used in the enclosing function signature and not as `args.config`:
https://github.com/mjordan/islandora_workbench/blob/fce9db7e0de9047e93cd69c4644a4eca5e12e34c/workbench_utils.py#L5479-L5481

<br/>
<br/>

In line 6192 I think `r.status_code` should be replaced with `media_list_response.status_code`:

https://github.com/mjordan/islandora_workbench/blob/fce9db7e0de9047e93cd69c4644a4eca5e12e34c/workbench_utils.py#L6191-L6193

this is based on the request call before the if / else that leads to the line above:

https://github.com/mjordan/islandora_workbench/blob/fce9db7e0de9047e93cd69c4644a4eca5e12e34c/workbench_utils.py#L6141-L6143

<br/> 

I am putting in a very short PR as a potential fix for these two issues.

**Comment by mjordan** [comment]
Closed with e079e43823ae1732ea435ca1ce48b515607d5961.
