### ISSUE TITLE
Term Lookup not Working for Term Update

### ISSUE THREAD

**Issue by hassanelsheikha** [mjordan/islandora_workbench#661]
Thank you for the `update_terms` routine introduced in #622. For our use case, we include string literals for the CSV field values and rely on Workbench's taxonomy lookup to replace those literals with the term ID. However, this isn't working, and this error is encountered:
![image](https://github.com/mjordan/islandora_workbench/assets/71786895/0db0c293-3a51-47a3-a4e1-f6a312298b4c)

**Comment by aOelschlager** [comment]
You can use string literals with term_id as well but it needs to be what the current term is named. It is used as the unique identifier needed for each row. term_name in term_update is used for if you want to change the term name to a different term or fix an error with the name. I added the term_id variable so that people could still use string literals as ids and be able to change the term name.
Sorry, I should have documented that in the pr better and gave an example for clarity.

**Comment by hassanelsheikha** [comment]
Thanks for your reply. I think there may have been a misunderstanding. Here is a sample CSV for our use case:

```csv
term_id,field_occupation
1000,physician
```

The lookup for the occupation field will not work for row 2 because the value is a string literal, and the traceback will be identical to the one in my original question.

**Comment by mjordan** [comment]
I can try to resolve this over the weekend.

**Comment by mjordan** [comment]
@hassanelsheikha so I understand, is `field_occupation` a field on your taxonomy entity that itself is an entity reference field linking to a taxonomy of occupations?

**Comment by aOelschlager** [comment]
@hassanelsheikha Is this a linked agent or a hierarchical vocabulary? Can you give an example of how the term is setup? I'd like to be able to recreate it or something like that locally so I can troubleshoot it if that's ok with you?

**Comment by Natkeeran** [comment]
@aOelschlager 

When ingesting content, Islandora Workbench will look up fields pointing to taxonomy terms.  Similarly, it is possible to have fields in taxonomy themselves pointing to other taxonomies.  

For example, in the person taxonomy, one can add a reference field called field_placed_lived and point that to Geographic Location taxonomy.  

We assumed that taxonomy create/update will also do lookup similar to how look ups are done for taxonomy fields in the islandora object content type.  Currently, it errors out as Hassan pointed out above.

**Comment by mjordan** [comment]
@Natkeeran that's the intent. But `update_terms` tasks are not yet documented. Thanks for testing now though. Also, an important part that is not yet ready is the `--check` logic. I wouldn't call the `update_terms` functionality really complete until both the `--check` stuff is in place and everything is fully documented.

**Comment by mjordan** [comment]
@Natkeeran @hassanelsheikha to confirm, you have a taxonomy reference field referenced from a term entity, correct? As in my example below, I have added to the standard "Person" vocabulary a field `field_maintainter`, which references a new vocab I created called "Maintainer" (added as the first field in the term add/edit form):

![taxonomy_on_a_taxonomy](https://github.com/mjordan/islandora_workbench/assets/403918/12b41e45-780d-4591-8b49-29ec25bea017)

**Comment by Natkeeran** [comment]
@mjordan Yes, this is correct.

**Comment by hassanelsheikha** [comment]
All good. Thanks a lot @mjordan!

**Comment by mjordan** [comment]
@aOelschlager's fix merged with 97f8b8338024f6c582aae85ff0716cacfe28d9cd.
