### ISSUE TITLE
Call to basename() needs to use os.path.basename()

### ISSUE THREAD

**Issue by ysuarez** [mjordan/islandora_workbench#665]
The Pycharm linter found a call to basename() that just needs to use os.path.basename()

https://github.com/mjordan/islandora_workbench/blob/c3fe7e13e1ac16cd5a731555edaf376639b5513a/workbench_utils.py#L3180-L3183

PR incoming.

**Comment by mjordan** [comment]
Resolved with a4e67033c78108bf30d317ad080a295dedd59d48.
