### ISSUE TITLE
EDTF date validation fails on values containing unspecified digits and qualifiers

### ISSUE THREAD

**Issue by joshdentremont** [mjordan/islandora_workbench#669]
The EDTF python module says that `198X?` is invalid, but it also produces that same format when parsing dates: https://github.com/ixc/python-edtf/issues/38

Drupal allows this type of date in an EDTF field, but there was discussion in Slack about whether it is valid EDTF.

I have reached out to LOC for clarification and will reply here when I hear back.

**Comment by joshdentremont** [comment]
Response from LoC:

Yes, that’s perfectly fine for EDTF.
 
So you can have one or more X’s to indicate the level of imprecision, and then a ? to indicate you’re not even sure of that date expression as a whole. 198X? would mean “sometime in the 80’s, I think”. 
I could easily see that formulation applying for older time frames.

**Comment by mjordan** [comment]
Thanks @joshdentremont. workbench_utils.py has a `validate_edtf_date(date)` function that wraps the EDTF library's validation function. We could add validation of that pattern to that wrapper function, at least for now until the library can validate it. I'll propose that over in slack.

**Comment by mjordan** [comment]
I'm going to set up a test suite to determine exactly which patterns aren't passing validation, so our temporary fix can scoped as small as possible and not duplicate what the library does. So far we have: 

- 3 digits, one X, one ? (@joshdentremont's original example of `198X?`)

If anyone can verify other patterns, please drop them here.

**Comment by joshdentremont** [comment]
All of the following cause errors:
1XXX?
11XX?
111X?
1XXX~
11XX~
111X~
1XXX%
11XX%
111X%

These also cause errors, but I'm not sure they would ever come up in actual use, and they may not be valid EDTF
XXXX?
XXXX~
XXXX%

**Comment by seth-shaw-asu** [comment]
> These also cause errors, but I'm not sure they would ever come up in actual use, and they may not be valid EDTF
>
>   - XXXX?
>   - XXXX~
>   - XXXX%

I agree, they are unlikely to be used, but they _are_ valid. These are just _some_ of the oddities that EDTF allows.

**Comment by mjordan** [comment]
Do we have to validate that that date is not in the future?

**Comment by seth-shaw-asu** [comment]
We do _not_ have to validate that the date is current or past. Nothing in the spec indicates we can't specify future dates.

**Comment by seth-shaw-asu** [comment]
I think these "bad" values are technically acceptable: https://github.com/mjordan/islandora_workbench/blob/issue_669/tests/unit_tests.py#L358-L359

**Comment by seth-shaw-asu** [comment]
I am mistaken, it _does_ require four years.

I went back to review the spec and was reminded that EDTF is _an extension_ of ISO 8601, which means that the base rules of that spec still apply. Although EDTF only specifies a required number of year digits for significant digits notation, the _base_ rules for ISO 8601 _do_ require four digits.

So, mea cupla, those three-digit years _are_ invalid.

**Comment by joshdentremont** [comment]
Looks good. The values of YYYX? that were previously failing are no longer throwing errors.

Thanks

**Comment by mjordan** [comment]
OK, thanks, I've merged the issue_669 branch with 3b1a4481fec3694a6b112b9cfc64863fb2ec8db2 so am closing this issue.
