### ISSUE TITLE
Download remote files during check

### ISSUE THREAD

**Issue by aOelschlager** [mjordan/islandora_workbench#673]
Throwing out the idea of downloading the remote files while running --check instead of during the regular workbench tasks so that the tasks would be performed quicker. May be a moot point if it still takes the same amount of time. Open to any thoughts or suggestions about this.

**Comment by mjordan** [comment]
I think downloading remote files during `--check` would just move the amount of time to `--check`, but running the ingest would certainly be faster. Might be a useful opt-in setting though. Workbench could be made to check if the downloaded file exists (based on the various configuration settings that determine the downloaded temporary file's name) and if it does, not redownload it.
