### ISSUE TITLE
Fixed some misspellings in docs - August 2023

### ISSUE THREAD

**Issue by ysuarez** [mjordan/islandora_workbench#674]
I noticed a misspelled word in the docs, so I proceeded to run the open source CLI aspell spell checker.

I followed this workflow that I documented for the ISLE7 project here:
https://islandora-collaboration-group.github.io/ISLE/contributor-docs/spell-checker/

I tried to be conscious of British/Canadian versus American spelling of words. When I do spell checks I strive to stick to whatever the authors preference is for these types of spelling variations, though I may still make mistakes.

Incoming PR

**Comment by mjordan** [comment]
Thanks very much!
