### ISSUE TITLE
error on running the congfig file 

### ISSUE THREAD

**Issue by malone09** [mjordan/islandora_workbench#677]
Hello,
   I'm getting this error message when running the config command
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 16: invalid start byte

**Comment by mjordan** [comment]
Can you share your configuration file (with host, username, and password removed) and you input CSV input file so I can investigate?

**Comment by malone09** [comment]
task: create
host: HHHH
username: '#####'
password: '####'
input_csv: 'Islandora 2.0 compound sample.csv'
content_type: 'islandora_object'
delete_tmp_upload: true
id_field: ID
use_nid_in_media_title: True
allow_adding_terms: true
list_missing_drupal_fields: true
allow_missing_files: True
log_file_path: compoundsample.log
validate_terms_exist: false
http_cache_storage: sqlite



After the previous encountered issue when attempting to save the Excel file directly in the "input_data" location which wasn't working for me, as a result, I've opted to use the URL from Google Sheets with the "Anyone with the link can view" option. However, I'm encountering what I believe to be a permission error for some reason.

![image](https://github.com/mjordan/islandora_workbench/assets/7304432/c3f25474-adbf-4bc9-b158-bf20b663e2c0)
has zero rows

**Comment by mjordan** [comment]
Can you tell me what line number the "UnboundLocalError" is occurring on?

Also, if you can share a copy of your Excel file, I might be able to address the root problem of getting the CSV out of it.

**Comment by malone09** [comment]
I was able to locate the errors. I think it has to do with the new Islandora 2.0 mappings. I have to translate the mappings of Islandora 7 to reflect the new field columns header mappings of Islandora 2.0 .. Could you kindly share the new column head mappings with me?

**Comment by mjordan** [comment]
Hi @malone09 there are no standard column head mappings as far as I know. You probably should ask for help in the "metadata" channel in the Islandora Slack for assistance with mapping your MODS Solr data to Islandora 2 fields.

**Comment by mjordan** [comment]
You might find [this mapping useful](https://docs.google.com/spreadsheets/d/18u2qFJ014IIxlVpM3JXfDEFccwBZcoFsjbBGpvL0jJI/edit?pli=1#gid=0), since it has a MODS <-> Drupal field name mapping. It's linked from https://islandora.github.io/documentation/user-documentation/metadata/#fields.

**Comment by malone09** [comment]
Hi @mjordan . Looks like the ingest are going through now. How to add images and media in config file?

**Comment by mjordan** [comment]
For basic (single) image ingest, no need to account for them in your config file. You add a "file" column to your CSV. Documentation is at https://mjordan.github.io/islandora_workbench_docs/fields/#values-in-the-file-column.

**Comment by malone09** [comment]
And for bulk images based on my config file, what would be the added element or field to include?

**Comment by mjordan** [comment]
The documentation linked above describes that the 'file' column can contain - either a relative or absolute path to the image files on you local disk, or a full http link to the location of the file on the web.

**Comment by mjordan** [comment]
Hi @malone09 OK to close this issue?

**Comment by malone09** [comment]
Yes. 

Yahoo Mail: Seamless Account Control 
 
  On Tue, Jan 30, 2024 at 7:21 PM, Mark ***@***.***> wrote:   


Hi @malone09 OK to close this issue?
