### ISSUE TITLE
check_input complains my title field is missing

### ISSUE THREAD

**Issue by seth-shaw-unlv** [mjordan/islandora_workbench#68]
When I provide a CSV to check_input it complains that the required title field is missing, despite it being present. I know it is present because it got passed [an earlier required fields check](https://github.com/mjordan/islandora_workbench/blob/master/workbench_utils.py#L313-L316).

It appears that after the linked check it then [_removes it_](https://github.com/mjordan/islandora_workbench/blob/master/workbench_utils.py#L321-L322). Removing those two lines of code pacifies the check.

**Comment by mjordan** [comment]
@seth-shaw-unlv I have resolved this as part of my work on #66. Can you confirm?

**Comment by seth-shaw-unlv** [comment]
@mjordan, I just pulled down the most recent version, ran the config check, and got another error:
```
$ ./workbench --config config.yml --check
OK, configuration file has all required values (did not check for optional values).
OK, CSV file input_data/metadata.csv found.
OK, all 5 rows in the CSV file have the same number of columns as there are headers (5).
Error: CSV column header "title" does not appear to match any Drupal field names.
```

**Comment by mjordan** [comment]
Hm. Are you at 7bb868dba1f0f55b5d9d64e12e7bebeda482efbf (latest commit in master)?

**Comment by seth-shaw-unlv** [comment]
Looks like it:
```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Islandora_Workbench.egg-info/
	config.yml
	dist/

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by mjordan** [comment]
Is this urgent or can I look at it this evening?

**Comment by seth-shaw-unlv** [comment]
Not urgent; just checking as you requested. I have lots more local UI stuff to work on.

**Comment by mjordan** [comment]
I'm not sure what's going on. I just cloned a clean copy of workbench and ran `--check` using the default create.yml and didn't see the title warning:

```
mark@mark-ThinkPad-X1-Carbon-6th:/tmp/islandora_workbench$ ./workbench --config create.yml --check
OK, configuration file has all required values (did not check for optional values).
OK, http://localhost:8000 is accessible using the credentials provided.
OK, CSV file input_data/metadata.csv found.
OK, all 5 rows in the CSV file have the same number of columns as there are headers (5).
OK, CSV column headers match Drupal field names.
OK, required Drupal fields are present in the CSV file.
OK, files named in the CSV "file" column are all present.
Configuration and input data appear to be valid.
```

Not sure if this would do anything useful, but can you delete your `__pycache__` and try again?

**Comment by seth-shaw-unlv** [comment]
Same result this morning. Maybe I'm installing it wrong...

**Comment by seth-shaw-unlv** [comment]
Oh! It has been a long time since I worked with this; I probably haven't set up my new test boxes properly...

**Comment by seth-shaw-unlv** [comment]
Yep, I think that was it. I needed to setup the Islandora requirements. Everything seems to be working okay; although I haven't tried the Desktop yet.

**Comment by seth-shaw-unlv** [comment]
Ack, when did we start requiring an ID field for create statements? My branch of Desktop doesn't have that accounted for yet.

**Comment by mjordan** [comment]
We could probably do more preliminary checking of requirements on the Drupal side. 

ID has been there since https://github.com/mjordan/islandora_workbench/issues/52 - but I think that's the only change in the basic CSV structure in a long time.

**Comment by seth-shaw-unlv** [comment]
i must have been running on an older commit.

Anyway, I think we can close this one. I can re-open it if I run into it again.
