### ISSUE TITLE
[BUG] `get_data_from_view` gives empty values for Entity Reference fields

### ISSUE THREAD

**Issue by rosiel** [mjordan/islandora_workbench#682]
I have some data in Drupal, and when I do `get_data_from_view` all my entity reference fields - `field_genre`, `field_language`, `field_physical_form`, etc. are empty. The data is there in Drupal, it's just not getting written to the exported CSV.

**Comment by mjordan** [comment]
Thanks for reporting this @rosiel .

**Comment by mjordan** [comment]
Resolved with 83df0449ae9e0e745fa9e5c31dde2d21069a971b.
