### ISSUE TITLE
`add_media` tasks don't create any media if `allow_missing_files` is False

### ISSUE THREAD

**Issue by rosiel** [mjordan/islandora_workbench#687]
I had a set of media to add where one file, the one in the `file` column, was present for every row. A secondary file was added as an "additional file" for some but not all rows. In order to ensure that the `file` column was present and accurate I set `allow_missing_files` to False.

This caused Workbench to complete its run without doing anything. No errors or warnings were logged, just the usual "connected to Drupal" etc and "Completed". 

I think there's an indentation or `if` mismatch here, because according to the code in the screenshot, if 'additional files is in `config`, then `config['allow_missing_files']` must be 'True' in order for the `create_media()` line to run.

<img width="1008" alt="Screenshot 2023-09-06 at 9 50 04 AM" src="https://github.com/mjordan/islandora_workbench/assets/1943338/00868aaf-2565-4a88-84c5-682cd7064aad">

**Comment by rosiel** [comment]
I mean, I didn't realize that `allow_missing_files` applies both to the `file` column and also to any `additional_files`, but it does, so you're right in that `allow_missing_files` needed to be true to get the result i desired.

**Comment by rosiel** [comment]
I think there's a difference between:
* Some of my rows have empty values for `file` or for one of the `additional_files` columns
* The file that i told you to upload is not present 
but it sounds like `allow_missing_files` conflates the two. Personally, I think the former situation is normal and the latter situation is a problem that should get my attention (fail loudly).

**Comment by mjordan** [comment]
Agreed, I think it makes sense to constrain `allow_missing_files` to only apply to files that can't be found. What would be a reasonable behavior if the cell is empty, just log that it's empty (in case *that* was in fact an error/data issue) and skip doing whatever the current action is on the file? I think that's reasonable.

**Comment by rosiel** [comment]
I agree. Does the following cover it?

When `allow_missing_files` is `true`, workbench will log a "file not found" error and continue to the next row, while when `allow_missing_files` is `false` (default), workbench will error and exit if a file in the sheet is not present.

And in all cases, workbench will log "blanks" in the file/additional file columns.

**Comment by mjordan** [comment]
Integration test cases needed:

- input: `file` column not empty, indicated file not found
  - `allow_missing_files` is False / expected result: log entry indicating file not found, exit
  - `allow_missing_files` is True / expected result: log entry indicating file not found, continue

- input: `file` column is empty
  - `allow_missing_files` is False / expected result: log entry indicating it's empty, no media created, continue
  - `allow_missing_files` is True / expected result: media is created

- input: `additional_files` present, indicated file is not found
  - `allow_missing_files` is False / expected result: log entry indicating file not found, exit
  - `allow_missing_files` is True / expected result: log entry indicating file not found, continue

**Comment by mjordan** [comment]
Resolve #688 in `issue687` branch as well.

**Comment by rosiel** [comment]
Reading through your expected results table, I just have a question on whether the bullet points under "input: file column is empty" should match the bullet under "input: additional_files present, file path value is empty"?

**Comment by mjordan** [comment]
That last bullet is not worded as clearly as it should be. Is this OK?

- input: `additional_files` present, column for additional file also present in CSV, but file path value is empty
  - expected result: log entry indicating file not found, continue

**Comment by mjordan** [comment]
Code and integration tests for the first two cases in the expected results table committed to the issue_687 branch. Tests only inspect `--check`'s output, not the log files; we probably should add inspecting the log files for specific entries to be thorough.

**Comment by mjordan** [comment]
List of expected behaviours above to include @rosiel's clarification.

**Comment by mjordan** [comment]
@mjordan to do: first point under "A few notes" at https://mjordan.github.io/islandora_workbench_docs/adding_multiple_media/ will need to be removed.

**Comment by mjordan** [comment]
Only outstanding tests that remain are add_media with additional files.

**Comment by mjordan** [comment]
@rosiel sorry this took so long but writing integration tests takes a long time. Well worth it though for an issue as complex as this one. Can you smoke test the issue_687 branch please?

**Comment by mjordan** [comment]
@rosiel I'd like to merge this branch into main. All integration tests pass. Do you want to give it a smoketest before I merge?

**Comment by mjordan** [comment]
Closed with f03f97be8f9e7568146bcef046c9f7cd1ea83db5. Documentation updates coming next.
