### ISSUE TITLE
`add_media` tasks which use `additional_files` don't process the (mandatory) `file` column.

### ISSUE THREAD

**Issue by rosiel** [mjordan/islandora_workbench#688]
I had a set of media to add where one file, the one in the file column, was present for every row. A secondary file was added as an "additional file" for some but not all rows. In order to ensure that the file column was present and accurate I set allow_missing_files to False. Per #687, that failed so I set it to True. 

* `--check` fails if the file in column `file` is missing
* during the run, the file in column `file` is completely ignored.

This is probably a documentation issue and maybe I read it wrong.

**Comment by mjordan** [comment]
@rosiel you shouldn't have to set `allow_missing_files` to false, it's false [by default](https://github.com/mjordan/islandora_workbench/blob/main/WorkbenchConfig.py#L166). That said, setting it to false in your config *should* have zero implications. Can you try not setting it to false in your config to see if the problems persist? 

I'll follow up on #687.

**Comment by rosiel** [comment]
I'm sorry I mentioned 'allow_missing_files' because it has nothing to do with this problem.

If there are additional files, the `file` column does not get processed.

**Comment by mjordan** [comment]
Closed with f03f97be8f9e7568146bcef046c9f7cd1ea83db5.
