### ISSUE TITLE
Add ability to create URL aliases

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#69]
It would be useful to allow input CSVs to contain URL aliases so they can be assigned on node creation. However, a URL alias assigned to a node using the standard add/edit form is not showing up in the _format=json output. Will investigate further.

**Comment by mjordan** [comment]
This works: `curl -v -X POST -uadmin:islandora -H"Content-type: application/json" --data '{"path":[{"value":"\/node\/197"}],"alias":[{"value":"\/Iamanalias"}]}' "http://192.168.50.111:8000/entity/path_alias?_format=json"`

"URL alias" REST endpoint needs to be enabled first.

**Comment by mjordan** [comment]
This ability should be generalized out to include updating and deleting aliases.

**Comment by mjordan** [comment]
You can assign URL aliases to nodes by adding the `url_alias` field to you CSV file, like this:

```
file,title,field_description,url_alias
IMG_1410.tif,Small boats in Havana Harbour,Some are blue.,/havana_boats
IMG_2549.jp2,Manhatten Island,Manhatten is part of New York City.,/manhatten
```

URL aliases must start with a forward slash (`/`). Also note that this feature is only available in the `create` task.

**Comment by dnwk** [comment]
I just tried adding url_alias column into my spreadsheet, it didn't do anything and no error in the log

**Comment by dnwk** [comment]
Thank you.

FYI Here is what's in my spreadsheet
url_alias
/theses/20201121

**Comment by mjordan** [comment]
One thing to check - Drupal allows a node to have only one URL alias. Does the node you are applying that to using Workbench already have a URL alias?

**Comment by dnwk** [comment]
This is "create" task. So after ingest, I go check on individual items that's ingested. I saw they only have the automatically generated URL. 
By the way, the site currently doesn't have a valid SSL certificate. I have to set secure_ssl_only to false. I don't know if it's reverent.

**Comment by mjordan** [comment]
`set_secure_ssl: false` is OK.

Assigning URL aliases works for me as documented at https://mjordan.github.io/islandora_workbench_docs/aliases/, for both `create` and `update` tasks. Here are my configs and CSVs:

`create` task:

```
task: create
host: "http://localhost:8000"
username: admin
password: islandora
nodes_only: true
input_csv: aliases_test.csv
```
```
file,id,title,field_model,url_alias
IMG_1410.tif,01,URL alias test - Small boats in Havana Harbour,25,/foo
IMG_2549.jp2,02,URL alias test - Manhatten Island,25,/bar
```
`update` task:

```
task: update
host: "http://localhost:8000"
username: admin
password: islandora
input_csv: update_aliases.csv
validate_title_length: false
```
```
node_id,url_alias
15,/i_am_node_15
16,/i_am_node_16
```

If this isn't working for, we'll need to dig deeper to find out why.

**Comment by dnwk** [comment]
OK. I can confirm existing pattern configuration /admin/config/search/path/patterns   overrides the url_alias in the spreadsheet. When I disable the pathauto pattern, it works.  Maybe pointing this out in documentations. Or find a way to adjust url_alias after pathauto done its job?

**Comment by dnwk** [comment]
I was trying to keep thesis URL stable. So, I do need the url alias to actually showing up on the browser bar. But I think I have a solutions right now to work the alias. 

Thank you
