### ISSUE TITLE
Ingesting content into groups

### ISSUE THREAD

**Issue by flummingbird** [mjordan/islandora_workbench#696]
I have a use case for using workbench along with the islandora_group module by digitalutsc to ingest content into groups with workbench.

In my workbench csv there is a header for "field_access_terms" which is entered as an Islandora Access taxonomy term number.

@kylehuynh205 showed me a change to workbench_utils.py that lets workbench ingest directly into a group:

The following would be added to the media_json of workbench_utils.py starting on line 3460 
`"field_access_terms": [{
                    "target_id": csv_row['field_access_terms'],
                    "target_type": 'taxonomy_term'`

**Comment by mjordan** [comment]
Instead of adding a hard-coded reference to a specific field, I'd rather address #606 so we can update any supported type of field in media. Since `field_access_terms` is just a regular taxonomy reference field, #606 will cover it.

**Comment by mjordan** [comment]
@flummingbird as of this evening, you can now update all supported field types on media, including taxonomy term reference fields, which covers your use case here. Closing this issue, but feel free to repoen if still have problems.
