### ISSUE TITLE
CSVs generated during get_data_from_view tasks don't respect view_parameter

### ISSUE THREAD

**Issue by dara2** [mjordan/islandora_workbench#698]
I’m using `get_data_from_view`, and I ran it three times on a view I’d created, attempting to get 3 sets of records: one set belonging to Institution A, one set belonging to Institution B, one set belonging to Institution C, using "field_institution" as a view_parameter in my .yml files. In my yml files, I set up view_parameters to only dump objects that had the field_institution taxonomy term corresponding to one institution. My 3 yml files each had a different name. However, it seems that each time I ran the task, the CSVs that were created don't seem to respect the view_parameter I set in my yml files. 

Here's one of the yml files I ran, setting a parameter of "Historical Society of Pennsylvania" (HSP):
```
task: get_data_from_view
host: "https://mysite.org"
view_path: '/workbench-export'
username: xxx
password: xxx
export_csv_field_list: ['title', 'field_pid', 'field_collection', node_id]
# Identify any URL parameters configured for the View (e.g., an exposed filter).
# Note that values in the 'view_parameters' configuration setting are literal
# parameter/operator/value strings,not YAML key: value pairs.
view_parameters:
 - 'field_institution=Historical Society of Pennsylvania'
 ```
 But I got records belonging to the other 2 institutions as well as HSP. I confirmed the term name is exactly as I have it in the view_parameter.

**Comment by mjordan** [comment]
When you view, in your browser, the View URL including that parameter, are the items in the resulting output what you expect or do they als contain items belonging to the other two institutions?

**Comment by dara2** [comment]
How do I add the view parameter to the view URL?

**Comment by dara2** [comment]
Is it like `&view_parameter=...`?

**Comment by mjordan** [comment]
Yes. Can you try both of these?

- `field_institution=Historical Society of Pennsylvania`
- `field_institution=Historical%20Society%20of%20Pennsylvania`

**Comment by dara2** [comment]
../workbench-export&field_institution=Historical%20Society%20of%20Pennsylvania and ../workbench-export&field_institution=Historical Society of Pennsylvania both gave 404s. Did I set up those URLs correctly? (My view URL is /workbench-export.)

**Comment by mjordan** [comment]
Hard to say since the URLs are determined by the View configuration. Is `field_field_institution` a text field or taxonomy reference?

**Comment by dara2** [comment]
`field_institution` is a taxonomy reference field.

**Comment by mjordan** [comment]
Can you try using the term ID as the parameter value instead of the term name?

**Comment by dara2** [comment]
../workbench-export&field_institution=1389 also gives a 404.

**Comment by mjordan** [comment]
Sorry, I don't know. It's hard to say what's wrong without having access to your specific View configuration. Over the weekend I'll create a taxonomy term "Historical Society of Pennsylvania" and give it a try locally.

**Comment by dara2** [comment]
Okay, thanks! I am curious whether it has anything to do with the spaces in the term name. Here are screenshots of my View if it helps at all. There is filter criteria including the "Held by" field (field_institution) - I'm wondering if that being open (allowing any term) could affect the exported CSV? Like would it override my view_parameter?
![Screenshot 2023-10-13 at 3 29 44 PM](https://github.com/mjordan/islandora_workbench/assets/72275887/33174a83-8fc9-46d3-9d60-be75933d264d)
![Screenshot 2023-10-13 at 3 29 36 PM](https://github.com/mjordan/islandora_workbench/assets/72275887/5a9de3b9-c6b8-4c64-b12c-9463d7260a29)

**Comment by mjordan** [comment]
> I am curious whether it has anything to do with the spaces in the term name

I don't know - that's what I am going to test first.

> There is filter criteria including the "Held by" field (field_institution)

Do you mean that this field is a  "Views: Filter by an entity reference View" taxonomy reference field? If so, that's probably it. If so, that's probably the issue.

**Comment by dara2** [comment]
It's what is in the second screenshot. It's a filter on Content: Held By (which is the field_institution taxonomy reference field) and it's set to any term in that taxonomy. It carried over into the REST display from when I was testing out the Page display of the view. I didn't think the filter would matter, because if it were respected by Workbench then why wouldn't I just set my parameter there and run the Workbench task? I figured Workbench was only paying attention to the view_parameter specified in the yml file. Perhaps the instructions could specify **not** to include any other filter criteria? Or if filters CAN be used (in place of view_parameter), maybe that could be indicated?

**Comment by mjordan** [comment]
Workbench only respects the parameters in the config file. I can add that to the docs.

**Comment by dara2** [comment]
If that's the case, then it shouldn't matter that I have the filter in the REST export display of the view, right?
So I'm confused...

**Comment by mjordan** [comment]
All the filters in the "Filter criteria" section of your View apply. The only URL parameters that can be used in the View must be provided in the config file.

**Comment by dara2** [comment]
Got it. Okay, then I think it would be helpful to say something about that in the documentation. Thank you for explaining!

**Comment by mjordan** [comment]
Thanks, I will.

**Comment by mjordan** [comment]
I've opened a separate documentation issue. OK to close this one?

**Comment by dara2** [comment]
Yes, thanks!
