### ISSUE TITLE
Improve docs on generating CSV data from a View

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#699]
Related to #698.

https://mjordan.github.io/islandora_workbench_docs/generating_csv_files/#using-a-drupal-view-to-identify-content-to-export-as-csv needs some clarification on how URL parameters are used. Specifically, the screenshot is missing the right-most part of the Views configuration, and the role of filters in the "Filter criteria" section of the Views configuration needs to be made explicit. Basically, all of those filters take effect, and any URL parameters used as filters are additional to the one configured there.

Thanks to @dara2 for pointing this out.

**Comment by mjordan** [comment]
@dara2 I've updated the docs on configuring Views to use as the basis for exporting CSV data. Can you take a look at the updates to verify that they distinguish between Contextual Filters and the other type of filter ("Filter Criteria") clearly?

**Comment by dara2** [comment]
Yes, this is great - thank you! I followed the updated documentation recently to build a view and it worked as expected.

**Comment by mjordan** [comment]
Very good, thank you for taking a look and getting back to me.
