### ISSUE TITLE
Numeric characters in relation codes for 'typed relation' field result in Workbench validation error

### ISSUE THREAD

**Issue by eldonquijote** [mjordan/islandora_workbench#701]
https://github.com/mjordan/islandora_workbench/blob/7c66389df6e8da97b326318dbc21a56e3468cfb6/workbench_utils.py#L5491
assumes that the relationship code for typed relation fields contains all letters (as is the case with MARC relator codes). We are using AAT terms to describe roles/relationships in addition to MARC relator codes; the AAT term identifiers are numbers though. Workbench throws a validation error for an entry in an import CSV like aat:300024987:person:Wees, J.L., even if the relation is listed in the field configuration (aat:300024987|architect (aat)). Ideally, Workbench should accept/validate alphanumeric values as configured.

**Comment by mjordan** [comment]
Can you check out the issue_701 branch and test?

**Comment by eldonquijote** [comment]
https://github.com/mjordan/islandora_workbench/blob/d55dea766548cce675e8581565bb4af97a5817fc/workbench_utils.py#L5491 gives me a regex parsing error:
                        if not re.match("^[09-0a-zA-Z]+:[0-9a-zA-Z]+:.+$", field_value.strip()):
should probably be 
                        if not re.match("^[0-9a-zA-Z]+:[0-9a-zA-Z]+:.+$", field_value.strip()):

**Comment by eldonquijote** [comment]
(Seems to work fine if I correct the typo locally.)

**Comment by mjordan** [comment]
Duh, thanks, I'll fix that.

**Comment by mjordan** [comment]
OK, typo fixed, can you retest?

**Comment by eldonquijote** [comment]
Works great, thank you very much!

**Comment by mjordan** [comment]
Issue_701 branch merged into main. Thanks again @eldonquijote for finding this and for testing the fix.
