### ISSUE TITLE
Add Github workflow to check style

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#712]
The Islandora [LSAP](https://docs.google.com/document/d/1luNwv9P19IGkka6ID27Il7xK4BTWV_Zbetridue997Y/edit) requires a Github workflow to automatically check code style.

**Comment by joecorall** [comment]
This can be closed by https://github.com/mjordan/islandora_workbench/issues/585 // https://github.com/mjordan/islandora_workbench/pull/744
