### ISSUE TITLE
Improve memory management when downloading large files

### ISSUE THREAD

**Issue by joecorall** [mjordan/islandora_workbench#719]
Currently a file that is loaded from workbench is fully loaded into the workbench script's memory before it's written to a temporary file on disk. We should stream the response instead so then entire file does not need to be in memory.

## More information

https://islandora.slack.com/archives/C01TLCB0EEQ/p1702252050833559

**Comment by mjordan** [comment]
Merged with f03f97be8f9e7568146bcef046c9f7cd1ea83db5.

Thanks very much @joecorall and @ajstanley for testing!
