### ISSUE TITLE
Reimplement fields as objects

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#72]
The main workbench script is already a scary rat's nest of conditional logic to deal with a very small set of field types (text, EDTF date, taxonomy and linked nodes) and whether or not they are single-or-multi-value. It makes sense to start discussing the advantages of implementing "fields" as object-oriented classes:

* easier to introduce more field types (we need to do this anyway); someone was asking about support for Paragraphs recently and I had to respond with a 🤷‍♂ 
* simpler core `workbench` script (at the expense of more class files) with less, or at least more readable, nested logic
* better ability to use more unit tests

Pinging @seth-shaw-unlv on this but would welcome anyone's input.

**Comment by seth-shaw-unlv** [comment]
That sounds reasonable to me. Honestly, it has been a while since I plumbed the depths of the workbench code, but I see the benefits of what you describe.

**Comment by mjordan** [comment]
Some implementation notes. Workbench can use the following technique to package each field class in a file named after the Drupal field type ("typed_relation", "entity_reference", "simple" for text, int, etc.) that it can then load dynamically based on the type of the current field.

Given a file `Dog.py`:

```
def dostuff():
    print("I am a dog")
```

A file `main.py`:

```
import importlib

module = 'Dog'
mod = importlib.import_module(module)
mod.dostuff()
```
will print "I am a dog".

**Comment by mjordan** [comment]
More implementation notes.

#### Fields share the following methods

- create
- update

These methods return the JSON that is added to the node object.

#### Arguments

- config
- definition
- csv_row_value (i.e. the value of the field in the incoming CSV row)
- node_value (i.e. values existing in the field on the node)
    
#### Example usage

- `field_json = field.create(config, definition, csv_row_value, node_value)`
- `field_json = field.update(config, definition, csv_row_value, node_value)`

These classes would be unit testable without interacting with a live Islandora instance since the expected return JSON could be predicted based on the arguments.

**Comment by mjordan** [comment]
This was completed with [c5014d5](https://github.com/mjordan/islandora_workbench/commit/c5014d5b60a66e42063d949acd9b42ce3701378a). Sorry not to close back then.
