### ISSUE TITLE
Validate that title does not exceed 255 characters

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#73]
That's the maximum allowed length.

**Comment by seth-shaw-unlv** [comment]
Unless they are using https://www.drupal.org/project/title_length or the (relative) newcomer https://www.drupal.org/project/entity_title_length

**Comment by mjordan** [comment]
Yup, I'll add a note about that.

**Comment by mjordan** [comment]
Gonna add a config variable that lets you turn off title length validation, which you would add if you were using one of those modules.
