### ISSUE TITLE
Import crashes on encountering big file

### ISSUE THREAD

**Issue by BrzIGH** [mjordan/islandora_workbench#787]
Hi folks,

running get_islandora_7_content.py with **get_file_url: false** and **fetch_files: true** consistently kills my import. I have since discovered that the record in question has a huge 4.5GB file attached.
Would be nice to be able to exclude a specific PID from the data import and/or increase the file download timeout and/or set a set of rules to skip downloading files larger than a certain size.
Thanks

**Comment by mjordan** [comment]
To clarify, you say "import" but his is happening when you are running `get_islandora_7_content.py` to export content from the Legacy Islandora, correct. Just want to make sure I understand.

**Comment by BrzIGH** [comment]
Yes, when I import to my device using the script you mention to create a .csv that will then be used to migrate to V2.

No problems – with English being the 4th language that I learned (as well as geriatric issues 😊 ) I sometimes do not express myself most accurately.

But I keep trying…
