### ISSUE TITLE
Allow some config settings to be passed in as command-line arguements

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#792]
Over at https://github.com/mjordan/islandora_workbench/issues/789#issuecomment-2150677929 @khart20 asked about specifying `input_csv` on the command line. I think this might be useful in a lot of cases (reduce minor edits to config files, testing, scripted use of Workbench). I think we could provide the ability to do this for any config setting that takes a simple string as its value. Don't think allowing complex data structures like lists will be practical, but maybe.

**Comment by khart20** [comment]
Also I'll add, we use the same name for output file and just add _output at the end.  I wonder if most others do the same and perhaps you just need to put in one filename to save even more typing?

**Comment by mjordan** [comment]
Hi @khart20 I don't know how common this is but I'm a little reluctant to introduce much more "magic" behavior as doing so comes with substantial invisible code complexity, e.g. what if the user doesn't want that to happen, what do they need to do? That said, I encourage people to drop a comment here if they would like to see this feature.

**Comment by mjordan** [comment]
@khart20 @edlington I've got --input_dir, --input_csv, --google_sheets_gid, and --log_file_path for create tasks working as command-line arguments. Would these be a good start?

@khart20 I recently did some work to provide [filename templates for rollback files](https://mjordan.github.io/islandora_workbench_docs/rolling_back/#using-rollback-filename-templates. I could probably do something similar for the output CSV as well. Can you let me know which output CSV in particular you are interested in appending _output to?

**Comment by edlington** [comment]
@mjordan yes! those variables as command line arguments are really helpful for me. thank you!!!!

**Comment by mjordan** [comment]
@khart20 let me know if you'd like me to proceed with creating a filename template for the output CSV.
