### ISSUE TITLE
Allow more control over the rollback (delete) input CSV

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_workbench#844]
Currently, the default filename for the input CSV used by rollbacks (which are delete tasks) is "rollback.csv", generated during `create` tasks and written by default in the input_dir. There are only two configuration settings available to override the location and filename:

- `rollback_dir`, which determines the directory "rollback.csv" is written to
- `timestamp_rollback`, which appends a timestamp to the filename, e.g. "rollback.2021_11_03_21_10_28.csv"

It would be useful to provide some additional options that allow control over the input CSV filename, e.g. during large migrations or automated workflows. These options should probably apply to the "rollback.yml" file as well.

One mechanism for providing configuration options to do this is allowing users to create a template that is then applied to the filenames. Workbench already uses templates that provide commonly used variables. The two uses are [CSV value templates](https://mjordan.github.io/islandora_workbench_docs/csv_value_templates/) and the page_title_template configuration setting described [here](https://mjordan.github.io/islandora_workbench_docs/paged_and_compound/#field-data-applied-to-pageschildren). 

In the case of a configurable template for rollback input CSVs, two variables that would be useful are the name of the `create` task's configuration file and the name of the input CSV used in the `create` task. One implementation of a configuration setting that uses these might be:

```
rollback_csv_filename_template:
 - rollback_$task_config_filename-$task_input_csv_filename
```

Using this template in a `create` task with a config filename of "photos.yml" and an input CSV filename of "cats.csv" would generate a rollback input CSV with the namen "rollback_photos-cats.csv".  If we add a timestamp to that filename, it would be "rollback_photos-cats.2021_11_03_21_10_28.csv",

**Comment by dara2** [comment]
I think this sounds like a really useful configuration option, and I like your proposal.

**Comment by edlington** [comment]
@mjordan I like your proposed implementation. Thank you!!!

**Comment by mjordan** [comment]
The ability to use other files' names in the CSV should also be applied to the configuration (i.e., .yml)  file. The datestamp option already does.

**Comment by mjordan** [comment]
Updated docs are at https://mjordan.github.io/islandora_workbench_docs/rolling_back/
