### ISSUE TITLE
Adding Content display in column and increase number

### ISSUE THREAD

**Issue by malone09** [mjordan/islandora_workbench#860]
How can I add an additional column, such as "Node ID", to the column listing on this display? Also, is it possible to increase the number of items displayed per page from 1-50 to 1-100?
![display](https://github.com/user-attachments/assets/cd9ed767-714a-4955-b607-1bf05e7bb491)

**Comment by mjordan** [comment]
Looks like that is a View (`admin/structure/views/view/content`) so you should be able to add whatever fields you want to it. But I don't know what will happen to your changes when you upgrade Islandora. You may want to ask about this on the Islandora Slack, someone there might know more about this than I do.
